---
title: "Accommodation"
order: 6
---

For the cheapest accommodation options, we recommend reserving a room at one of several university halls which are hired out to visitors over the summer. A single room with shared bathroom facilities can be acquired from £45 a night, with the cheapest ensuite options starting from £65. You can use the following links to assess options:

* [University College London (UCL)](https://www.ucl.ac.uk/residences/ucl-summer-residences)
* [London School of Economics (LSE)](https://www.lsevacations.co.uk/Home.aspx?gclid=Cj0KCQjwlPWgBhDHARIsAH2xdNeLF6l90iOO7Ypmb1l6c76dCWuvnnMO-r2TooTQov1T1cRQ7IZcSqMaAuPMEALw_wcB)
* [King’s College London (KCL)](https://www.kcl.ac.uk/accommodation/summer-accommodation)
* [Imperial College London (ICL)](https://www.imperial.ac.uk/visit/summer-accommodation/)

Many major chain hotels can also be found within 10–15 minutes walking distance of UCL, with rates for a double ensuite starting from around £100 a night. Some suggestions include:

* [Premier Inn London Euston](https://www.premierinn.com/gb/en/hotels/england/greater-london/london/london-euston.html?cid=GLBC_LONEUS)
* [Premier Inn London St. Pancras](https://www.premierinn.com/gb/en/hotels/england/greater-london/london/london-st-pancras.html)
* [Hub by Premier Inn Goodge Street](https://www.premierinn.com/gb/en/hotels/england/greater-london/london/hub-london-goodge-street.html)

Multiple independent hotels also operate in the area, which can be viewed on [booking.com](https://www.booking.com/). 

We recommend booking as soon as possible to keep prices lower!
