---
title: "Entertainment"
order: 8
---

## Our favourite pubs (tried and tested of course)! 

* **Prince of Wales Feathers** – bustling pub with a roof terrace perfect for a summer’s eve!
* **Smuggler’s Tavern** – A cosy, nautical themed pub serving some very decent pizzas. On the second Friday of every month, the tavern has a karaoke night. We’re still unsure whether this is a good or bad thing. Probably both. 
* **Carpenter’s Arms** – Cosy and slightly off the beaten track so doesn’t get busy too quickly. 
* **Lore of the Land** – A very appealing wood panelled pub with a fancy restaurant upstairs. They win the award for the best smelling hand sanitizer.

## Things to do in the immediate area

* **UCL’s Grant Museum of Zoology** (1–5pm Tues to Fri) – a five-minute walk from the workshop, this little museum hosts thousands of Zoological specimens in cabinets and jars. Highlights include the Micrarium and the (in)famous Jar of Moles.

* **Green Spaces** – Head just a few minutes away from Euston Road and you’ll find a variety of green spaces perfect for a short stroll, reading a book, or a picnic. Close to UCL you can find Gordon Square, Tavistock Square Gardens, and Russell Square. For a larger space, we’d recommend the trip to Regent’s Park, home to London Zoo.

* **Wellcome Collection** (10am–6pm) – Located opposite the Kathleen Lonsdale Building, the Wellcome Collection hosts a series of rotating exhibitions focused on science, medicine, life, and art. Apparently there’s a lovely library open to everyone too!
