---
title: "Food and Drink"
order: 7
---

## Our favourites near Campus

UCL benefits very heavily from its central London location, and is only a short walk, bus, or tube away from areas such as Soho, Covent Garden, Islington, and Camden. For the closest lunch or dinner options within around five minutes of campus, we recommend the following:

* **Bloomsbury Farmers’ Market (Thursday only)** – a big favourite with everybody in the office. Taking place in Torrington Square from around 12--2pm every Thursday, there are usually over 20 stalls selling a huge range of cuisines. Prices generally fall just under <£10.
* **Roti King** – very tasty Malaysian and Singaporean street food. You can’t book here, and queues often form outside if you want a table, but it’s worth it. You can pre-order and collect, or they will also deliver to UCL. Prices for main dishes range from £5--10.
* **Noodle & Snack 面道坊** - amazing handmade noodles and broths! The restaurant is small, and it can get very busy around lunch and dinner if you’re hoping to sit in, but they also do takeaway. A main and a side should cost £10--20.
* **Franco Manca** – Good quality sourdough pizzas for <£10. Both eat in and takeaway options are available.
* **Rosa’s Thai** – A large selection of tasty Thai dishes with a sizeable number of vegetarian and vegan options. Lunch will likely cost £10--20 per person. Eat in and takeaway options are available.
* **Mestizo** – delicious Mexican food with a large number of items on the menu. Expect a meal for one to cost around £20.

## On Campus

UCL’s cafes all serve a similar selection of hot and cold drinks, sandwiches, salads, and microwaveable meals averaging around £5--6. All of those listed here are within 3-4 minutes of the Kathleen Lonsdale Building, and are open from 8am onwards. 

The main canteen (Wilkins Terrace and Lower Refectory) is open throughout the day, and offers a variety of cooked meals costing around £5--7.

* **George Farha Café** (8am--6pm) – the neighbour to the Kathleen Lonsdale Building
* **Print Room Café** (8am--8pm) – perhaps the nicest setting if the sun’s out as there’s seating in a nice courtyard. As well as the usual sandwiches and salads, this café also serves a few cooked options such as pasta dishes.
* **Gordon’s Café** (8am--7pm) – Similar to George Farha, but with the bonus addition of pizza!
* **Wilkins Terrace and Lower Refectory** (8--10:30am, 11:30am--7pm) – located on the lower level of campus, the canteen houses 3 or 4 different outlets selling a variety of cooked dishes.
