{
  "hash": "3a0f10ad0ebfd21839c7bf2695312721",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Processing II\"\nsubtitle: \"Data Processing II: Data Harmonization and Synthesis\"\ntoc: true\norder: 5\n---\n## Learning Objectives\n\nIn this session, we'll walk through how to effectively visualize data. We'll cover:\n\n- Why data visualization is important\n- Strategies for effectively visualizing data\n- How to create basic graph types in R\n\nYou'll also walk away with some example code to modify and adapt to your own work.\n\n## Plan for the Session\n\nThe session will be split into the following sections:\n\nI.   Theory of data visualization\nII.  Data visualization practical\n\n## Schedule\n\n1:30–3:15 PM\n\n## I. Theory of data visualization\n<iframe class=\"slide-deck\" width=\"100%\" height=\"800px\" src=\"data_viz_gsa.html\"></iframe>\n\n## II. Data visualization practical\n\n### Getting familiar with ggplot2\n\n[`ggplot2`](https://ggplot2.tidyverse.org/index.html) is designed around the \"grammar of graphics\". In most cases you start with `ggplot()` and then supply a dataset and \"aesthetic\" mappings (with `aes()`). You then add on individual layers (like `geom_point()` or `geom_histogram()`) to add the visualization(s) that you want. Let's first try making a scatterplot using some built-in data about car mileage (`mpg`). In this case, we'll plot the highway mileage with respect to the engine size (displacement). Note that in this case, instead of calling functions separately, we chain them together with the `+` operator.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the ggplot2 package\nlibrary(ggplot2)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check out the mileage data\nhead(mpg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 11\n  manufacturer model displ  year   cyl trans      drv     cty   hwy fl    class \n  <chr>        <chr> <dbl> <int> <int> <chr>      <chr> <int> <int> <chr> <chr> \n1 audi         a4      1.8  1999     4 auto(l5)   f        18    29 p     compa…\n2 audi         a4      1.8  1999     4 manual(m5) f        21    29 p     compa…\n3 audi         a4      2    2008     4 manual(m6) f        20    31 p     compa…\n4 audi         a4      2    2008     4 auto(av)   f        21    30 p     compa…\n5 audi         a4      2.8  1999     6 auto(l5)   f        16    26 p     compa…\n6 audi         a4      2.8  1999     6 manual(m5) f        18    26 p     compa…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nYou'll notice that with just a couple of lines, we've already made a pretty nice visualization. `ggplot2` does most of the work for us once we specify our `x` and `y` variables. Let's go a step further and color the points by another variable (e.g., the class of the car). With `ggplot2`, all that requires is specifying another aesthetic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nNotice that `ggplot2` comes with its own default color scheme. I would strongly discourage you from using the default colors. Instead, we'll try out some of the accessible color palettes we talked about earlier. First, let's try one of the `viridis` color palettes. Since this palette is included in `ggplot2`, all we need to do is add the proper \"scale\" to our `ggplot()` call.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_viridis_d()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nHmm...with this many colors, it becomes a little hard to distinguish between the colors with this color palette. Let's try one of the [brewer color palettes](https://r-graph-gallery.com/38-rcolorbrewers-palettes.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_brewer(palette = \"Set1\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nOutside of color, there are many other [aspects of the graph](https://ggplot2.tidyverse.org/articles/ggplot2-specs.html) that we can modify using \"scale\"s. For example, we can modify the x and y axes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n#### Theming\n\nThe last basic thing you might want to do with `ggplot2` is modify the style of the visualization. This is extremely customizable, but the first place to start is with a [built-in theme](https://ggplot2.tidyverse.org/reference/ggtheme.html). I personally prefer the classic theme:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nUsing this built-in theme has changed many visual aspects of the graph, including changing the plot background color, adding axis lines, and removing the internal grid lines. If you look very closely, however, the axis tick labels are still a slight grey. We can use the `theme()` function to further customize the appearance and change this. In this case, we'll make the axis text elements have a black color.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nAnd there we have it! With just 7 lines we've created what I would say is a publication quality graph! `ggplot` does a lot of the tedious work for you, giving you time to focus on the more important aspects, such as labeling and color. Admittedly, I've spent a LOT of time on these aspects in the past...\n\nFor comparison, here's how we would produce a similar graph using only R's built-in (base) plotting functions. It's worth taking a moment to see how ggplot's additive functions all work together to produce a final product, whereas base R requires lots of simultaneous arguments inside a single function, plus sequential additive functions that ggplot accounts for by default (e.g., adding a legend).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(x = mpg$displ, y = mpg$hwy,\n     col = factor(mpg$class), pch = 16,\n     xlab = \"Engine Displacement (l)\",\n     ylab = \"Highway Mileage (mpg)\")\nlegend(\"topright\", legend = unique(mpg$class), cex = 0.8,\n       pch = 16, col = unique(factor(mpg$class)),\n       ncol = 2, bty = 'n', title = \"Vehicle Class\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\nMore information about all of the hierarchical theme components that you can customize is available [here](https://ggplot2.tidyverse.org/reference/theme.html). In order to change many of these components, you need to use theme elements like we did above with `element_text()`. That and other theme elements are documented [here](https://ggplot2.tidyverse.org/reference/element.html).\n\n### More complex features\n\n#### Facetting\n\nLet's take our scatterplot example from earlier and make it a little more complex with another aesthetic:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class, shape = drv)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_shape_discrete(name = \"Drive Type\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nNow, what if we wanted to also split the data by the years the cars were manufactured? We're already using color and shape, so what other aesthetic could we use? We could possible use some shapes that have both a fill and outline color, but that sounds messy. Instead of using another aesthetic, we could also use a `facet`. This splits the chart into multiple panels:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class, shape = drv)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_shape_discrete(name = \"Drive Type\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  facet_wrap(vars(year)) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nWe can get even crazier by faceting by multiple variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = displ, y = hwy, color = class, shape = drv)) + \n  geom_point() +\n  scale_color_brewer(name = \"Vehicle Class\", palette = \"Set1\") +\n  scale_shape_discrete(name = \"Drive Type\") +\n  scale_x_continuous(name = \"Engine Displacement (l)\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  facet_grid(rows = vars(cyl), cols = vars(year)) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nOK, maybe we've gone a little too far here, but you get the picture!\n\n#### Other layers\n\nThere are many other [types of plots](https://ggplot2.tidyverse.org/reference/#layers) that we can make with `ggplot2`.\n\n##### Histograms\n\nWe can visualize the density of values for a single variable with a histogram:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = hwy)) + \n  geom_histogram() +\n  scale_x_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nNote how histograms don't require a y-axis aesthetic by default. The counts are tabulated for you.\n\n##### Boxplots and Violin Plotss\n\nWe can visualize the density of values for a single variable across a discrete variable with boxplots or violin plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = as.factor(cyl), y = hwy)) + \n  geom_boxplot() +\n  scale_x_discrete(name = \"# Cylinders\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mpg, aes(x = as.factor(cyl), y = hwy)) + \n  geom_violin(scale = \"width\", draw_quantiles = c(0.25, 0.5, 0.75)) +\n  scale_x_discrete(name = \"# Cylinders\") +\n  scale_y_continuous(name = \"Highway Mileage (mpg)\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The `draw_quantiles` argument of `geom_violin()` is deprecated as of ggplot2\n4.0.0.\nℹ Please use the `quantiles.linetype` argument instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nNote that many of these \"geom\"s have lots of options. For example, we've decided to `scale` all of the violin plots to the same width and to draw the quartiles on them (mimicking the boxplots above).\n\n##### 2D Contours\n\nWe can also visualize the density of values across two continuos variables using a 2D contour. Here we'll use the built-in Old Faithful waiting time/eruption duration data (`faithful`). We'll expand the axes a little bit to better show the contours:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(faithful, aes(x = eruptions, y = waiting)) +\n  geom_density_2d(linewidth = 0.25, colour = \"black\") +\n  xlim(0.5, 6) +\n  ylim(35, 110) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n#### Combining layers\n\nWe can also combine multiple layers to show the same data in different ways in the same plot. For example, we could show the raw data for the above contour plot in addition to the contours:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(faithful, aes(x = eruptions, y = waiting)) +\n  geom_point() +\n  geom_density_2d_filled(alpha = 0.5) +\n  geom_density_2d(linewidth = 0.25, colour = \"black\") +\n  xlim(0.5, 6) +\n  ylim(35, 110) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nNote that, when combining layers, the layers are added to the plot in order, so in this case the points are the bottom layer and the contour lines are the top layer. We changed the alpha of the middle layer to prevent the points from being blocked.\n\n##### Time Series\n\nWe'll use the built-in `economics` dataset to explore visualizing a time series. In this case, we are looking at unemployment over time:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(economics, aes(x = date, y = unemploy)) +\n  geom_line() +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n`geom_path()` lets you explore how two variables are related over time. For example, unemployment and personal savings rate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(economics, aes(x = unemploy/pop, y = psavert)) +\n  geom_path(aes(colour = as.numeric(date))) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nNote how we've used multiple columns of the data to define the x-axis here.\n\n### Your turn!\n\nLet's see what you and those sitting around you can produce using the iris dataset built into R. Here's a basic plot of Sepal Length versus Petal Length:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(iris)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sepal.Length Sepal.Width Petal.Length Petal.Width Species\n1          5.1         3.5          1.4         0.2  setosa\n2          4.9         3.0          1.4         0.2  setosa\n3          4.7         3.2          1.3         0.2  setosa\n4          4.6         3.1          1.5         0.2  setosa\n5          5.0         3.6          1.4         0.2  setosa\n6          5.4         3.9          1.7         0.4  setosa\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(iris, aes(x = Sepal.Length, y = Petal.Length)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nFeel free to edit the r script directly above by changing the variables, coloring the points by species, fixing the axis labels, etc.\n\n### Visualizing paleo data\n\nNow let's take a stab at visualizing some paleo data! First, let's load and prepare the packages we are going to need.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palaeoverse) # for data\nlibrary(ggplot2) # for plots\nlibrary(deeptime) # for fun plot additions\n```\n:::\n\n\nNow let's prepare our reef data that comes with the palaeoverse package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Assign a common time scale based on an interval key\ndata(reefs)\nreefs <- look_up(occdf = reefs,\n                 early_interval = \"interval\",\n                 late_interval = \"interval\",\n                 int_key = interval_key)\n# Remove pre-Phanerozoic data to focus our study\nreefs <- subset(reefs, interval_max_ma <= 541)\n# Extract Phanerozoic stage-level stages for time bins\nbins <- time_bins(interval = \"Phanerozoic\", rank = \"stage\")\n# bin_time requires \"max_ma\" and \"min_ma\" columns\ncolnames(reefs)[which(colnames(reefs) == \"interval_max_ma\")] <- \"max_ma\"\ncolnames(reefs)[which(colnames(reefs) == \"interval_min_ma\")] <- \"min_ma\"\nreefs <- bin_time(occdf = reefs, bins = bins, method = \"all\")\n# Bin occurrence data\nreefs_time <- group_apply(occdf = reefs, group = c(\"bin_assignment\", \"bin_midpoint\"), fun = nrow)\n# Clean these columns up\nreefs_time$bin_assignment <- as.numeric(reefs_time$bin_assignment)\nreefs_time$bin_midpoint <- as.numeric(reefs_time$bin_midpoint)\n# Check output\nhead(reefs_time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nrow bin_assignment bin_midpoint\n1    3            102      0.00210\n2    3            101      0.00620\n3    3            100      0.00995\n4  117             99      0.07035\n5   52             98      0.45150\n6   34             97      1.28700\n```\n\n\n:::\n:::\n\n\nAnd now we plot the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow)) +\n  geom_line() +\n  scale_x_reverse(\"Time (Ma)\", limits = c(541, 0), expand = expansion(0, 0)) +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n#### Timescales\n\nThe [`deeptime`](https://williamgearty.com/deeptime/index.html) package allows us to add a timescale to a `ggplot2` plot with a single line (just like `palaeoverse` does in base R graphics). `coord_geo()` is one of many [coordinate systems](https://ggplot2.tidyverse.org/articles/ggplot2.html#coordinates) that exist in the `ggplot2` ecosystems. Often coordinate systems are used to alter the positions of aesthetics, but in this case `coord_geo()` adds a timescale to one or more of the axes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow)) +\n  geom_line() +\n  scale_x_reverse(\"Time (Ma)\") +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  coord_geo(xlim = c(541, 0)) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nWe can stack multiple timescales or have timescales on multiple sides:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow)) +\n  geom_line() +\n  scale_x_reverse(\"Time (Ma)\") +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  coord_geo(\n    dat = list(\"periods\", \"eras\"), xlim = c(542, 0),\n    pos = list(\"b\", \"b\"), abbrv = list(TRUE, FALSE)\n  ) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow)) +\n  geom_line() +\n  scale_x_reverse(\"Time (Ma)\") +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  coord_geo(\n    dat = list(\"periods\", \"eras\"), xlim = c(542, 0),\n    pos = list(\"b\", \"t\"), abbrv = list(TRUE, FALSE)\n  ) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n##### Timescale color palettes\n\nInstead of a line graph/time series, we could plot these reef counts as a bar graph (`geom_col()` in this case). However, to give a little more life to our graph, we'll go ahead and color each bar based on the official geological timescale color palette (included in `deeptime`). First we need to get the stage names and the beginnings and ends of the bins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get stage names\nreefs_time$stage <- bins$interval_name[reefs_time$bin_assignment]\n\n# Get beginning and end of bins\nreefs_time$bin_max_ma <- bins$max_ma[reefs_time$bin_assignment]\nreefs_time$bin_min_ma <- bins$min_ma[reefs_time$bin_assignment]\n```\n:::\n\n\nThen we can go ahead and make the desired bar graph:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow, fill = stage)) +\n  geom_col(aes(width = bin_max_ma - bin_min_ma)) +\n  scale_x_reverse(\"Time (Ma)\") +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  scale_fill_geo(dat = \"stages\", guide = \"none\") +\n  coord_geo(xlim = c(541, 0)) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\nWe could also group the stages by era and color them based on that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreefs_time$era <- cut(reefs_time$bin_midpoint,\n                      breaks = c(0, 66, 252, 542),\n                      labels = c(\"Cenozoic\", \"Mesozoic\", \"Paleozoic\"))\n\nggplot(reefs_time, aes(x = bin_midpoint, y = nrow, fill = era)) +\n  geom_col(aes(width = bin_max_ma - bin_min_ma)) +\n  scale_x_reverse(\"Time (Ma)\") +\n  scale_y_continuous(\"Number of reefs per stage\") +\n  scale_fill_geo(dat = \"eras\", guide = \"none\") +\n  coord_geo(xlim = c(541, 0)) +\n  theme_classic() +\n  theme(axis.text = element_text(color = \"black\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n#### Plot occurrences through time\n\nA common graph in paleontology is stratigraphic occurrences of taxa through time. The `palaeoverse` and `deeptime` packages have functions to instantly create graphs like these based on occurrence data. I'll focus on the `deeptime` version here since it uses `ggplot2`. First we'll grab some tetrapod occurrence data from the `palaeoverse` package and clean it up a little:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noccdf <- subset(tetrapods, accepted_rank == \"genus\")\noccdf <- subset(occdf, select = c(occurrence_no, accepted_name,\n                                  max_ma, min_ma))\noccdf$age <- (occdf$max_ma + occdf$min_ma) / 2\noccdf <- subset(occdf, accepted_name %in% c(\"Eryops\", \"Dimetrodon\",\n                                            \"Diadectes\", \"Diictodon\",\n                                            \"Ophiacodon\", \"Diplocaulus\",\n                                            \"Benthosuchus\"))\n```\n:::\n\n\nNow we'll use `geom_points_range()` to plot the occurrences as points and ranges:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# plot those occurrences\nggplot(data = occdf) +\n  geom_points_range(aes(x = age, y = accepted_name)) +\n  # geom_point(aes(x = age, y = accepted_name)) +\n  # geom_line(aes(x = age, y = accepted_name))\n  scale_x_reverse(name = \"Time (Ma)\") +\n  coord_geo(pos = list(\"bottom\", \"bottom\"),\n            dat = list(\"stages\", \"periods\"),\n            abbrv = list(TRUE, FALSE), expand = TRUE, size = \"auto\") +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nAnd that's that!\n\n\n\n## OLD\n## I. Introduction to Harmonization and Synthesis\n\nSo far, we've used R to carry out a variety of operations for acquiring and preparing palaeontological data. We can also use R to run analyses with the aim of answering specific research questions. We touched on this briefly during the last session when we looked at the latitudinal ranges of Crocodylia occurrences, but we can push our analyses further than that.\n\nIt will be of no surprise to anyone in this room that we are in the midst of a biodiversity crisis. Understanding and anticipating the changes that will occur to organisms, their communities, and the environments that they inhabit as a result of climate change and other anthropogenic stressors has emerged as a primary goal of our disciplines. Traditionally, modern ecologists have focused on studying current or recent historical processes to address questions related to biodiversity loss and the impacts of climate change, while palaeoecologists have studied long-term processes in the fossil record [(Nieto-Lugilde et al. 2021)](https://doi.org/10.1088/1748-9326/ac1b59). However, it is becoming increasingly clear that the answers to some of the most important questions relate to the fuzzy area between our modern and palaeo records:\n\n- Can past ecosystems be used as analogues for present-day ecosystems? Can we understand future changes to biodiversity by examining past losses?\n- What are the main drivers and consequences of collapse within communities and ecosystems?\n- When examining modern ecosystems, have crucial elements been lost? How can we set accurate baselines for conservation efforts?\n\nCombining datasets spanning different timescales can help us address these questions. As you've seen earlier today, there are a wealth of available datasets that contain information about organisms and climate today and in the past, be that across shallow or deep time. Individually these datasets track processes that operate on different spatial and temporal scales. For instance, the figure below from [Darroch et al. 2022](https://doi.org/10.1016/j.tree.2022.05.005) shows the potential drivers of geographic range in organisms across modern, historical and palaeontological timescales:\n\n![Figure from Darroch et al. 2022](Figure1.png)\n\nThis figure emphasizes that ecological patterns such as geographic range are driven by processes operating on a continuum. The past and present are interconnected, and both can provide valuable information that can be combined to improve our understanding of underlying ecological processes. By developing approaches to harmonize data across timescales, we can begin to utilize this information to better understand drivers of ecological change, improve predictions of future biodiversity responses, and cross the palaeontological-ecological gap.\n\nOne research area that has particularly benefitted from the harmonization of palaeo and modern occurrence data is that of Species Distribution Models, or SDMs. These models correlate occurrences of species with climatic and environmental variables, and then use these associations to predict the distribution of that species across time and space. Consequently, they are frequently used to forecast species range shifts and understand potential losses in biodiversity as a result of future climate change. However, only including modern occurrences in these models excludes a vast amount of data of where organisms may have occupied in the past, running the risk of only predicting the occupied niche as opposed to gaining an understanding of the fundamental niche of a species (e.g., [Veloz et al. 2012](https://doi.org/10.1111/j.1365-2486.2011.02635.x)). This can have serious knock-on effects when attempting to predict the distribution of species under different climate scenarios. Consequently, studies have started to use the historical and palaeontological distribution of occurrences within these models. As you can see below, including coral occurrences from the last interglacial drastically changes the predicted habitability of corals under different IPCC forecasted climate scenarios [(Jones et al. 2019)](https://doi.org/10.1098/rsos.182111):\n\n![](Figure2.jpg)\n\n![Figures from Jones et al. 2019](Figure3.jpg)\n\nAnother clear example of the harmonization of palaeo and modern data is in understanding long-term baselines of species abundances and distributions for conservation. This often involves combining records of presence or abundance that were collected in different ways over different timescales, and finding common currencies or other statistical approaches to align them. For example, by combining modern, historical, and palaeontological records of coral presence, [(Cramer et al. 2020)](https://doi.org/10.1126/sciadv.aax9395) examined the timing of coral decline in the Caribbean response to various regional and local stressors. They were able to track trends in coral abundance and community composition before recent ecological surveys, providing important baseline data for understanding the drivers of ongoing coral loss and where to target conservation and restoration efforts:\n\n![](Figure4.jpeg)\n\nA final example synthesizes pollen data from cores to quantify rates of vegetation change over thousands of years in different regions, which sets the stage for investigating feedbacks between various anthropogenic and environvental drivers [(Mottl et al. 2021)](https://doi.org/10.1126/science.abg1685). Databases like Neotoma contain a wealth of palaeoecological records such as this, alongside chronological information, that can be leveraged to reconstruct community change with relatively high temporal resolution in shallow time.\n\n![Figure from [Flantua et al. 2023](https://doi.org/10.1111/geb.13693)](Figure5.jpg)\n\nHowever, there are many considerations that have to be taken into account when carrying out this type of research, and a number of practical challenges that have to be overcome to ensure that the results we get are meaningful. Differences in spatial and temporal scales, data types, and various biases that impact our data sources all make this research difficult to carry out. Today, we are going to provide a brief introduction to this broad area of research, focusing in particular on the decisions that have to be made regarding our data and research approaches. Let's dig in!\n\n## II. Planning, Setup, and Finding Your Data\n\n### Our Research Question\n\nOur first step will be to define our research question, which will be framed around the dataset of Cenozoic Crocodylia that we worked on this morning. As mentioned previously, Crocs are an excellent group to use for studies comparing modern and deep time records: they have a very tight association with temperature, are well represented in the fossil record spatially and temporally, and many extant species are threatened by anthropogenic impacts including habitat loss and climate change.\n\nIn this section, we'll aim to answer the following research question: **How does the temperature range inhabited by Crocodylia in deep time compare to that seen in the present?**\n\nWe'll focus our deep time analysis on the Miocene, a climatically dynamic epoch in Earth's history that can serve as an analog for future climate scenarios (e.g., [Steinthorsdottir et al. 2020](https://doi.org/10.1029/2020PA004037)).\n\n### Making a Plan\n\nBefore we start, it's helpful to write out a step-by-step plan of what we want to accomplish to ensure that the approach we're taking and the code that we write will appropriately answer the question(s) that we are interested in. Think of this as a kind of \"logical flow.\" In other words, what are all the steps needed to get from our research idea to our finalised analysis? This can be as extensive as you wish and can be done in any fashion---even writing out your code or general approach on pen and paper! We'll be doing this a few times today, so let's start by considering our research question and what materials we'll need to address it.\n\n## **BREAKOUT SESSION 1**\n\n**Organize yourselves into groups of 4-6 and take 10 minutes to discuss the following questions:**\n\n***1. What datasets will we need to answer this question?***\n\n***2. What issues might we encounter when sourcing, gathering, and working with these various datasets? How might these be addressed?***\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\nAs we aim to compare the distributions of Crocodylia in deep time and the present, there are a couple of key datasets that we will require:\n\n1.  A spatially explicit dataset of modern Crocodylia\n2.  A spatially explicit dataset of Crocodylia in the deep time intervals we will assess\n3.  A spatially explicit dataset of modern climatic variables\n4.  A spatially explicit dataset of climatic variables for the deep time intervals we choose, likely generated from palaeo-climatic modelling\n\n:::\n\n::: {.callout-note title=\"Heads Up!\"}\nEven at this first step, the decisions we make will have consequences for our research and findings. For example, our choice of datasets and how they are handled can impact our results. This will be a recurring theme throughout the session.\n:::\n\n## III. Building a Workflow to Merge Datasets\n\nTo help you get an idea of the process of using data from different sources, we'll now walk through an example for how we might acquire and harmonize our climatic data. First, let's make a plan of the steps we'll take and some of the decisions we'll need to consider along the way.\n\n1.  **Decide which climate data to use.** What will be most appropriate variables for the taxonomic group we are studying? Some potential choices might be:\n\n-   The mean annual temperature\n-   The mean annual range of temperature\n-   The annual standard deviation of temperature\n-   The temperature of the hottest or coldest quarter\n\n2.  **Find a suitable source of data.** We will need to find spatially explicit climatic data for each time interval we are interested in and acquire it in an appropriate format (.nc). What factors might we consider?\n\n-   Availability of specifications listed above\n-   Spatial resolution\n-   Temporal resolution\n\n3.  **Sort file structure.** Ensure that your R project is set up appropriately and that the downloaded files are in an appropriate place to be used in your project, remembering to follow some of the guidance that we've covered earlier on today (e.g., ensuring there are raw versions of your data saved).\n\n4.  **Load data.** Read our data into R in an appropriate format to work with (e.g., raster). How might we do this? What packages might we need?\n\n5.  **Check formatting and prepare for analysis. ** Ensure that the data are formatted appropriately. How might this impact our results or interpretations? What issues should we be aware of?\n\n-   Do the data have the right extent for our research question and R pipeline, and can this be changed?\n-   Are they at an appropriate spatial/temporal resolution, and can this be changed?\n-   Are they in the right Coordinate Reference System?\n-   Are they capturing the same climatic information?\n\nIn terms of our R code, we might want to break down our steps further:\n\n-   Check the format of the data using the 'class()' function\n-   Make a reference raster with appropriate resolution and extent\n-   Ensure climate raster doesn't have wrapping/extent issues, and rotate if necessary\n-   Re-sample raster to our reference raster\n\nNow that we have a basic plan, we can start to put it into action. Before we begin, we'll need to install and load some packages that will allow us to work with our data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install necessary packages\n#install.packages(\"rgbif\")\n#install.packages(\"dplyr\")\n#install.packages(\"ggplot2\")\n#install.packages(\"palaeoverse\")\n#install.packages(\"raster\")\n#install.packages(\"sf\")\n#install.packages(\"geodata\")\n#install.packages(\"rnaturalearth\")\n#install.packages(\"ncdf4\")\n#install.packages(\"rgplates\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(rgbif)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(palaeoverse)\nlibrary(raster)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: sp\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'raster'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(geodata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: terra\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nterra 1.8.70\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rnaturalearth)\nlibrary(ncdf4)\nlibrary(rgplates)\n```\n:::\n\n\nNow that's done, let's get cracking! \n\n### 1. Deciding on climate data to use\n\nAs we want to link croc occurrences to temperature, we'll need to find some spatially explicit climatic datasets for both the modern and deep time. This will mean that we can extract the temperature associated with the geographic location of those occurrences which can then be compared between our time intervals of interest. \n\nWe've also decided to keep things simple today and use the mean annual temperature to answer our research question, as this data is readily available in both palaeo and modern intervals. However, if we had more time, we might want to figure out how to find or calculate the temperature of the coldest quarter, as crocs are constrained physiologically by cooler temperatures. But that's a challenge for another day. Now let's find some data!\n\n### 2. Finding a suitable source of data\n\n#### 2A. Palaeo data\n\nAfter exploring several potential palaeo-climatic datasets, we've decided to use a dataset of global mean surface temperatures for the Phanerozoic (Scotese 2021), based on HadCM3L simulations and aligned with geochemical proxies like ∂18O. The data are available for 5-million-year intervals that cover our time period of interest (Miocene) and have a 1x1 degree (lat/long) resolution. The dataset is also publicly accessible via Zenodo: [https://zenodo.org/records/5718392](https://zenodo.org/records/5718392).\n \nThis climatic dataset offers decently high temporal resolution (for deep time), but one thing we'll need to keep in mind is that the 5-million-year intervals don't align perfectly with geological stages. This will come into play later when we start working with the occurrence data.\n\nFor our study, we'll work with two files from this dataset: one covering 25-20 Ma and another covering 20-15 Ma. These data span warming intervals like the Mid Miocene Climatic Optimum and cooling intervals like the Oligocene-Miocene Climate Transition. \n\n#### 2B. Modern data\n\nWe'll obtain our modern climatic data from WorldClim: [https://www.worldclim.org/](https://www.worldclim.org/). WorldClim is a freely available set of global climate layers with a spatial resolution of about 1 square kilometer, which covers a variety of different climatic options. We can load these data directly into R using the `geodata` package, so no need to download anything for now!\n\nRemember, to keep our climatic variables consistent we'll also be working with mean annual temperature data, but we might have to do some fiddling to set that up (this will make more sense when we see the data!).\n\n### 3. Sort file structure\n\nHere we'd ensure that our downloaded palaeoclimate data are in an appropriate folder for our project. We'll also set some default values to ensure that our spatial datasets conform with one another. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set spatial resolution\nres <- 1\n\n# Set spatial extent\ne <- extent(-180, 180, -90, 90)\n\n# Make generic raster using these values\nref_raster <- raster(res = res, ext = e)\n```\n:::\n\n\n### 4. Load data\n\n#### 4A. Loading palaeo-climatic data\n\nWe now need to load in our data, which is currently stored as a .nc file. This can be read into R as a raster using the `raster` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in rasters of palaeoclimate for each time interval\nraster2prep_15 <- raster(x = \"015_tas_scotese02a_v21321.nc\")\nraster2prep_20 <- raster(x = \"020_tas_scotese02a_v21321.nc\")\n```\n:::\n\n\n#### 4B. Loading modern climatic data\n\nWe can now use the `geodata` package to grab our modern climatic data. Whilst below we show you code to access this data directly within R, it can take a while to download. We've therefore also included it alongside the other materials for the workshop, which can be accessed **[HERE](https://github.com/palaeoverse/2025-CPEG-workshop/tree/main/05_harmonization)**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data from WorldClim and make into raster\nraster2prep_modern <- worldclim_global(var = \"tavg\", res = 10, path = tempdir())\nraster2prep_modern <- as(raster2prep_modern, \"Raster\")\n```\n:::\n\n\n### 5. Check formatting and prepare for analysis\n\n#### 5A. Formatting palaeo-climatic data\n\nFirst, lets have a look at our palaeo climate data and compare it to our reference raster:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Examine our raster layers\nraster2prep_15\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 361, 64980  (nrow, ncol, ncell)\nresolution : 1, 1.005556  (x, y)\nextent     : -180.5, 180.5, -90.5, 90.5  (xmin, xmax, ymin, ymax)\ncrs        : NA \nsource     : 015_tas_scotese02a_v21321.nc \nnames      : X015_tas_scotese02a_v21321 \nzvar       : 015_tas_scotese02a_v21321 \n```\n\n\n:::\n\n```{.r .cell-code}\nraster2prep_20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 361, 64980  (nrow, ncol, ncell)\nresolution : 1, 1.005556  (x, y)\nextent     : -180.5, 180.5, -90.5, 90.5  (xmin, xmax, ymin, ymax)\ncrs        : NA \nsource     : 020_tas_scotese02a_v21321.nc \nnames      : X020_tas_scotese02a_v21321 \nzvar       : 020_tas_scotese02a_v21321 \n```\n\n\n:::\n\n```{.r .cell-code}\nref_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 360, 64800  (nrow, ncol, ncell)\nresolution : 1, 1  (x, y)\nextent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)\ncrs        : +proj=longlat +datum=WGS84 +no_defs \n```\n\n\n:::\n:::\n\nAs you can see, the resolution and extent of these rasters doesn't quite match the reference one that we made above. We'll have to resample our data to match our reference raster:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resample data to match our set extent and resolution\nraster_resampled_15 <- resample(x = raster2prep_15, y = ref_raster)\nraster_resampled_20 <- resample(x = raster2prep_20, y = ref_raster)\n```\n:::\n\n\nFinally, we can stack these rasters into one file, name them, and see what they look like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stack rasters\nscotese_temp <- stack(raster_resampled_15, raster_resampled_20)\n\n# Name and plot rasters\nnames(scotese_temp) <- c(\"Burdigalian\",\"Aquitanian\")\nplot(scotese_temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n#### 5B. Formatting modern data\n\nNow let's have a look at our modern data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Examine our modern raster:\nraster2prep_modern\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterStack \ndimensions : 1080, 2160, 2332800, 12  (nrow, ncol, ncell, nlayers)\nresolution : 0.1666667, 0.1666667  (x, y)\nextent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)\ncrs        : +proj=longlat +datum=WGS84 +no_defs \nnames      : wc2.1_10m_tavg_01, wc2.1_10m_tavg_02, wc2.1_10m_tavg_03, wc2.1_10m_tavg_04, wc2.1_10m_tavg_05, wc2.1_10m_tavg_06, wc2.1_10m_tavg_07, wc2.1_10m_tavg_08, wc2.1_10m_tavg_09, wc2.1_10m_tavg_10, wc2.1_10m_tavg_11, wc2.1_10m_tavg_12 \nmin values :         -45.88400,         -44.80000,         -57.92575,         -64.19250,         -64.81150,         -64.35825,         -68.46075,         -66.52250,         -64.56325,         -55.90000,         -43.43475,         -45.32700 \nmax values :          34.00950,          32.82425,          32.90950,          34.19375,          36.25325,          38.35550,          39.54950,          38.43275,          35.79000,          32.65125,          32.78800,          32.82525 \n```\n\n\n:::\n\n```{.r .cell-code}\nref_raster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 360, 64800  (nrow, ncol, ncell)\nresolution : 1, 1  (x, y)\nextent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)\ncrs        : +proj=longlat +datum=WGS84 +no_defs \n```\n\n\n:::\n:::\n\n\nAs you can see, although the extent matches our reference raster, these modern climatic data are considerably higher resolution than what we have available for our deep time data. But there's something else going on: there's 12 layers within this raster! This is because there's a climatic layer for each month of the year. Therefore, we'll have to calculate the mean temperature before we can use this for comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean annual temperature\nmodern_mean <- calc(x = raster2prep_modern, fun = mean)\n\n# Plot raster\nplot(modern_mean)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n*What issues might this higher resolution cause? What actions could we take to resolve this? What could we test?*\n\n## **BREAKOUT SESSION 2**\n\n**Now it's your turn to give it a go! Let's spend the next 10-15 minutes to work through this same process for our occurrence data:** \n\n***1. First, take a couple minutes to jot down a workflow for the fossil and modern occurrence data. Think about where you might find these data, if you'll need to do any filtering, and how you might format them to enable fair comparisons across time with the climatic data that we just read into R. If you're an experienced R user, you can also start to plan your code.***\n\n***2. Then, get into the same groups you were in previously to discuss your approach. Where you might encounter potential pitfalls? What packages or approaches might make this process easier?*** \n\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\n\nLet's start by thinking about what we need from our occurrence datasets. To answer our question, we aim to compare Crocodylia occurrences in the past and present in relation to temperature data from the same geographic coordinates.\n\nHow do we get there? Let's outline some potential steps:\n\n1.  **Decide which occurrence data to use and where to source it.** The PBDB Crocodylia dataset we've been working with contains occurrences that span our interval of interest. Where might we find a comparable dataset of modern occurrences? Earlier today, we learned about the Global Biodiversity Information Facility (GBIF). This could be a good source!\n\n2.  **Filtering.** We'll need to do some filtering, for example to our time period of interest and to remove occurrences that have high uncertainty or aren't comparable between the datasets. What other filtering criteria might we consider?\n\n3.  **Cleaning.** As we learned in the previous session, we'll also want to spend some time cleaning and exploring our data.\n\n4.  **Merging data.** We'll next want to combine our occurrence and climatic datasets to extract the mean temperature values at the same points in space and time as the occurrences. When doing this, what are some factors we need to consider? This might involving binning our data given differences in temporal and spatial resolutions and making some decisions about which taxonomic level to run our analysis. Along the way, we'll likely need to think carefully about the dataframe structures and identify common data fields that are relevant for our study (time designations, taxonomy, coordinates, collection numbers, etc). We'll also want to consider potential sampling biases that might influence our comparisons.\n\n5. **Data extraction and visualisation.** At this point, we'll have binned fossil and modern occurrences with geographic coordinates and associated temperature data. Returning to our question, this will allow us to determine whether the fossil occurrences cover a broader range of temperatures than the modern occurrences.\n:::\n\nLet's begin!\n\n### 1. Sourcing occurrence data\n\n#### 1A. Organise fossil occurrence data\n\nFirst, we'll load in our palaeontological data. Luckily for us, we've already been working with a Crocodylia fossil occurrence dataset. We'll use these data in our analysis. If you've not quite finished cleaning your dataset, you can find a cleaned version that's ready for this next step **[HERE](https://github.com/palaeoverse/2025-CPEG-workshop/tree/main/05_harmonization)**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load cleaned fossil data for order Crocodylia that we worked on earlier\nfossil_occ <- read.csv(\"cenozoic_crocs_clean.csv\")\n```\n:::\n\n\n#### 1B. Organise modern occurrence data\n\nAfter looking at the number and coverage of available records, we've decided to use the GBIF data.\n\nWe'll start by doing a quick data download using the `rgbif` package for the purposes of this exploratory exercise. Note that this method for retrieving occurrences has some limitations, and we'd want to do a formal download query before running our full analysis for publication. For that, you'd need to make a GBIF account.\n\nHere's how we can do this. Scroll down to load the dataset we've previously downloaded.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set taxa key to order Crocodylia\n#crocodile_key <- name_backbone(name = \"Crocodylia\")$usageKey\n\n# Download data\n#modern_download <- occ_search(\n  #taxonKey = crocodile_key,\n  #hasCoordinate = TRUE, #needs to have coordinates\n  #basisOfRecord = \"PRESERVED_SPECIMEN\", #keeping just preserved specimens for better comparability with the PBDB data\n  #limit = 10000)  #adjust limit (if you set limit to 0, you can check the metadata to see how many records are available)\n\n# Extract data\n#modern_occ <- modern_download$data\n\n# Extract metadata\n#modern_meta <- modern_download$meta\n```\n:::\n\n\nFor ease, here's a csv of the raw data download:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load modern data\nmodern_occ <- read.csv(\"crocs_modern.csv\") \n```\n:::\n\n\n::: {.callout-important}\n\n#### Don't forget!\n\nRemember what we learnt in our session earlier: keep raw data raw! Make sure to always keep a copy of the raw data that you have used for your analyses, be that occurrence data or covariate data (such as climatic data).\n:::\n\n### 2. Filtering\n\nThese datasets contain occurrences that are relevant to our research question, but they also contain occurrences that fall outside of the scope of our planned analysis. Let's filter the datasets to just keep the relevant occurrences. *What were some of the filtering criteria you brainstormed during the breakout session?*\n\n- **Data type:** Note that we've already queried GBIF for just the preserved specimens to optimize comparability with the PBDB dataset. For instance, GBIF also contains fossil specimens, living specimens, and human observations that either aren't entirely comparable with a fossil occurrence or don't represent our modern time interval.\n\n- **Taxonomic:** We'll run our analysis at the order level (Crocodylia) given taxonomic differences between the fossil and modern datasets at finer taxonomic levels (e.g., extinct taxa). That said, let's just retain occurrences that have been identified at least to genus (i.e., removing indet. taxa from the fossil dataset) given uncertainty in their taxonomy.\n\n- **Spatial:** Our research question is posed at a global scale, so we can keep everything. However, we will still want to check for potential geographic outliers or inconsistencies while cleaning the data.\n\n- **Temporal:** We'll constrain our palaeontological dataset to the same time intervals as our climatic dataset (25-15 Ma). Earlier, we downloaded Crocodylia occurrences for the whole of the Cenozoic, so we'll need to do some filtering. Our modern dataset includes occurrences from the 1800s to today, whereas the WorldClim dataset starts at 1970, so we can also filter the occurrence dataset to that time range for consistency.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## PBDB filtering\nfossil_occ_filter <- fossil_occ %>%\n  dplyr::filter(accepted_rank == \"genus\" | accepted_rank ==\"species\") %>% #taxonomic filtering\n  dplyr::filter(max_ma<=25 & min_ma>=15) #temporal filtering\n\n## GBIF filtering\nmodern_occ_filter <- modern_occ %>%\n  dplyr::filter(!is.na(genus)) %>% #taxonomic filtering\n  dplyr::filter(year >= 1970) %>% #temporal filtering\n  dplyr::filter(coordinateUncertaintyInMeters < 10000 | is.na(coordinateUncertaintyInMeters)) #we could also remove data with uncertain geographic coordinates\n```\n:::\n\n\nThis filtering step could have removed a fair amount of data. How many occurrences remain in each filtered dataset?\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(fossil_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 102\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(modern_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2504\n```\n\n\n:::\n:::\n\n\nAfter filtering, we notice that there are far more modern occurrences than fossil occurences to potentially work with. *How might we deal with this unequal sampling?*\n\n\n### 3. Cleaning\n\nWe'll then want to explore and clean our data to check for outliers, inconsistencies, duplicates, and other potential issues.\n\nOur fossil occurrence dataset has already gone through this process.\n\n::: {.callout-note title=\"Practise Time! *(optional)*\"}\n**Let's spend a couple of minutes cleaning and familiarising ourselves with the GBIF data, applying what we learned in the previous session.** For example, you might look at the range of latitudes represented by occurrences or check the taxa for spelling errors. You could plot them on a map to see if you notice any geographic oddities. Or you could check for duplicates. Alternatively, you can check out the [GBIF webpage](https://www.gbif.org/occurrence/search?basis_of_record=PRESERVED_SPECIMEN&taxon_key=11493978&occurrence_status=present) to see what's available.\n:::\n\n\n### 4. Merging\n\nNow we come to the fun part. How do we align these data, which were sampled in different ways with different temporal and spatial resolutions and coverage? Note that the header names differ, and that the datasets contain variables reported in different ways (units, formats) and with different resolutions.\n\n## **BREAKOUT SESSION 3**\n\n**Return to your discussion groups and take 5 minutes to discuss the following questions:**\n\n***1. What factors that might introduce bias when we try to make comparisons across these datasets?***\n\n***2. What are some sources of uncertainty regarding the taxonomic, temporal, and spatial attributes of the data?***\n\n***3. How might we address these potential confounds prior to analysis and/or what should we keep in mind as we're interpreting our results?***\n\nAs you discuss, you may find it helpful to return to your notes from Breakout Session 1.\n\n::: {.callout-tip collapse=\"true\"}\nThe resolution and coverage of the data is likely one aspect that came up in your group discussions, both here and in Breakout Session 1. As we move forward, we'll need to make some practical and philosophical decisions about how we bin the data given their varying resolutions. We'll also want to consider the sensitivity of our results to these various decisions. \n:::\n\nLet's now have a group discussion about these taxonomic, temporal, and spatial considerations when endeavoring to make our datasets comparable.\n\n#### 4A. Taxonomy\n\nWe'll be using higher-level taxonomic groups for our analysis. Let's take a look to see what's here.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fossil occurrences\ntable(fossil_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Alligatoridae        Crocodylidae          Gavialidae NO_FAMILY_SPECIFIED \n                 18                  26                  18                  40 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern occurrences\ntable(modern_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAlligatoridae  Crocodylidae    Gavialidae \n         1933           492            79 \n```\n\n\n:::\n:::\n\n\nWe see that the same families are represented in our datasets (with the fossil occurrence dataset lacking some family-level classifications). If you were to look at the genera, you'll notice some differences. *If we wanted to run an analysis at a finer taxonomic level, what would be some key considerations or steps that we would need to take?*\n\n#### 4B. Temporal Bins\n\nEarlier, we noticed that our climatic data were available at 5-million-year intervals, which don't align perfectly with geological stages. For example, our 25-20 Ma interval crosses the Chattian and Aquitanian stages and the 20-15 Ma interval crosses the Burdigalian and Langhian stages. On the other hand, each fossil occurrence has an associated age and interval range. We want to create time bins that roughly correspond with our climate layer so we can look at occurrences in relation to the temperature reconstructions. *How might we approach this?*\n\nFirst, let's take a look at the temporal distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(x = tax_range_time(occdf = fossil_occ_filter, \n               name = \"occurrence_no\",\n               min_ma = \"min_ma\", \n               max_ma = \"max_ma\", \n               plot = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     taxon taxon_id max_ma min_ma range_myr n_occ\n10  643927        1   16.9  15.98      0.92     1\n16  650903        2   16.9  15.98      0.92     1\n29  742606        3   16.9  15.98      0.92     1\n30  742607        4   16.9  15.98      0.92     1\n31  742608        5   16.9  15.98      0.92     1\n65 1193267        6   16.9  15.98      0.92     1\n```\n\n\n:::\n\n```{.r .cell-code}\naxis_geo(intervals = \"stages\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-49-1.png){width=672}\n:::\n:::\n\n\nOne option would be to bin the data by stage and use those as proxies for our 5-million-year climatic intervals.\nAnother approach might be to make near-equal-length bins within the 25-15 Ma range, and then assign occurrences to those bins. Let's try that latter approach here. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate time bins of ~5 million years within 25 and 15 Ma\nbins <- time_bins(interval = c(15,25), \n                  rank = \"stage\",\n                  size = 5, #here's where we specify the equal-length bins to approximate the resolution of our climatic data\n                  scale = \"GTS2020\",\n                  plot = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nTarget equal length time bins was set to 4.67 Myr. \nGenerated time bins have a mean length of 4.67 Myr and a standard deviation of 2.02 Myr.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Check bins\nhead(bins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bin max_ma mid_ma min_ma duration_myr grouping_rank             intervals\n1   1  27.82 25.425  23.03         4.79         stage              Chattian\n2   2  23.03 21.735  20.44         2.59         stage            Aquitanian\n3   3  20.44 17.130  13.82         6.62         stage Langhian, Burdigalian\n   colour  font\n1 #80cdc1 black\n2 #80cdc1 black\n3 #80cdc1 black\n```\n\n\n:::\n:::\n\n\nThere are also a couple methods that we could use to bin the occurrences. Let's test out two methods here to see how they differ. Hopefully you're starting to get a sense of how these various decisions might propagate to affect our results.\n\n::: {.cell}\n\n```{.r .cell-code}\n# `mid` method = uses the midpoint of age range to bin the occurrence\nfossil_occ_mid <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'mid')\n\n# `majority` method = bins an occurrence into the bin which it most overlaps with\nfossil_occ_maj <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'majority') \n\n# Compare the bin assignments\nbin_comparison <- fossil_occ_mid[c('occurrence_no','bin_assignment','n_bins')] %>% \n  left_join(fossil_occ_maj[c('occurrence_no','bin_assignment','n_bins')],by='occurrence_no') %>% \n  mutate(agreement = case_when(\n    bin_assignment.x == bin_assignment.y ~ \"yes\"\n  ))\n```\n:::\n\n\nIn this case, they actually match up! Since these approaches yielded the same results, we'll use the 'maj' dataset moving forward.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Renaming\nfossil_occ_bin <- fossil_occ_maj\n\n# How many occurrences per bin?\ntable(fossil_occ_bin$bin_assignment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n 2  3 \n 9 93 \n```\n\n\n:::\n:::\n\n\nWe see that most of the data falls into bin 3 (20.44-13.82 Ma, midpoint=17.130 Ma), with some occurrences in bin 2 (23.03-20.44 Ma, midpoint=21.735 Ma). We note that:\n\n-  Bin 2 overlaps with our 25-20 Ma climate raster\n-  Bin 3 overlaps with our 20-15 Ma climate raster\n\nOur GBIF dataset already contains just modern data, which overlaps with our WorldClim climate layer, so no additional binning is needed. \n\nOK, so now we have some temporal bins to facilitate our comparisons with the climatic data.\n\n#### 4C. Spatial Bins\n\nWe also observed that the spatial resolution of the climatic data differed between the past and present. Additionally, the uncertainties in the coordinates for our modern and fossil occurrences differ, especially since we'll need to rely on plate models to palaeorotate the geographic positions of our fossil occurrences. *How might we deal with this?*\n\nLike before, let's take a look at the spatial distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(fossil_occ_bin) +\n  geom_sf(data = world) +\n  geom_point(aes(x = lng, y = lat)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\nBut wait, remember that we need to palaeorotate our coordinates before we proceed! We could run a couple different plate models to check the sensitivity, but for now we'll just use the PALEOMAP rotation, which will also match up to our palaeo-climatic data. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Palaeorotation\nfossil_occ_bin_rot <- palaeorotate(fossil_occ_bin,\n                                   lng = \"lng\",\n                                   lat = \"lat\",\n                                   age = \"bin_midpoint\", \n                                   model  = \"PALEOMAP\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPALEOMAP\n```\n\n\n:::\n:::\n\n\n::: {.callout-note title=\"Heads Up!\"}\nWhilst the `palaeorotate` function is incredibly useful, the GPlates API can sometimes get overloaded with requests. If that happens, we can always use the palaeorotations included within the PBDB download. We'll just have to rename the columns!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rename palaeorotation columns\nrename(fossil_occ_bin_rot, p_lat = paleolat, p_lng = paleolng)\n```\n:::\n\n\n:::\n\nAfter some cleaning, we can then plot our rotated occurrences on a palaeogeographic map (here we're going to use our bin 3):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove NAs\nfossil_occ_bin_rot <- fossil_occ_bin_rot %>%\n  dplyr::filter(!is.na(p_lng) & !is.na(p_lat))\n\n# Use the rgplates package to reconstruct a palaeogeographic map\ncoastlines <- reconstruct(\"coastlines\", age=15, model=\"PALEOMAP\")\n\n# Plot palaeorotated coordinates for bin 3\nfossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 3) %>%\n  ggplot() +\n  geom_sf(data = coastlines) +\n  geom_point(aes(x = p_lng, y = p_lat)) +\n  labs(x = \"palaeolongitude (º)\",\n       y = \"palaeolatitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\nFor comparison, let's also plot the modern occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(modern_occ_filter) +\n  geom_sf(data = world) +\n  geom_point(aes(x = decimalLongitude, y = decimalLatitude)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-57-1.png){width=672}\n:::\n:::\n\n\nLooking at these spatial representations of the data, we can really visualise the difference in sampling effort. *How might we account for the spatial structure of the data in our analysis?*\n\nAnother challenge stems from aligning these occurrences with the spatially explicit climate layers. A simple approach would be to extract the mean temperature value at each coordinate. Alternatively, we might consider adding a bit of a buffer around each coordinate to incorporate geographic uncertainty and variation in the climatic data. A third, albeit more complex approach, would be to assign the occurrences to spatial bins so we can match them up to the climate layers (e.g., check out the `bin_space` function in the `palaeoverse` package). We'd also need to resolve the difference the spatial resolutions between the past and present climatic data, potentially by coarsening the modern dataset. We'll keep things simple and show the first approach here.\n\nNow moving onto the final section: using the combination of these datasets to carry out our analysis and visualise our results!\n\n## IV. Data Extraction and Visualisation\n\nWe're nearly there folks. It's time to put all these data sources together to answer our research question!🥁\n\nWe have our data binned to match the climate layers, so let's create separate datasets for each time bin. \n\n::: {.cell}\n\n```{.r .cell-code}\n# 25-20 Ma climate interval\npoints_20 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 2)\n\n# 20-15 Ma climate interval\npoints_15 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 3) \n\n# Modern interval (whole dataset)\npoints_mod <- modern_occ_filter\n```\n:::\n\n\nNext, let's set up our points and ensure they're on the same coordinate system. Recall that this was one of the things we wanted to check when we outlined our workflow for the climatic data at the beginning of the session.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Turn points into spatial features\npoints_sf_20 <- st_as_sf(x = points_20, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_15 <- st_as_sf(x = points_15, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_mod <- st_as_sf(x = points_mod, coords = c(\"decimalLongitude\", \"decimalLatitude\"))\n\n# Set coordinate system (WGS84) for occurrences\nst_crs(points_sf_20) <- st_crs(4326)\nst_crs(points_sf_15) <- st_crs(4326)\nst_crs(points_sf_mod) <- st_crs(4326)\n```\n:::\n\n\nWe're now ready to extract the climatic data at each coordinate!\n\n::: {.cell}\n\n```{.r .cell-code}\n# Past temperature (Scotese 2022)\nscotese_temp_20 <- raster::extract(x = scotese_temp$Aquitanian, \n                           y = points_sf_20, \n                           sp = TRUE, \n                           cellnumbers = TRUE)\n\nscotese_temp_15 <- raster::extract(x = scotese_temp$Burdigalian, \n                                     y = points_sf_15, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n\n# Modern temperature (WorldClim)\nmodern_temp <- raster::extract(x = modern_mean, \n                                     y = points_sf_mod, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n```\n:::\n\n\nLet's take a look. How does the temperature range inhabited by Crocodylia in deep time compare to that seen in the present?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aquitanian range (25-20 Ma)\nrange(scotese_temp_20$Aquitanian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.43755 26.87847\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_20$Aquitanian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.440919\n```\n\n\n:::\n\n```{.r .cell-code}\n# Burdigalian/Langhian range (20-15 Ma)\nrange(scotese_temp_15$Burdigalian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.28417 33.11024\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_15$Burdigalian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.82607\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern range\nrange(modern_temp@data$layer, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  8.368937 30.550188\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(modern_temp@data$layer, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.18125\n```\n\n\n:::\n:::\n\n\nFinally, let's plot the data.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Organise data for plotting\npalaeo_temp <- rbind(data.frame(Bin = rep(\"Burdigalian\", length(scotese_temp_15$Burdigalian)), #\n                           Temperature = scotese_temp_15$Burdigalian), \n                      data.frame(Bin = rep(\"Aquitanian\", length(scotese_temp_20$Aquitanian)), \n                                  Temperature = scotese_temp_20$Aquitanian),\n                      data.frame(Bin = rep(\"Modern\", length(modern_temp@data$layer)), \n                                  Temperature = modern_temp@data$layer))\n\n# Make box plot of temperature\nggplot(palaeo_temp, aes(x = Bin, y = Temperature)) +\n  geom_jitter(color=\"gray80\",size=2,alpha=0.5)+\n  geom_boxplot(width=0.5,alpha=0.7,outlier.shape = NA)+\n  labs(x=\"Time interval\", y=\"Temperature (ºC)\")+\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-62-1.png){width=672}\n:::\n:::\n\n\nWhen looking at the better sampled intervals in particular, we find that the mean temperature range of Crocodylia occurrences was quite similar between the Miocene and Modern.\n*How might we interpret our results? How might this interpretation be shaped by the caveats we pointed out along the way?*\n\nUltimately, our goal was to provide a workflow for merging different types of datasets and thinking critically about some of the caveats that arise when doing so. These taxonomic, spatial, and temporal considerations are critical to address and report in palaeobiological and palaeoecological research in general---but particularly in studies aiming to cross the palaeontological-ecological gap. We hope you can adapt and learn from this script as you venture forward with your own exciting research questions and datasets!\n\n## References\n\nCramer, K.L., Jackson, J.B., Donovan, M.K., Greenstein, B.J., Korpanty, C.A., Cook, G.M., & Pandolfi, J.M. (2020). Widespread loss of Caribbean acroporid corals was underway before coral bleaching and disease outbreaks. Science Advances, 6(17), eaax9395.\n\nDarroch, S.A., Saupe, E.E., Casey, M.M. and Jorge, M.L. 2022. Integrating geographic ranges across temporal scales. Trends in Ecology & Evolution, 37(10), 851-860.\n\nFlantua, S.G., Mottl, O., Felde, V.A., Bhatta, K.P., Birks, H.H., Grytnes, J.A., ... & Birks, H.J.B. (2023). A guide to the processing and standardization of global palaeoecological data for large‐scale syntheses using fossil pollen. Global Ecology and Biogeography, 32(8), 1377-1394.\n\nJones, L.A., Mannion, P.D., Farnsworth, A., Valdes, P.J., Kelland, S.J. and Allison, P.A. (2019). Coupling of palaeontological and neontological reef coral data improves forecasts of biodiversity responses under global climatic change. Royal Society Open Science, 6(4), 182111.\n\nMottl, O., Flantua, S.G., Bhatta, K.P., Felde, V.A., Giesecke, T., Goring, S., ... & Williams, J. W. (2021). Global acceleration in rates of vegetation change over the past 18,000 years. science, 372(6544), 860-864.\n\nNieto-Lugilde, D., Blois, J.L., Bonet-García, F.J., Giesecke, T., Gil-Romera, G. and Seddon, A. (2021). Time to better integrate palaeoecological research infrastructures with neoecology to improve understanding of biodiversity long-term dynamics and to inform future conservation. Environmental Research Letters, 16(9), 095005.\n\nScotese, C.R., Song, H., Mills, B.J. and van der Meer, D.G. (2021). Phanerozoic palaeotemperatures: The earth’s changing climate during the last 540 million years. Earth-Science Reviews, 215, 103503.\n\nSteinthorsdottir, M., Coxall, H.K., De Boer, A.M., Huber, M., Barbolini, N., Bradshaw, C.D., Burls, N.J., Feakins, S.J., Gasson, E., Henderiks, J. and Holbourn, A.E. (2021). The Miocene: The future of the past. palaeoceanography and palaeoclimatology, 36(4), e2020PA004037.\n\nValdes, P.J., Scotese, C.R. and Lunt, D.J. 2020. Deep ocean temperatures through time. Climate of the Past Discussions (2020). 1-37.\n\nVeloz, S.D., Williams, J.W., Blois, J.L., He, F., Otto‐Bliesner, B. and Liu, Z. (2012). No‐analog climates and shifting realized niches during the late quaternary: implications for 21st‐century predictions by species distribution models. Global Change Biology, 18(5), 1698-1713.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}