project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "R for Palaeobiologists"
  description: "Palaeoverse: Workshop - NAPC 2024"
  site-url: https://workshop.palaeoverse.org
  repo-url: https://github.com/palaeoverse-community/workshop/
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card: true
  image: "/images/twitter-card.png"
  page-footer:
    border: true
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Palaeoverse"
    center: "[Code of Conduct](./conduct.qmd)"
    background: "lightgrey"

  sidebar:
    background: "lightgrey"
    border: true
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/palaeoverse
        text: "GitHub organization"
      - icon: twitter
        href: https://twitter.com/ThePalaeoverse
        text: "Twitter"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: schedule.qmd
        text: Schedule
      - href: team.qmd
        text: Organising Team
      - section: "Workshop Materials"
        contents:
          - href: acquisition.qmd
            text: Data acquisition
          - href: preparation.qmd
            text: Data preparation
          - href: visualisation.qmd
            text: Data visualisation
          - href: resources.qmd
            text: Resources
      - href: conduct.qmd
        text: Code of Conduct

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

editor: visual
