project:
  type: website

website:
  title: "**Palaeoverse Workshops**"
  site-url: https://workshop.palaeoverse.org
  image: "/images/favicon.png"
  favicon: "/images/favicon.png"
  page-navigation: false
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/palaeoverse/workshop
  page-footer:
    background: "#c1e0e2"
    border: true
    left: "&copy; Copyright 2025, Palaeoverse"
    right:
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/palaeoverse.bsky.social
      - text: "{{< iconify fa6-brands:github >}}"
        href: https://github.com/palaeoverse
      - text: "{{< iconify fa6-brands:youtube >}}"
        href: https://www.youtube.com/@ThePalaeoverse
  navbar:
    border: true
    background: "#c1e0e2"
    logo: "images/favicon.png"
    pinned: true
    align: center
    right:
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/palaeoverse.bsky.social
      - text: "{{< iconify fa6-brands:github >}}"
        href: https://github.com/palaeoverse
      - text: "{{< iconify fa6-brands:youtube >}}"
        href: https://www.youtube.com/@ThePalaeoverse
    style: "docked"
    search: true

format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



