---
title: "Welcome"
---

Welcome! This website serves as an index for all workshops organised by [Palaeoverse](https://palaeoverse.org), an organisation aiming to bring the palaeobiological community together to share resources, reach agreed standards, and improve reproducibility in palaeobiological research. Our workshops typically center around Open Science and training in the R programming language. 

## 2025

### Building open data science skills in paleobiology and ecology  
**Organisers:** Erin M. Dillon, Lewis A. Jones, Bethany J. Allen, William Gearty, Christopher D. Dean, Harriet B. Drage, Pedro Godoy  
**Location:** 4^th^ Crossing the Palaeontological-Ecological Gap & 3rd Conservation Paleobiology   
**Date:** 27^th^ July 2025

Website | Archived materials

## 2024  

### R for Paleobiologists: Getting Started with the Palaeoverse R Package  
**Organisers:** Lewis A. Jones, Bethany J. Allen, William Gearty, Erin M. Dillon, Christopher D. Dean  
**Location:** 12^th^ North American Palaeontological Convention, University of Michigan, Michigan, U.S.A  
**Date:** 19^th^ June 2024

[Website](/NAPC2024/index.qmd) | [Archived materials](https://github.com/palaeoverse/2024-NAPC-workshop)

## 2023

### R for Palaeobiologists: Workshop and Hackathon  
**Organisers:** Lewis A. Jones, Bethany J. Allen, Christopher D. Dean, Kilian Eichenseer, Cecily Nicholl, Sofía Galván, and Miranta Kouvari  
**Location:** Department of Earth Sciences, University College London, London, UK  
**Date:** 7--8^th^ September 2023

[Website](/UCL2023/index.qmd) | [Archived materials](https://github.com/palaeoverse/2023-UCL-hackathon)


