{
  "hash": "4acd110de6b8522a2b8f1c7398ec5c65",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data processing II\"\nsubtitle: \"Data processing II: Data harmonization and synthesis\"\ntoc: true\norder: 5\n---\n\n## Learning Objectives\n\nIn this session, we'll walk through how to combine and use different deep-time and modern datasets to answer questions that cross the palaeo-ecological divide. We'll cover:\n\n-  The power of harmonizing data from different sources\n-  The considerations and complications that arise when combining datasets\n-  How to source spatially explicit climatic data for the past and present, and how to look at relationships with fossil and modern occurrences\n-  How to plan, write code for, and carry out projects covering multiple time frames\n\nTo do this, we'll continue working with the Crocodylia dataset. If you've not quite finished cleaning your dataset, you can find a cleaned version that's ready for this next step **HERE**.\n\n## Plan for the Session\n\nThe session will be split into the following sections:\n\nI.   Introduction to harmonization and synthesis\nII.  Planning, setup, and finding your data\nIII. Building a workflow to merge datasets\nIV.  Data visualisation and synthesis\n\n## I. Introduction to Harmonization and Synthesis\n\nPresentation goes here??\n\n## II. Planning, Setup, and Finding Your Data\n\n### Our Research Question\n\nOur first step will be to define our research question, which will be framed around the dataset of Cenozoic Crocodylia that we've been working on this morning. As mentioned previously, Crocs are an excellent group to use for studies comparing modern and deep-time records: they have a very tight association with temperature, are well represented in the fossil record spatially and temporally, and many extant species are threatened by anthropogenic impacts including habitat loss and climate change.\n\nIn this section, we'll aim to answer the following research question: **How does the temperature range inhabited by Crocodylia in deep-time compare to that seen in the present?**\n\nWe'll focus our deep-time analysis on the Miocene, a climatically dynamic epoch in Earth's history that can serve as an analog for future climate scenarios (e.g., [Steinthorsdottir et al. 2020](https://doi.org/10.1029/2020PA004037)).\n\n### Making a Plan\n\nBefore we start, it's helpful to write out a step-by-step plan of what we want to accomplish to ensure that the approach we're taking and the code that we write will appropriately answer the question(s) that we are interested in. Think of this as a kind of \"logical flow.\" In other words, what are all the steps needed to get from our research idea to our finalised analysis? This can be as extensive as you wish and can be done in any fashion---even writing out your code or general approach on pen and paper! We'll be doing this a few times today, so let's start by considering our research question and what materials we will need to address it.\n\nAs we aim to compare the distributions of Crocodylia in deep-time compared to the present, there are a couple of key datasets that we will require:\n\n1.  A spatially explicit dataset of modern Crocodylia\n2.  A spatially explicit dataset of Crocodylia in the deep-time intervals we will assess\n3.  A spatially explicit dataset of modern climatic variables\n4.  A spatially explicit dataset of climatic variables for the deep-time intervals we choose, likely generated from palaeoclimatic modelling\n\n::: {.callout-note title=\"Heads Up!\"}\nEven at this first step, the decisions we make will have consequences for our research and findings. For example, our choice of datasets and how they are handled can impact our results. This will be a recurring theme throughout the session.\n:::\n\n## **BREAKOUT SESSION 1**\n\n**Organize yourselves into groups of 4-6 and discuss the following questions:**\n\n***1. What issues might we encounter when sourcing, gathering, and working with these various climatic and occurrence datasets?***\n\n***2. What caveats should we be aware of, and how can they be addressed?***\n\n## III. Building a Workflow to Merge Datasets\n\nTo help you get an idea for the process of using data from different sources, we'll now walk through an example for how we might acquire and harmonize our climatic data. First, let's make a plan of the steps we'll take and some of the decisions we'll need to consider along the way.\n\n1.  **Decide which climate data to use.** What will be most appropriate for the taxonomic group we are studying? Some potential choices might be:\n\n-   The mean annual temperature\n-   The mean annual range of temperature\n-   The annual standard deviation of temperature\n-   The temperature of the hottest or coldest quarter\n\n2.  **Find a suitable source of data.** We will need to find spatially climatic data for each time interval we are interested in and acquire it in an appropriate format (.nc). What factors might we consider?\n\n-   Availability of specifications listed above\n-   Spatial resolution\n-   Temporal resolution\n\n3.  **Sort file structure.** Ensure that your R project is set up appropriately and that the downloaded files are in an appropriate place to be used in your project, remembering to follow some of the guidance that we've covered earlier on today (e.g. ensuring there are raw versions of your data saved).\n\n4.  **Load data.** Read our data into R in an appropriate format to work with (e.g., raster). How might we do this? What packages might we need?\n\n5.  **Check formatting.** Ensure that the data are formatted appropriately. How might this impact our results or interpretations? What issues should we be aware of?\n\n-   Do the data have the right extent for our research question and R pipeline, and can this be changed?\n-   Are they at an appropriate spatial/temporal resolution, and can this be changed?\n-   Are they in the right Coordinate Reference System?\n-   Are they capturing the same climatic information?\n\n6.  **Prepare for analysis.** Ensure that the data are ready to be used in our next stages of analysis.To do this, we might want to break down our steps further:\n\n-   Check the format of the data using the 'class()' function\n-   Make a reference raster with appropriate resolution and extent\n-   Ensure climate raster doesn't have wrapping/extent issues, and rotate if necessary\n-   Re-sample raster to our reference raster\n-   Ensure that all rasters are capturing the same climatic information\n\nNow that we have a basic plan, we can start to put it into action. Let's write some code!\n\n### 0. Set-up\n\nFirst, we'll need to install and load some packages that will allow us to work with our data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install necessary packages\n#install.packages(\"rgbif\")\n#install.packages(\"tidyverse\")\n#install.packages(\"ggplot2\")\n#install.packages(\"palaeoverse\")\n#install.packages(\"raster\")\n#install.packages(\"sf\")\n#install.packages(\"geodata\")\n#install.packages(\"rnaturalearth\")\n#install.packages(\"ncdf4\")\n#install.packages(\"rgplates\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(rgbif)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(palaeoverse)\nlibrary(raster)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: sp\n\nAttaching package: 'raster'\n\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(geodata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: terra\nterra 1.8.54\n\nAttaching package: 'terra'\n\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rnaturalearth)\nlibrary(ncdf4)\nlibrary(rgplates)\n```\n:::\n\n\nWe'll also set some default values to ensure that our spatial datasets conform with one another. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set spatial resolution\nres <- 1\n\n# Set spatial extent\ne <- extent(-180, 180, -90, 90)\n\n# Make generic raster using these values\nref.raster <- raster(res = res, ext = e)\n```\n:::\n\n\nNow lets find some climate data!\n\n### 1. Organising Palaeo-climatic Data\n\nAfter exploring several potential palaeo-climatic datasets, we've decided to use a dataset of global mean surface temperatures for the Phanerozoic (Scotese 2022), based on HadleyCM3L simulations and aligned with geochemical proxies like ∂18O. The data are available for 5-million-year intervals that cover our time period of interest (Miocene) and have a 1x1 degree (lat/long) resolution. The dataset is also publicly accessible via Zenodo: https://zenodo.org/records/5718392.\n\n  Scotese, C. R., Song, H., Mills, B. J. W., & van der Meer, D. G. (2021). Phanerozoic paleotemperatures: The earth’s changing climate during the last 540 million years. Earth-Science Reviews, 215, 103503. https://doi.org/10.1016/j.earscirev.2021.103503\n  \n  Valdes, P.J., Scotese, C.R., and Lunt, D.J. (2021). Deep Ocean Temperatures through Time, Climates of the Past, Discussions, https://doi.org/10.5194/cp-2020-83. \n\nThis climatic dataset offers decently high temporal resolution (for deep time), but one thing we'll need to keep in mind is that the 5-million-year intervals don't align perfectly with geological stages. This will come into play later when we start working with the occurrence data.\n\nFor our study, we'll work with two files from this dataset: one covering 25-20 Ma and another covering 20-15 Ma. These data span warming intervals like the Mid Miocene Climatic Optimum and cooling intervals like the Oligocene-Miocene Climate Transition. \n\nFirst, we need to load in our data, which is currently stored as a .nc file, and have a look at it. This can be read into R as a raster using the 'raster' package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in rasters of palaeoclimate for each time interval\nraster2prep.15 <- raster(x = \"015_tas_scotese02a_v21321.nc\")\nraster2prep.20 <- raster(x = \"015_tas_scotese02a_v21321.nc\")\n\nraster2prep.15\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 361, 64980  (nrow, ncol, ncell)\nresolution : 1, 1.005556  (x, y)\nextent     : -180.5, 180.5, -90.5, 90.5  (xmin, xmax, ymin, ymax)\ncrs        : NA \nsource     : 015_tas_scotese02a_v21321.nc \nnames      : X015_tas_scotese02a_v21321 \nzvar       : 015_tas_scotese02a_v21321 \n```\n\n\n:::\n\n```{.r .cell-code}\nraster2prep.20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterLayer \ndimensions : 180, 361, 64980  (nrow, ncol, ncell)\nresolution : 1, 1.005556  (x, y)\nextent     : -180.5, 180.5, -90.5, 90.5  (xmin, xmax, ymin, ymax)\ncrs        : NA \nsource     : 015_tas_scotese02a_v21321.nc \nnames      : X015_tas_scotese02a_v21321 \nzvar       : 015_tas_scotese02a_v21321 \n```\n\n\n:::\n:::\n\nAs you can see, the resolution and extent of these rasters doesn't quite match our reference one that we made above. We'll have to resample our data to match our reference raster:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Resample data to match our set extent and resolution\nraster.resampled.15 <- resample(x = raster2prep.15, y = ref.raster)\nraster.resampled.20 <- resample(x = raster2prep.20, y = ref.raster)\n```\n:::\n\n\nFinally, we can stack these rasters into one file, name them, and see what they look like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stack rasters\nscotese.temp <- stack(raster.resampled.15, raster.resampled.20)\n\n# Name and plot rasters\nnames(scotese.temp) <- c(\"Burdigalian\",\"Aquitanian\")\nplot(scotese.temp)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nNow we'll move on to our modern data!\n\n### 2. Organising Modern Climatic Data\n\nWe'll obtain our modern climatic data from WorldClim: \n\nhttps://www.worldclim.org/\n\nTo keep our climatic variables consistent, we'll also work with the mean annual temperature data.\n\nWhilst below we show you code to access this data directly within R, it can take a while to download. We've therefore also included it alongside the other materials for the workshop, which can be accessed HERE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data from WorldClim and make into raster\nmodern <- worldclim_global(var = \"tavg\", res = 10, path = tempdir())\nmodern <- as(modern, \"Raster\")\nmodern\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nclass      : RasterStack \ndimensions : 1080, 2160, 2332800, 12  (nrow, ncol, ncell, nlayers)\nresolution : 0.1666667, 0.1666667  (x, y)\nextent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)\ncrs        : +proj=longlat +datum=WGS84 +no_defs \nnames      : wc2.1_10m_tavg_01, wc2.1_10m_tavg_02, wc2.1_10m_tavg_03, wc2.1_10m_tavg_04, wc2.1_10m_tavg_05, wc2.1_10m_tavg_06, wc2.1_10m_tavg_07, wc2.1_10m_tavg_08, wc2.1_10m_tavg_09, wc2.1_10m_tavg_10, wc2.1_10m_tavg_11, wc2.1_10m_tavg_12 \nmin values :         -45.88400,         -44.80000,         -57.92575,         -64.19250,         -64.81150,         -64.35825,         -68.46075,         -66.52250,         -64.56325,         -55.90000,         -43.43475,         -45.32700 \nmax values :          34.00950,          32.82425,          32.90950,          34.19375,          36.25325,          38.35550,          39.54950,          38.43275,          35.79000,          32.65125,          32.78800,          32.82525 \n```\n\n\n:::\n:::\n\nAs you can see, whilst the extent matches our reference raster, these modern climatic data are considerably higher resolution than what we have available for our deep-time data. They're also provided on a monthly basis, so we'll have to calculate the mean temperature before we can use this for comparison:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean annual temperature\nmodern.mean <- calc(x = modern, fun = mean)\n\n# Plot raster\nplot(modern.mean)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nWhat issues might this higher resolution cause? What actions could we take to resolve this? What could we test?\n\n## **BREAKOUT SESSION 2**\n\n**Now it's your turn to give it a go! Let's go through the same process for our occurrence data:** \n\n***1. First, take a couple minutes to jot down a workflow for the fossil and modern occurrence data. Think about where you might find these data, if you'll need to do any filtering, and how you might get them in the right format such that we can make fair comparisons across time with the climatic data that we just read into R. If you're an experienced R user, you can also start to plan your code.***\n\n***2. Then, get into the same groups you were in previously to discuss your approach. Where you might encounter potential pitfalls? What packages or approaches might make this process easier?*** \n\n\n### Solution\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\n\nLet's start by thinking about what we need from our occurrence datasets. To answer our question, we aim to compare Crocodylia occurrences in the past and present in relation to temperature data from the same geographic coordinates.\n\nHow do we get there? Let's outline some potential steps:\n\n1.  **Decide which occurrence data to use and where to source it.** The PBDB Crocodylia dataset we've been working with contains occurrences that span our interval of interest. Where might we find a comparable dataset of modern occurrences? Earlier today, we learned about the Global Biodiversity Information Facility (GBIF). This could be a good source!\n\n2.  **Filtering.** We'll need to do some filtering, for example to our time period of interest and to remove occurrences that have high uncertainty or aren't comparable between the datasets. What other filtering criteria might we consider?\n\n3.  **Cleaning.** As we learned in the previous session, we'll also want to spend some time cleaning and exploring our data.\n\n4.  **Merging data.** We'll next want to combine our occurrence and climatic datasets to extract the mean temperature values at the same points in space and time as the occurrences. When doing this, what are some factors we need to consider? This might involving binning our data given differences in temporal and spatial resolutions and making some decisions about which taxonomic level to run our analysis. Along the way, we'll likely need to think carefully about the dataframe structures and identify common data fields that are relevant for our study (time designations, taxonomy, coordinates, collection numbers, etc). We'll also want to consider potential sampling biases that might influence our comparisons.\n\n5. **Data extraction and visualisation.** At this point, we'll have binned fossil and modern occurrences with geographic coordinates and associated temperature data. Returning to our question, this will allow us to determine whether the fossil occurrences cover a broader range of temperatures than the modern occurrences.\n:::\n\nLet's begin!\n\n### 1. Sourcing occurrence data\n\n#### 1A. Organise fossil occurrence data\n\nFirst, we'll load in our palaeontological data. Luckily for us, we've already been working with a Crocodylia fossil occurrence dataset. We'll use these data in our analysis. If needed, you can read in the cleaned dataset below.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load cleaned fossil data for order Crocodylia\nfossil_occ <- read.csv(\"crocs_fossil_test.csv\")\n```\n:::\n\n\n#### 1B. Organise modern occurrence data\n\nAfter looking at the number and coverage of available records, we've decided to use the GBIF data.\n\nWe'll start by doing a quick data download using the `rgbif` package for the purposes of this exploratory exercise. Note that this method for retrieving occurrences has some limitations, and we'd want to do a formal download query before running our full analysis for publication. For that, you'd need to make a GBIF account.\n\nHere's how we can do this. Scroll down to load the dataset we've previously downloaded.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set taxa key to order Crocodylia\n#crocodile_key <- name_backbone(name = \"Crocodylia\")$usageKey\n\n# Download data\n#modern_download <- occ_search(\n  #taxonKey = crocodile_key,\n  #hasCoordinate = TRUE, #needs to have coordinates\n  #basisOfRecord = \"PRESERVED_SPECIMEN\", #keeping just preserved specimens for better comparability with the PBDB data\n  #limit = 10000)  #adjust limit (if you set limit to 0, you can check the metadata to see how many records are available)\n\n# Extract data\n#modern_occ <- modern_download$data\n\n# Extract metadata\n#modern_meta <- modern_download$meta\n```\n:::\n\n\nFor ease, here's a csv of the raw data:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load modern data\nmodern_occ <- read.csv(\"crocs_modern.csv\") \n```\n:::\n\n\n\n### 2. Filtering\n\nThese datasets contain occurrences that are relevant to our research question, but they also contain occurrences that fall outside of the scope of our planned analysis. Let's filter the datasets to just keep the relevant occurrences. What were some of the filtering criteria you brainstormed during the breakout session?\n\n**-Data type:** Note that we've already queried GBIF for just the preserved specimens to optimize comparability with the PBDB dataset. For instance, GBIF also contains fossil specimens, living specimens, and human observations that either aren't entirely comparable with a fossil occurrence or don't represent our modern time interval.\n\n**-Taxonomic:** We'll run our analysis at the order level (Crocodylia) given taxonomic differences between the fossil and modern datasets at finer taxonomic levels (e.g., extinct taxa). That said, let's just retain occurrences that have been identified at least to genus (i.e., removing indet. taxa from the fossil dataset) given uncertainty in their taxonomy.\n\n**-Spatial:** Our research question is posed at a global scale, so we can keep everything. However, we will still want to check for potential geographic outliers or inconsistencies while cleaning the data.\n\n**-Temporal:** We'll constrain our palaeontological dataset to the same time intervals as our climatic dataset (25-15 Ma). Earlier, we downloaded Crocodylia occurrences for the whole of the Cenozoic, so we'll need to do some filtering. Our modern dataset includes occurrences from the 1800s to today, whereas the WorldClim dataset starts at 1970, so we can also filter the occurrence dataset to that time range for consistency.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## PBDB filtering\nfossil_occ_filter <- fossil_occ %>%\n  dplyr::filter(accepted_rank == \"genus\" | accepted_rank ==\"species\") %>% #taxonomic filtering\n  dplyr::filter(max_ma<=25 & min_ma>=15) #temporal filtering\n\n## GBIF filtering\nmodern_occ_filter <- modern_occ %>%\n  filter(!is.na(genus)) %>% #taxonomic filtering\n  filter(year >= 1970) %>% #temporal filtering\n  filter(coordinateUncertaintyInMeters < 10000 | is.na(coordinateUncertaintyInMeters)) #we could also remove data with uncertain geographic coordinates\n```\n:::\n\n\nThis filtering step could have removed a fair amount of data. How many occurrences remain in each filtered dataset?\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(fossil_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 114\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(modern_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2504\n```\n\n\n:::\n:::\n\n\nAfter filtering, we have 114 fossil occurrences and 2504 modern occurrences to potentially work with. How might we deal with this unequal sampling?\n\n\n### 3. Cleaning\n\nWe'll then want to explore and clean our data to check for outliers, inconsistencies, duplicates, and other potential issues.\n\nOur fossil occurrence dataset has already gone through this process.\n\n::: {.callout-note title=\"Practise Time!\"}\n**Let's spend a couple of minutes cleaning and familiarising ourselves with the GBIF data, applying what we learned in the previous session.** For example, you might look at the range of latitudes represented by occurrences or check the taxa for spelling errors. You could plot them on a map to see if you notice any geographic oddities. Or you could check for duplicates.\n:::\n\n\n### 4. Merging\n\nNow we come to the fun part. How do we align these data, which were sampled in different ways with different temporal and spatial resolutions and coverage? Note that the header names differ, and that the datasets contain variables reported in different ways (units, formats) and with different resolutions.\n\n## **BREAKOUT SESSION 3**\n\n**Return to your discussion groups and discuss the following questions:**\n\n***1. What factors that might introduce bias when we try to make comparisons across these datasets?***\n\n***2. What are some sources of uncertainty?***\n\n***3. How might we address these potential confounds prior to analysis and/or what should we keep in mind as we're interpreting our results?***\n\n::: {.callout-tip collapse=\"true\"}\nThe resolution and coverage of the data is likely one aspect that came up in your group discussions. As we move forward, we'll need to make some practical and philosophical decisions about how we bin the data given their varying resolutions. We'll also want to consider the sensitivity of our results to these various decisions. \n:::\n\nHere, we'll touch on several key taxonomic, temporal, and spatial considerations when endeavoring to make these datasets comparable.\n\n#### 4A. Taxonomy\n\nWe'll be using higher-level taxonomic groups for our analysis. Let's take a look to see what's here.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fossil occurrences\ntable(fossil_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Alligatoridae        Crocodylidae          Gavialidae NO_FAMILY_SPECIFIED \n                 24                  27                  23                  40 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern occurrences\ntable(modern_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAlligatoridae  Crocodylidae    Gavialidae \n         1933           492            79 \n```\n\n\n:::\n:::\n\n\nWe see that the same families are represented in our datasets. If you were to look at the genera, you'll notice some differences. If we wanted to run an analysis at a finer taxonomic level, what would be some key considerations or steps that we would need to take?\n\n#### 4B. Temporal Bins\n\nEarlier, we noticed that our climatic data were available at 5-million-year intervals, which don't align perfectly with geological stages. For example, our 25-20 Ma interval crosses the Chattian and Aquitanian stages and the 20-15 Ma interval crosses the Burdigalian and Langhian stages. Each fossil occurrence has an associated age and interval range. We want to create time bins that roughly correspond with our climate layer so we can look at occurrences in relation to the temperature reconstructions. How might we approach this?\n\nFirst, let's take a look at the temporal distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(x = tax_range_time(occdf = fossil_occ_filter, \n               name = \"occurrence_no\",\n               min_ma = \"min_ma\", \n               max_ma = \"max_ma\", \n               plot = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     taxon taxon_id max_ma min_ma range_myr n_occ\n10  643927        1   16.9  15.98      0.92     1\n16  650903        2   16.9  15.98      0.92     1\n29  742606        3   16.9  15.98      0.92     1\n30  742607        4   16.9  15.98      0.92     1\n31  742608        5   16.9  15.98      0.92     1\n73 1193267        6   16.9  15.98      0.92     1\n```\n\n\n:::\n\n```{.r .cell-code}\naxis_geo(intervals = \"stages\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nOne option would be to bin the data by stage and use those as proxies for our 5-million-year climatic intervals.\nAnother approach might be to make near-equal-length bins within the 25-15 Ma range, and then assign occurrences to those bins. Let's try that here. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate time bins of ~5 million years within 25 and 15 Ma\nbins <- time_bins(interval = c(15,25), \n                  rank = \"stage\",\n                  size = 5, #here's where we specify the equal-length bins to approximate the resolution of our climatic data\n                  scale = \"GTS2020\",\n                  plot = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nTarget equal length time bins was set to 4.67 Myr. \nGenerated time bins have a mean length of 4.67 Myr and a standard deviation of 2.02 Myr.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Check bins\nhead(bins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bin max_ma mid_ma min_ma duration_myr grouping_rank             intervals\n1   1  27.82 25.425  23.03         4.79         stage              Chattian\n2   2  23.03 21.735  20.44         2.59         stage            Aquitanian\n3   3  20.44 17.130  13.82         6.62         stage Langhian, Burdigalian\n   colour  font\n1 #80cdc1 black\n2 #80cdc1 black\n3 #80cdc1 black\n```\n\n\n:::\n:::\n\n\nAdditionally, there are a couple methods that we could use to bin the occurrences. Let's test out two approaches here to see how they differ. Hopefully you're starting to get a sense of how these various decisions might propagate to affect our results.\n\n::: {.cell}\n\n```{.r .cell-code}\n# `mid` method = uses the midpoint of age range to bin the occurrence\nfossil_occ_mid <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'mid')\n\n# `majority` method = bins an occurrence into the bin which it most overlaps with\nfossil_occ_maj <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'majority') \n\n# Compare the bin assignments\nbin_comparison <- fossil_occ_mid[c('occurrence_no','bin_assignment','n_bins')] %>% \n  left_join(fossil_occ_maj[c('occurrence_no','bin_assignment','n_bins')],by='occurrence_no') %>% \n  mutate(agreement = case_when(\n    bin_assignment.x == bin_assignment.y ~ \"yes\"\n  ))\n```\n:::\n\n\nIn this case, they actually match up! Since these approaches yielded the same results, we'll use the 'maj' dataset moving forward.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Renaming\nfossil_occ_bin <- fossil_occ_maj\n\n# How many occurrences per bin?\ntable(fossil_occ_bin$bin_assignment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  2   3 \n  9 105 \n```\n\n\n:::\n:::\n\n\nWe see that most of the data falls into bin 3 (20.44-13.82 Ma, midpoint=17.130 Ma), with some occurrences in bin 2 (23.03-20.44 Ma, midpoint=21.735 Ma).\n\n-  Bin 2 overlaps with our 25-20 Ma climate raster\n-  Bin 3 overlaps with our 20-15 Ma climate raster\n\nOur GBIF dataset already contains just modern data, which overlaps with our WorldClim climate layer, so no additional binning is needed. \n\nOK, so now we have some temporal bins to facilitate our comparisons with the climatic data.\n\n#### 4C. Spatial Bins\n\nWe also observed that the spatial resolution of the climatic data differed between the past and present. Additionally, the uncertainties in the coordinates for our modern and fossil occurrences differ, especially since we'll need to rely on plate models to palaeorotate the geographic positions of our fossil occurrences. How might we deal with this?\n\nLike before, let's take a look at the spatial distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(fossil_occ_bin) +\n  geom_sf(data = world) +\n  geom_point(aes(x = lng, y = lat)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nBut wait, remember that we need to paleorotate our coordinates before we proceed. We could run a couple different plate models to check the sensitivity, but for now we'll just use the PALEOMAP rotation, which will also match up to our paleoclimatic data. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Palaeorotation\nfossil_occ_bin_rot <- palaeorotate(fossil_occ_bin,\n                                   lng = \"lng\",\n                                   lat = \"lat\",\n                                   age = \"bin_midpoint\", \n                                   model  = \"PALEOMAP\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPALEOMAP\n```\n\n\n:::\n:::\n\n\nAfter some cleaning, we can then plot our rotated occurrences on a palaeogeographic map (here we're going to use our bin 3):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove NAs\nfossil_occ_bin_rot <- fossil_occ_bin_rot %>%\n  dplyr::filter(!is.na(p_lng) & !is.na(p_lat))\n\n# Use the rgplates package to reconstruct a palaeogeographic map\ncoastlines <- reconstruct(\"coastlines\", age=15, model=\"PALEOMAP\")\n\n# Plot palaeorotated coordinates for bin 3\nfossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 3) %>%\n  ggplot() +\n  geom_sf(data = coastlines) +\n  geom_point(aes(x = p_lng, y = p_lat)) +\n  labs(x = \"Paleolongitude (º)\",\n       y = \"Paleolatitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nFor comparison, let's also plot the modern occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(modern_occ_filter) +\n  geom_sf(data = world) +\n  geom_point(aes(x = decimalLongitude, y = decimalLatitude)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nLooking at these spatial representations of the data, we can really visualise the difference in sampling effort. How might we account for the spatial structure of the data in our analysis?\n\nAnother challenge stems from aligning these occurrences with the spatial explicit climate layers. A simple approach would be to extract the mean temperature value at each coordinate. Alternatively, we might consider adding a bit of a buffer around each coordinate to incorporate geographic uncertainty and variation in the climatic data. A third, albeit more complex approach, would be to assign the occurrences to spatial bins so we can match them up to the climate layers (e.g., check out the `bin_space` function). We'd also need to resolve the difference the spatial resolutions between the past and present climatic data, potentially by coarsening the modern dataset.\n\nWe'll keep things simple and show the first approach here.\n\n\n## IV. Data Extraction and Visualisation\n\nWe have our data binned to match the climate layers, so let's create separate datasets for each time bin.\n\n::: {.cell}\n\n```{.r .cell-code}\n# 25-20 Ma climate interval\npoints_20 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 2)\n\n# 20-15 Ma climate interval\npoints_15 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 3) \n\n# Modern interval (whole dataset)\npoints_mod <- modern_occ_filter\n```\n:::\n\n\nNext, let's set up our points and ensure they're on the same coordinate system. Recall that this was one of the things we wanted to check when we outlined our workflow for the climatic data at the beginning of the session.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Turn points into spatial features\npoints_sf_20 <- st_as_sf(x = points_20, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_15 <- st_as_sf(x = points_15, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_mod <- st_as_sf(x = points_mod, coords = c(\"decimalLongitude\", \"decimalLatitude\"))\n\n# Set coordinate system (WGS84) for occurrences\nst_crs(points_sf_20) <- st_crs(4326)\nst_crs(points_sf_15) <- st_crs(4326)\nst_crs(points_sf_mod) <- st_crs(4326)\n```\n:::\n\n\nWe're now ready to extract the climatic data at each coordinate!\n\n::: {.cell}\n\n```{.r .cell-code}\n# Past temperature (Scotese 2022)\nscotese_temp_20 <- raster::extract(x = scotese.temp$Aquitanian, \n                           y = points_sf_20, \n                           sp = TRUE, \n                           cellnumbers = TRUE)\n\nscotese_temp_15 <- raster::extract(x = scotese.temp$Burdigalian, \n                                     y = points_sf_15, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n\n# Modern temperature (WorldClim)\nmodern_temp <- raster::extract(x = modern.mean, \n                                     y = points_sf_mod, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n```\n:::\n\n\nLet's take a look. How does the temperature range inhabited by Crocodylia in deep-time compare to that seen in the present?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aquitanian range (25-20 Ma)\nrange(scotese_temp_20$Aquitanian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17.99979 28.13364\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_20$Aquitanian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.13385\n```\n\n\n:::\n\n```{.r .cell-code}\n# Burdigalian/Langhian range (20-15 Ma)\nrange(scotese_temp_15$Burdigalian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.28417 33.11024\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_15$Burdigalian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.82607\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern range\nrange(modern_temp@data$layer, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  8.368937 30.550188\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(modern_temp@data$layer, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.18125\n```\n\n\n:::\n:::\n\n\nFinally, let's plot the data.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Organise data for plotting\npalaeo_temp <- rbind(data.frame(Bin = rep(\"Burdigalian\", length(scotese_temp_15$Burdigalian)), #\n                           Temperature = scotese_temp_15$Burdigalian), \n                      data.frame(Bin = rep(\"Aquitanian\", length(scotese_temp_20$Aquitanian)), \n                                  Temperature = scotese_temp_20$Aquitanian),\n                      data.frame(Bin = rep(\"Modern\", length(modern_temp@data$layer)), \n                                  Temperature = modern_temp@data$layer))\n\n# Make box plot of temperature\nggplot(palaeo_temp, aes(x = Bin, y = Temperature)) +\n  geom_jitter(color=\"gray80\",size=2,alpha=0.5)+\n  geom_boxplot(width=0.5,alpha=0.7,outlier.shape = NA)+\n  labs(x=\"Time interval\", y=\"Temperature (ºC)\")+\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 3 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nWhen looking at the better sampled intervals in particular, we find that the mean temperature range of Crocodylia occurrences was quite similar between the Miocene and Modern.\nHow might we interpret our results? How might this interpretation be shaped by the caveats we pointed out along the way?\n\nUltimately, our goal was to provide a workflow for merging different types of datasets and thinking critically about some of the caveats that arise when doing so. These taxonomic, spatial, and temporal considerations are critical to address and report in palaeobiological and palaeoecological research in general---but particularly in studies aiming to cross the palaeontological-ecological gap. We hope you can adapt and learn from this script as you venture forward with your own exciting research questions and datasets!",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}