---
title: "Ethical Open Science Practices"
toc: true
order: 6
---

## Learning Objectives

In this last session, we'll be thinking about archiving our data and other materials at the end of a project adhering to ethical open science practices, why we should archive with these principles in mind, and where we might archive materials:

- Get moving and thinking about/discussing open science archiving with others
- Understand why ethical open science is important, and what should be archived
- Have some ideas of where working documents can be archived and openly accessible

**Schedule**

- 15:45--16:45

## Get thinking and discussing!

Now we're back from break, let's get talking about archiving our work. Think about the following questions and discuss your thoughts with your neighbours. Then write your answers, and have a look at what your colleagues think is important in open science and archiving research outputs.

25 minutes, then we'll come back together to go over the important points!

1. Why is open science important?
2. What information is important to archive in a findable, accessible, interoperable, and reproducible way?
3. What are some repositories where you can archive open science data?
4. What are ethical considerations with open science data?

## Archiving & publishing

In the last lecture part for the day, we'll go over some of the key reasons why archiving is important for open science, where you can archive your materials, and some considerations for archiving and publishing:

<object data="./GSAOpenScience.pdf#view=FitH&pagemode=none" width="100%" height="800px" type="application/pdf">
    <embed src="./GSAOpenScience.pdf#view=FitH&pagemode=none" width="100%" height="800px" type="application/pdf" />
</object>

(You can download the slides [here](./GSAOpenScience.pdf).)
