{
  "hash": "1ae3255c11d9aae64b7228b438630948",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data Processing I\"\nsubtitle: \"Data Processing I: Data Exploration and Cleaning\"\ntoc: true\norder: 4\n---\n\n# Learning Objectives\n\nIn this session, the objectives are to (1) understand why data exploration and cleaning is key for data analyses and (2) develop the skills and knowledge needed to explore and clean data. We will cover:\n\n- Exploratory data analyses\n- Identifying and handling incomplete records\n- Identifying and handling outliers\n- Identifying and handling inconsistencies\n- Identifying and handling duplicate records\n\n# Schedule\n\n11:15--12:30\n\n# Data exploration\n\n## Why do we explore our data?\n\nAfter acquiring the raw data to address your research question, a practical next step is to explore your data. Exploratory data analysis involves using graphical tools and basic statistical techniques to better understand the characteristics of your dataset, identify anomalies, and uncover patterns. This step is important for a variety of reasons:\n\n- Reveal the structure and attributes of your dataset, such as variable types and distributions, numbers of observations, and spatial or temporal dependencies between observations.\n- Highlight relationships between variables to guide future analyses and maximise statistical insights.\n- Help you select appropriate statistical tools and verify their assumptions to avoid type I (false positive) and II (false negative) errors that might lead to incorrect conclusions.\n- Flag systematic biases (e.g. taphonomic or sampling biases) that warrant careful consideration when interpreting your results.\n- Reveal missing values, outliers, inconsistencies, duplication, and other unusual or erroneous values that require [cleaning](#data-cleaning).\n\nTogether, exploratory data analysis is used to assess the quality and completeness of your dataset and gauge whether it can provide a meaningful and representative sample to address your research question. Without this step, you run the risk of applying inappropriate statistical techniques or making faulty inferences.\n\n## How do we explore our data?\n\n### Load packages and data\n\nBefore we start, we will load the R packages and data we need:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"dplyr\")\n# install.packages(\"palaeoverse\")\n# install.packages(\"ggplot2\")\n# install.packages(\"rnaturalearth\")\n# install.packages(\"rnaturalearthdata\")\n# install.packages(\"deeptime\")\n# install.packages(\"rgplates\")\n# install.packages(\"fossilbrush\")\nlibrary(dplyr)\nlibrary(palaeoverse)\nlibrary(ggplot2)\nlibrary(rnaturalearth)\nlibrary(rnaturalearthdata)\nlibrary(deeptime)\nlibrary(rgplates)\nlibrary(fossilbrush)\n# Load data\nfossils <- read.csv(\"cenozoic_crocs.csv\")\n```\n:::\n\n\nThe first thing we want to do with our data is generate summary statistics and plots to help us understand the data and its various characteristics.\n\nFor example, we can look at the distribution of identification levels for our fossils.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the frequency of taxonomic ranks\ntable(fossils$accepted_rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        family          genus        species      subfamily       subgenus \n            15            624            850              3              1 \n    subspecies    superfamily unranked clade \n             2             30            718 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Calculate as percentages\n(table(fossils$accepted_rank) / nrow(fossils)) * 100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n        family          genus        species      subfamily       subgenus \n    0.66874721    27.81988408    37.89567543     0.13374944     0.04458315 \n    subspecies    superfamily unranked clade \n    0.08916630     1.33749443    32.01069996 \n```\n\n\n:::\n:::\n\n\nWe can see that of our 2243 occurrences, 850 (~38%) are identified to species level. A further 624 (~28%) are identified to genus level. The remaining fossils are more coarsely identified, including 718 (~32%) which are identified to the mysterious level of \"unranked clade\".\n\nNext, let's look at the distribution of fossils across localities. In the PBDB, fossils are placed within collections, each of which can roughly be considered a separate locality (they can also represent different sampling horizons at the same locality; more on this later). First, we can count the number of unique `collection_no` values to find out how many unique collections are in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# What is the length of a vector of unique collection numbers?\nlength(unique(fossils$collection_no))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1692\n```\n\n\n:::\n:::\n\n\nOur dataset contains 1692 unique collections.\n\nWe can also create a plot showing us the distribution of occurrences across these collections. First let's tally up the number of occurrences in each collection.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of times each collection number appears in the dataset\ncoll_no_freq <- as.data.frame(table(fossils$collection_no))\ncoll_no_freq\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       Var1 Freq\n1      3113    4\n2      5241    1\n3     11601    1\n4     11803    1\n5     12842    1\n6     12847    1\n7     12970    1\n8     13063    1\n9     13065    7\n10    13079    2\n11    13096    1\n12    13127    1\n13    13221    1\n14    13265    1\n15    13293    1\n16    13318    2\n17    13319    1\n18    13322    6\n19    13346    1\n20    13456    1\n21    13626    6\n22    13686    1\n23    13739    1\n24    13747    1\n25    13749    1\n26    13758    1\n27    13782    1\n28    14658    3\n29    14662    1\n30    14670    2\n31    14692    2\n32    14713    1\n33    14729    1\n34    14730    1\n35    14735    1\n36    14736    2\n37    14738    1\n38    14739    2\n39    14748    1\n40    14762    1\n41    14764    1\n42    14766    2\n43    14774    2\n44    14790    2\n45    14805    3\n46    14830    2\n47    14872    1\n48    14873    2\n49    14874    2\n50    14883    1\n51    14928    1\n52    14956    1\n53    14962    1\n54    14963    1\n55    14970    1\n56    14975    1\n57    14992    1\n58    15000    2\n59    15034    1\n60    15049    1\n61    15074    2\n62    15091    1\n63    15098    1\n64    15108    1\n65    15114    1\n66    15119    1\n67    15132    1\n68    15147    1\n69    15152    1\n70    15155    1\n71    15157    1\n72    15159    1\n73    15171    1\n74    15173    2\n75    15174    1\n76    15176    1\n77    15184    1\n78    15190    1\n79    15192    1\n80    15208    2\n81    15211    1\n82    15217    2\n83    15252    1\n84    15454    1\n85    15458    1\n86    15583    1\n87    15586    2\n88    15587    1\n89    15589    1\n90    15590    1\n91    15592    1\n92    15593    1\n93    15594    1\n94    15595    3\n95    15665    2\n96    15668    1\n97    15669    1\n98    15682    1\n99    15683    1\n100   15687    1\n101   15688    1\n102   15692    1\n103   15694    2\n104   15695    1\n105   15696    1\n106   15697    1\n107   15698    1\n108   15699    1\n109   15701    1\n110   15702    1\n111   15703    1\n112   15704    1\n113   15705    1\n114   15706    1\n115   15707    1\n116   15718    1\n117   15759    3\n118   15760    1\n119   15761    1\n120   15771    1\n121   15780    2\n122   15793    1\n123   15830    2\n124   15832    1\n125   15833    1\n126   15837    4\n127   15895    3\n128   15914    1\n129   15917    1\n130   15997    1\n131   16000    1\n132   16134    1\n133   16196    1\n134   16202    1\n135   16228    7\n136   16235    1\n137   16236    1\n138   16244    1\n139   16253    1\n140   16261    1\n141   16262    1\n142   16264    2\n143   16265    1\n144   16266    1\n145   16267    1\n146   16268    2\n147   16270    3\n148   16272    3\n149   16273    3\n150   16274    1\n151   16279    1\n152   16280    1\n153   16282    1\n154   16296    2\n155   16396    2\n156   16405    1\n157   16414    1\n158   16438    1\n159   16528    1\n160   16542    3\n161   16545    1\n162   16549    1\n163   16550    1\n164   16586    1\n165   16590    1\n166   16607    1\n167   16614    1\n168   16623    2\n169   16650    2\n170   16651    1\n171   16656    1\n172   16662    1\n173   16666    1\n174   16669    2\n175   16674    1\n176   16675    1\n177   16676    1\n178   16687    1\n179   16695    1\n180   16712    1\n181   16823    1\n182   16842    1\n183   16877    1\n184   16885    1\n185   16919    1\n186   16938    1\n187   17341    1\n188   17476    1\n189   17837    1\n190   17865    2\n191   17904    1\n192   18004    1\n193   18028    1\n194   18031    1\n195   18046    1\n196   18284    1\n197   18327    1\n198   18357    1\n199   18442    1\n200   18443    1\n201   18537    1\n202   18539    2\n203   18550    1\n204   18554    2\n205   18556    2\n206   18560    2\n207   18561    1\n208   18564    1\n209   18579    1\n210   18586    2\n211   18587    1\n212   18597    1\n213   18601    1\n214   18610    1\n215   18611    1\n216   18613    1\n217   18619    2\n218   18623    1\n219   18626    1\n220   18627    1\n221   18628    1\n222   18630    1\n223   18640    1\n224   18645    1\n225   18646    1\n226   18663    2\n227   18665    1\n228   18759    1\n229   19673    1\n230   19750    1\n231   19753    1\n232   19764    1\n233   20079    1\n234   20302    1\n235   20400    1\n236   20402    1\n237   20440    1\n238   20491    1\n239   20495    1\n240   20530    1\n241   20604    1\n242   20613    1\n243   20650    1\n244   21282    1\n245   21287    1\n246   21294    1\n247   21300    2\n248   21332    2\n249   21334    2\n250   21335    1\n251   21336    3\n252   21337    1\n253   21338    1\n254   21339    1\n255   21340    1\n256   21341    2\n257   21369    3\n258   21377    3\n259   21396    1\n260   21414    3\n261   21442    3\n262   21446    3\n263   21451    3\n264   21453    3\n265   21456    3\n266   21466    3\n267   21490    3\n268   21495    1\n269   21497    3\n270   21499    3\n271   21500    3\n272   21513    3\n273   21522    3\n274   21524    3\n275   21526    3\n276   21531    3\n277   21534    3\n278   21538    3\n279   21626    1\n280   21627    1\n281   21654    1\n282   21688    2\n283   21723    1\n284   21724    1\n285   21835    1\n286   21836    1\n287   21837    1\n288   21839    1\n289   21843    1\n290   21848    1\n291   21855    1\n292   21962    1\n293   21970    1\n294   21973    1\n295   21974    1\n296   22041    1\n297   22064    1\n298   22069    1\n299   22071    1\n300   22077    1\n301   22078    2\n302   22081    1\n303   22082    1\n304   22089    1\n305   22134    1\n306   22138    1\n307   22160    1\n308   22174    1\n309   22178    1\n310   22196    1\n311   22234    2\n312   22235    3\n313   22236    2\n314   22237    2\n315   22238    1\n316   22239    2\n317   22241    5\n318   22242    3\n319   22248    1\n320   22265    1\n321   22268    1\n322   22269    1\n323   22270    1\n324   22271    1\n325   22272    1\n326   22273    1\n327   22275    1\n328   22276    1\n329   22277    1\n330   22278    1\n331   22290    1\n332   22300    1\n333   22301    1\n334   22302    1\n335   22303    1\n336   22307    1\n337   22316    1\n338   22329    1\n339   22336    3\n340   22338    2\n341   22345    2\n342   22346    1\n343   22368    1\n344   22376    2\n345   22377    1\n346   22423    1\n347   22424    1\n348   22444    1\n349   22456    1\n350   22486    1\n351   22487    1\n352   22491    1\n353   22494    1\n354   22495    3\n355   22505    1\n356   22506    2\n357   22548    1\n358   22552    1\n359   22553    1\n360   22554    1\n361   22577    1\n362   22578    1\n363   22579    1\n364   22593    1\n365   22596    2\n366   22614    1\n367   22621    2\n368   22626    2\n369   22628    1\n370   22664    1\n371   22701    3\n372   22924    1\n373   23115    1\n374   24181    3\n375   24237    1\n376   25654    1\n377   26129    2\n378   26550    1\n379   26574    1\n380   27077    1\n381   27268    4\n382   27269    4\n383   27353    1\n384   27508    1\n385   28180    1\n386   28194    1\n387   28230    1\n388   28292    1\n389   28293    1\n390   28368    1\n391   28422    1\n392   28747    2\n393   31108    1\n394   31173    1\n395   31183    1\n396   31316    1\n397   31605    1\n398   31606    1\n399   31717    1\n400   31735    1\n401   31743    1\n402   31748    1\n403   31762    1\n404   32051    2\n405   32052    1\n406   32053    2\n407   32054    1\n408   32055    2\n409   32058    2\n410   32060    1\n411   32079    1\n412   32085    2\n413   32111    1\n414   32116    2\n415   32931    1\n416   32948    1\n417   34269    1\n418   34615    2\n419   34805    1\n420   34845    1\n421   34846    1\n422   34847    1\n423   35132    1\n424   35275    1\n425   35277    3\n426   35279    1\n427   35280    1\n428   35281    2\n429   35531    5\n430   35986    1\n431   36113    1\n432   36114    1\n433   36266    2\n434   36628    1\n435   36631    2\n436   36633    1\n437   36713    1\n438   37239    1\n439   37559    1\n440   37703    2\n441   38060    1\n442   38076    2\n443   38077    1\n444   38172    1\n445   38793    1\n446   38814    1\n447   38817    1\n448   39014    1\n449   39015    1\n450   39209    3\n451   39210    1\n452   39643    2\n453   39662    1\n454   39665    1\n455   39667    1\n456   39892    1\n457   40030    1\n458   40358    1\n459   40516    1\n460   40758    1\n461   40883    1\n462   41073    2\n463   41078    2\n464   41308    1\n465   41735    1\n466   41810    1\n467   41812    1\n468   41813    1\n469   41818    1\n470   41992    1\n471   41998    1\n472   42067    1\n473   42119    1\n474   42130    1\n475   43026    1\n476   43030    1\n477   43063    2\n478   43400    1\n479   44977    1\n480   44999    1\n481   45000    1\n482   45002    3\n483   45097    1\n484   45235    1\n485   45237    2\n486   45239    1\n487   45317    1\n488   45326    1\n489   45327    1\n490   45452    1\n491   45469    1\n492   45485    3\n493   45590    1\n494   45591    1\n495   45594    1\n496   45597    1\n497   45598    1\n498   45640    1\n499   45652    1\n500   45777    1\n501   45801    1\n502   46084    1\n503   46097    1\n504   46197    1\n505   46636    1\n506   46637    1\n507   46639    1\n508   46641    1\n509   46642    1\n510   46644    1\n511   46645    1\n512   46646    1\n513   46649    1\n514   46650    1\n515   46651    1\n516   46652    1\n517   46653    1\n518   46654    1\n519   46659    1\n520   46661    1\n521   46663    1\n522   46672    1\n523   46676    1\n524   46677    1\n525   46678    1\n526   46679    1\n527   46682    1\n528   46683    1\n529   46685    1\n530   46686    1\n531   46687    1\n532   46688    1\n533   46689    1\n534   46690    1\n535   46693    1\n536   46694    1\n537   46697    1\n538   46698    1\n539   46699    1\n540   46700    2\n541   46704    1\n542   46705    1\n543   46707    1\n544   46708    1\n545   46711    1\n546   46720    1\n547   46721    1\n548   46726    1\n549   46727    1\n550   46728    1\n551   46730    1\n552   46731    1\n553   46732    1\n554   46733    1\n555   46734    1\n556   46735    1\n557   46736    1\n558   46738    1\n559   46739    1\n560   46740    1\n561   46743    1\n562   46748    1\n563   46749    1\n564   46753    1\n565   46754    1\n566   46757    1\n567   46758    1\n568   46759    1\n569   46760    1\n570   46761    1\n571   46763    1\n572   46764    1\n573   46766    1\n574   46767    1\n575   46768    1\n576   46769    1\n577   46771    1\n578   46772    1\n579   46773    1\n580   46776    1\n581   46777    1\n582   46778    1\n583   46780    1\n584   46782    1\n585   46783    1\n586   46784    1\n587   46785    1\n588   46786    1\n589   46787    1\n590   46788    1\n591   46789    1\n592   46790    1\n593   46791    1\n594   46792    1\n595   46793    1\n596   46794    1\n597   46795    1\n598   46797    1\n599   46798    1\n600   46800    1\n601   46803    1\n602   46804    1\n603   46807    1\n604   46808    1\n605   46809    1\n606   46810    1\n607   46812    1\n608   46813    1\n609   46814    1\n610   46816    1\n611   46817    1\n612   46819    1\n613   46821    1\n614   46824    1\n615   46825    1\n616   46833    1\n617   46834    1\n618   46835    1\n619   46836    1\n620   46837    1\n621   46840    1\n622   46841    1\n623   46845    1\n624   46846    1\n625   46849    1\n626   46852    1\n627   46955    1\n628   47021    1\n629   47024    1\n630   47026    1\n631   47069    1\n632   47074    1\n633   47086    1\n634   47091    1\n635   47095    1\n636   48029    1\n637   48074    1\n638   48077    2\n639   48159    1\n640   48173    1\n641   48325    1\n642   48638    1\n643   48656    1\n644   48657    1\n645   48667    1\n646   48676    1\n647   48681    2\n648   48696    1\n649   48706    1\n650   48712    1\n651   49078    5\n652   49083    1\n653   49102    1\n654   49403    1\n655   49882    1\n656   49942    1\n657   51104    1\n658   51106    1\n659   51266    2\n660   51412    2\n661   51413    1\n662   51586    1\n663   53001    1\n664   53970    3\n665   55250    1\n666   55396    2\n667   55449    2\n668   55530    1\n669   55600    9\n670   55602   15\n671   56976    1\n672   57007    2\n673   57700    2\n674   57782    1\n675   57989    1\n676   58089    1\n677   58454    2\n678   58455    1\n679   59088    2\n680   59129    1\n681   59839    3\n682   59904    1\n683   59906    1\n684   60443    1\n685   63515    1\n686   63519    1\n687   63520    7\n688   64376    1\n689   64377    1\n690   64378    1\n691   64382    1\n692   65037    1\n693   65140    1\n694   65143    2\n695   65149    1\n696   65161    1\n697   65162    1\n698   65163    1\n699   65170    2\n700   65181    1\n701   65205    1\n702   65367    1\n703   65405    2\n704   65798    1\n705   65912    1\n706   65943    1\n707   65960    3\n708   67172    1\n709   67384    1\n710   67385    4\n711   67386    3\n712   67634    2\n713   67706    1\n714   68032    1\n715   68069    1\n716   68174    4\n717   68428    2\n718   68437    4\n719   68440    3\n720   68795    1\n721   69098    1\n722   69099    1\n723   69539    1\n724   69540    1\n725   69920    1\n726   70118    1\n727   70129    1\n728   70257    1\n729   70266    2\n730   70338    1\n731   70359    1\n732   70360    1\n733   70362    1\n734   70363    1\n735   70364    1\n736   70808    2\n737   70814    1\n738   70827    1\n739   70828    1\n740   70833    1\n741   71275    1\n742   71302    1\n743   71332    1\n744   71651    1\n745   71801    1\n746   71817    1\n747   71819    1\n748   71942    2\n749   72045    1\n750   72184    1\n751   73686    1\n752   73965    1\n753   74097    1\n754   74098    1\n755   74361    1\n756   74470    1\n757   74505    1\n758   74555    1\n759   74556    1\n760   74643    2\n761   74737    1\n762   75078    1\n763   75282    1\n764   75427    1\n765   75638    1\n766   75945    1\n767   75974    1\n768   76029    1\n769   76063    1\n770   76064    1\n771   76066    1\n772   76067    1\n773   76129    1\n774   76844    2\n775   76981    1\n776   77596    1\n777   77776    1\n778   77777    2\n779   77778    1\n780   77779    3\n781   77780    1\n782   77784    1\n783   78233    2\n784   78249    1\n785   78300    1\n786   78518    1\n787   79200    1\n788   79323    1\n789   79700    1\n790   79701    1\n791   79704    1\n792   79757    1\n793   79793    1\n794   81455    1\n795   81498    1\n796   81604    1\n797   83303    1\n798   83304    1\n799   83305    1\n800   83629    1\n801   83938    1\n802   83984    1\n803   84022    1\n804   84045    2\n805   84048    1\n806   84364    1\n807   84511    1\n808   84548    1\n809   84549    1\n810   84606    1\n811   84793    3\n812   85142    1\n813   87489    2\n814   87925    1\n815   87947    1\n816   89015    1\n817   89444    2\n818   90354    2\n819   90576    1\n820   90577    2\n821   91316    1\n822   91467    1\n823   91575    1\n824   92070    4\n825   92641    4\n826   92702    1\n827   92703    2\n828   92732    1\n829   92733    1\n830   92751    1\n831   92839    2\n832   92904    1\n833   93103    1\n834   93265    1\n835   93379    1\n836   93521    2\n837   93522    2\n838   93525    1\n839   93543    1\n840   93546    1\n841   93548    1\n842   93567    1\n843   93587    1\n844   93623    1\n845   93668    1\n846   93670    1\n847   93697    1\n848   93752    1\n849   94595    1\n850   95826    1\n851   95863    1\n852   95914    4\n853   96702    3\n854   96800    1\n855   96899    1\n856   96952    1\n857   97257    1\n858   97550    1\n859   98313    1\n860   99403    1\n861   99707    1\n862   99708    1\n863   99709    1\n864   99711    1\n865   99821    1\n866   99855    1\n867   99856    1\n868  100330    1\n869  105889    3\n870  106003    1\n871  106061    1\n872  107992    5\n873  110177    1\n874  110965    1\n875  112590    1\n876  113118    1\n877  113275    1\n878  113430    1\n879  113685    1\n880  113769    1\n881  113770    1\n882  114013    1\n883  114014    1\n884  114104    1\n885  114105    1\n886  114149    1\n887  114685    1\n888  115113    1\n889  115148    4\n890  115152    2\n891  118015    1\n892  118016    1\n893  118037    1\n894  118038    1\n895  118314    1\n896  118406    2\n897  118482    1\n898  120036    4\n899  120798    1\n900  120885    3\n901  120887    1\n902  122033    2\n903  122454    2\n904  122852    1\n905  123270    1\n906  123296    1\n907  123371    1\n908  123372    1\n909  123373    1\n910  123374    2\n911  123375    1\n912  123376    1\n913  123483    1\n914  123511    1\n915  123512    1\n916  123513    1\n917  123514    1\n918  123515    1\n919  123518    1\n920  123800    1\n921  123919    1\n922  124191    1\n923  124717    1\n924  124905    1\n925  124963    1\n926  124964    1\n927  125091    2\n928  126289    1\n929  126605    1\n930  126866    1\n931  131859    2\n932  132580    2\n933  132938    1\n934  133440    2\n935  133648    1\n936  133692    2\n937  133693    1\n938  133780    1\n939  134806    2\n940  134945    2\n941  134954    1\n942  135038    1\n943  135348    2\n944  135373    1\n945  135688    1\n946  135706    6\n947  135707    1\n948  135911    1\n949  135917    1\n950  136148    1\n951  136269    1\n952  136334    1\n953  136511    2\n954  136521    1\n955  136714    5\n956  136717    8\n957  136720    1\n958  136776    6\n959  136777    6\n960  138404    2\n961  138825    1\n962  140051    1\n963  140202    1\n964  140377    1\n965  141848    1\n966  142030    1\n967  142340    1\n968  142889    1\n969  142891    1\n970  142893    1\n971  143057    2\n972  143060    1\n973  143207    1\n974  143208    1\n975  143209    1\n976  143319    1\n977  143321    3\n978  143324    1\n979  143343    1\n980  143358    1\n981  143359    1\n982  143377    1\n983  143459    1\n984  143461    3\n985  143464    1\n986  143470    3\n987  143472    1\n988  143473    1\n989  143475    1\n990  143476    1\n991  143477    1\n992  143478    1\n993  143479    1\n994  143480    1\n995  143482    1\n996  143483    1\n997  143484    1\n998  143487    1\n999  143488    1\n1000 143490    1\n1001 143515    1\n1002 143516    1\n1003 143517    1\n1004 143518    3\n1005 143524    1\n1006 143531    1\n1007 143552    1\n1008 143586    1\n1009 143603    1\n1010 143727    1\n1011 143748    2\n1012 143754    1\n1013 143780    2\n1014 143781    1\n1015 143782    2\n1016 143783    1\n1017 143784    2\n1018 143786    3\n1019 143788    1\n1020 143792    1\n1021 143795    1\n1022 143796    1\n1023 143884    1\n1024 143885    2\n1025 144046    2\n1026 144047    1\n1027 144065    1\n1028 144099    1\n1029 144102    1\n1030 144103    1\n1031 144104    1\n1032 144105    3\n1033 144106    1\n1034 144107    1\n1035 144108    1\n1036 144109    2\n1037 144110    1\n1038 144111    1\n1039 144113    1\n1040 144115    1\n1041 144116    1\n1042 144117    1\n1043 144118    1\n1044 144119    2\n1045 144124    1\n1046 144125    1\n1047 144127    1\n1048 144130    1\n1049 144131    1\n1050 144132    1\n1051 144133    1\n1052 144134    1\n1053 144135    1\n1054 144173    1\n1055 144174    1\n1056 144175    1\n1057 144176    4\n1058 144177    1\n1059 144178    1\n1060 144179    1\n1061 144180    1\n1062 144181    1\n1063 144182    1\n1064 144183    1\n1065 144184    1\n1066 144185    1\n1067 144187    2\n1068 144195    1\n1069 144196    1\n1070 144200    1\n1071 144202    1\n1072 144203    1\n1073 144260    1\n1074 144261    1\n1075 144262    1\n1076 144263    1\n1077 144444    1\n1078 144474    3\n1079 144511    1\n1080 144512    2\n1081 144514    1\n1082 144516    1\n1083 144517    1\n1084 144536    1\n1085 144537    2\n1086 144538    1\n1087 144540    1\n1088 144541    1\n1089 144542    1\n1090 144543    1\n1091 144544    1\n1092 144545    1\n1093 144546    1\n1094 144547    1\n1095 144548    1\n1096 144549    1\n1097 144550    1\n1098 144552    1\n1099 144553    1\n1100 144554    1\n1101 144555    1\n1102 144556    1\n1103 144557    1\n1104 144558    2\n1105 144559    1\n1106 144560    1\n1107 144562    1\n1108 144563    1\n1109 144564    1\n1110 144565    1\n1111 144566    2\n1112 144584    1\n1113 144585    1\n1114 144586    2\n1115 144588    1\n1116 144593    1\n1117 144595    3\n1118 144596    1\n1119 144638    1\n1120 144643    1\n1121 144645    2\n1122 144646    1\n1123 144649    1\n1124 144662    1\n1125 144663    1\n1126 144739    2\n1127 144788    1\n1128 144977    4\n1129 145618    1\n1130 145619    1\n1131 145620    1\n1132 145621    1\n1133 145622    1\n1134 145811    1\n1135 146600    1\n1136 146988    1\n1137 147191    1\n1138 147461    2\n1139 147462    4\n1140 147463    6\n1141 147464    3\n1142 147465    5\n1143 147466    5\n1144 147467    1\n1145 148381    1\n1146 148384    1\n1147 148387    1\n1148 148388    1\n1149 148390    1\n1150 148393    1\n1151 149168    4\n1152 149173    1\n1153 151620    1\n1154 151737    1\n1155 152082    1\n1156 152113    1\n1157 152870    1\n1158 153738    1\n1159 153741    1\n1160 153743    1\n1161 153745    1\n1162 153746    1\n1163 153747    1\n1164 153748    1\n1165 153749    1\n1166 153750    1\n1167 153751    1\n1168 153752    1\n1169 153753    1\n1170 153754    1\n1171 153756    1\n1172 153757    1\n1173 153758    1\n1174 153759    1\n1175 153760    1\n1176 153761    1\n1177 153763    1\n1178 153775    1\n1179 153776    1\n1180 153777    1\n1181 153779    1\n1182 153818    1\n1183 153820    1\n1184 153821    1\n1185 153822    1\n1186 153823    1\n1187 153824    1\n1188 154035    1\n1189 154221    1\n1190 154222    1\n1191 154724    1\n1192 154804    1\n1193 154805    1\n1194 154921    1\n1195 154960    1\n1196 155253    1\n1197 155752    1\n1198 156789    1\n1199 158991    1\n1200 160726    1\n1201 161374    1\n1202 161377    1\n1203 162464    1\n1204 162465    1\n1205 163851    1\n1206 163852    1\n1207 164388    1\n1208 164395    1\n1209 165176    1\n1210 166506    3\n1211 166507    2\n1212 166508    3\n1213 166598    1\n1214 166767    8\n1215 166768    7\n1216 166769    4\n1217 166770    4\n1218 166975    1\n1219 167230    1\n1220 167354    1\n1221 167729    1\n1222 167953    1\n1223 169420    2\n1224 169436    1\n1225 170185    1\n1226 172914    1\n1227 172927    1\n1228 174065    1\n1229 174066    1\n1230 174226    1\n1231 174672    1\n1232 174673    1\n1233 174730    1\n1234 175334    1\n1235 175727    1\n1236 175734    1\n1237 176127    1\n1238 176128    1\n1239 176129    3\n1240 176130    3\n1241 176132    2\n1242 176133    2\n1243 176135    1\n1244 176140    1\n1245 176143    2\n1246 176145    1\n1247 176147    3\n1248 176148    1\n1249 176149    3\n1250 176156    2\n1251 176162    3\n1252 176208    1\n1253 176226    3\n1254 176664    1\n1255 176750    1\n1256 176824    1\n1257 176825    1\n1258 176826    3\n1259 176827    1\n1260 176828    2\n1261 176829    1\n1262 176868    1\n1263 176936    2\n1264 176937    1\n1265 177036    1\n1266 177494    1\n1267 179000    1\n1268 179001    1\n1269 179481    1\n1270 179692    3\n1271 179707    1\n1272 179708    1\n1273 179709    1\n1274 179710    1\n1275 179732    1\n1276 179811    2\n1277 179812    1\n1278 179933    1\n1279 180111    1\n1280 180192    1\n1281 180576    1\n1282 180578    1\n1283 180579    1\n1284 180580    1\n1285 180582    1\n1286 180583    1\n1287 180591    1\n1288 180592    1\n1289 180594    1\n1290 180599    1\n1291 180603    1\n1292 180611    1\n1293 180613    1\n1294 180614    1\n1295 180616    1\n1296 180617    1\n1297 180624    1\n1298 180626    1\n1299 180629    1\n1300 180630    1\n1301 180691    2\n1302 180692    4\n1303 180791    1\n1304 181304    2\n1305 181308    1\n1306 181309    1\n1307 181310    1\n1308 181515    1\n1309 181845    1\n1310 182159    1\n1311 182505    1\n1312 182519    1\n1313 182565    1\n1314 182619    1\n1315 182641    2\n1316 182667    1\n1317 182671    1\n1318 182805    1\n1319 182916    1\n1320 182999    1\n1321 183008    2\n1322 183009    3\n1323 183010    3\n1324 183080    1\n1325 183151    1\n1326 183364    1\n1327 183674    1\n1328 183918    1\n1329 183976    1\n1330 183979    1\n1331 184227    1\n1332 184275    2\n1333 184468    1\n1334 185323    1\n1335 185615    1\n1336 185616    1\n1337 185681    1\n1338 186359    1\n1339 186362    1\n1340 186558    1\n1341 186636    1\n1342 186845    1\n1343 186852    1\n1344 186888    1\n1345 186894    1\n1346 187320    1\n1347 187324    2\n1348 187580    3\n1349 187583    1\n1350 187585    1\n1351 187873    1\n1352 187874    1\n1353 188304    1\n1354 188748    1\n1355 188761    1\n1356 188992    1\n1357 189440    3\n1358 189577    1\n1359 189788    1\n1360 189790    1\n1361 190038    1\n1362 190041    1\n1363 190086    1\n1364 190120    1\n1365 190535    1\n1366 190744    1\n1367 190965    1\n1368 191113    1\n1369 191222    1\n1370 191365    1\n1371 191932    2\n1372 192070    1\n1373 193126    1\n1374 193640    1\n1375 193641    1\n1376 193642    1\n1377 193643    1\n1378 193644    1\n1379 193645    1\n1380 193648    1\n1381 193650    1\n1382 193652    1\n1383 193654    1\n1384 193655    1\n1385 193656    1\n1386 193657    1\n1387 193659    1\n1388 193662    1\n1389 193664    1\n1390 193667    1\n1391 193670    1\n1392 193988    1\n1393 193989    1\n1394 193990    1\n1395 193998    1\n1396 193999    5\n1397 194000    2\n1398 194001    1\n1399 194002    1\n1400 194073    1\n1401 194574    1\n1402 194579    1\n1403 194580    1\n1404 194726    1\n1405 194846    1\n1406 195083    1\n1407 195288    1\n1408 195449    1\n1409 195457    2\n1410 195517    1\n1411 195859    1\n1412 196739    1\n1413 196740    1\n1414 196742    1\n1415 198248    1\n1416 198251    1\n1417 198638    1\n1418 198647    1\n1419 198648    1\n1420 198649    1\n1421 198650    1\n1422 198651    1\n1423 198652    1\n1424 198653    1\n1425 198654    1\n1426 198655    1\n1427 198656    1\n1428 198657    1\n1429 198658    1\n1430 198659    1\n1431 198660    1\n1432 198661    1\n1433 198662    1\n1434 198812    3\n1435 198813    1\n1436 198814    2\n1437 198815    1\n1438 198816    2\n1439 198892    1\n1440 198893    1\n1441 199213    1\n1442 199559    2\n1443 199560    3\n1444 199562    3\n1445 200044    1\n1446 200110    1\n1447 200111    4\n1448 201834    1\n1449 201840    1\n1450 201849    1\n1451 201850    1\n1452 201975    1\n1453 201976    1\n1454 202068    1\n1455 202336    1\n1456 202337    1\n1457 203089    1\n1458 203090    1\n1459 203092    1\n1460 203093    1\n1461 203112    5\n1462 203629    1\n1463 204596    1\n1464 204645    1\n1465 204646    1\n1466 205187    1\n1467 205815    1\n1468 205883    1\n1469 205884    1\n1470 205897    1\n1471 205898    1\n1472 205912    1\n1473 205916    1\n1474 205919    1\n1475 205920    1\n1476 205927    1\n1477 205929    1\n1478 205943    1\n1479 206017    1\n1480 206042    1\n1481 206081    1\n1482 206083    1\n1483 206184    1\n1484 206185    1\n1485 206532    1\n1486 206776    1\n1487 207049    4\n1488 207452    1\n1489 207484    1\n1490 207489    1\n1491 207493    1\n1492 207764    2\n1493 207765    1\n1494 208786    1\n1495 208787    1\n1496 209089    4\n1497 209370    1\n1498 209371    1\n1499 209873    1\n1500 209877    1\n1501 209878    1\n1502 209898    1\n1503 209904    1\n1504 209906    1\n1505 209913    1\n1506 209918    1\n1507 209922    1\n1508 209923    1\n1509 209932    1\n1510 209936    1\n1511 209938    1\n1512 209941    1\n1513 209947    1\n1514 209948    1\n1515 209965    1\n1516 209971    1\n1517 209975    1\n1518 209976    1\n1519 209979    1\n1520 209981    1\n1521 209987    1\n1522 209988    1\n1523 209990    1\n1524 209992    1\n1525 210009    1\n1526 210023    1\n1527 210027    1\n1528 210032    1\n1529 210038    1\n1530 210039    1\n1531 210043    1\n1532 210044    1\n1533 210045    1\n1534 210193    1\n1535 210194    1\n1536 210195    3\n1537 210197    4\n1538 210198    3\n1539 210199    4\n1540 210951    2\n1541 210952    1\n1542 210953    1\n1543 210954    1\n1544 210955    1\n1545 210956    1\n1546 210957    1\n1547 211299    1\n1548 211306    1\n1549 211787    1\n1550 211915    1\n1551 212251    1\n1552 212253    1\n1553 213137    1\n1554 213296    1\n1555 215569    2\n1556 217014    1\n1557 217616    1\n1558 217618    1\n1559 217775    1\n1560 217776    2\n1561 217781    2\n1562 217782    1\n1563 217788    1\n1564 217817    1\n1565 217818    1\n1566 217824    1\n1567 217876    1\n1568 217877    2\n1569 219022    1\n1570 219023    2\n1571 219024    2\n1572 219025    1\n1573 219026    1\n1574 219027    2\n1575 219762    1\n1576 219885    3\n1577 219967    1\n1578 220175    2\n1579 220590    1\n1580 220617    1\n1581 221108    1\n1582 221117    3\n1583 221118    1\n1584 221119    1\n1585 221120    1\n1586 222064    1\n1587 224007    1\n1588 224009    4\n1589 224010    5\n1590 224012    1\n1591 224013    3\n1592 224112    1\n1593 224113    1\n1594 224114    1\n1595 224115    1\n1596 224116    1\n1597 224117    1\n1598 224118    1\n1599 224119    1\n1600 224120    1\n1601 224121    1\n1602 224122    1\n1603 224123    1\n1604 224124    1\n1605 224125    1\n1606 224126    1\n1607 224127    1\n1608 224128    1\n1609 224129    1\n1610 224130    1\n1611 224131    1\n1612 224132    1\n1613 224301    2\n1614 224304    1\n1615 224305    1\n1616 224306    1\n1617 224308    1\n1618 224309    1\n1619 224310    1\n1620 224311    2\n1621 224312    1\n1622 224313    1\n1623 224326    1\n1624 224327    1\n1625 224328    1\n1626 224332    1\n1627 224333    1\n1628 224418    1\n1629 224505    1\n1630 224506    1\n1631 224507    1\n1632 224509    1\n1633 224510    1\n1634 224511    1\n1635 224594    1\n1636 224597    2\n1637 224598    1\n1638 224654    1\n1639 224655    2\n1640 224657    2\n1641 225490    1\n1642 225491    1\n1643 225492    1\n1644 225493    1\n1645 225494    1\n1646 225495    1\n1647 225589    1\n1648 225590    2\n1649 225891    1\n1650 225946    1\n1651 225947    1\n1652 225948    1\n1653 226046    2\n1654 226065    1\n1655 226738    1\n1656 227021    1\n1657 227328    1\n1658 227368    1\n1659 227371    1\n1660 227934    1\n1661 227935    1\n1662 228148    1\n1663 230003    1\n1664 230004    1\n1665 230115    1\n1666 230116    2\n1667 230675    1\n1668 230753    1\n1669 230754    1\n1670 230759    1\n1671 231878    1\n1672 232040    1\n1673 232370    1\n1674 232486    3\n1675 234561    1\n1676 234666    1\n1677 235737    1\n1678 235747    3\n1679 236300    1\n1680 236310    1\n1681 238106    1\n1682 238108    1\n1683 238109    1\n1684 238110    1\n1685 239734    1\n1686 239764    4\n1687 239770    1\n1688 239799    1\n1689 239809    1\n1690 239845    1\n1691 239955    1\n1692 241377    1\n```\n\n\n:::\n:::\n\n\nNext, we'll use the [ggplot2 package](https://ggplot2.tidyverse.org/), the go-to for professional-looking data visualizations in R, to visualize the frequency of collections with various numbers of occurrences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the distribution of number of occurrences per collection\nggplot(coll_no_freq, aes(x = Freq)) +\n  geom_bar() +\n  labs(x = \"Number of occurrences\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/abundance_distribution_plot-1.png){width=672}\n:::\n:::\n\n\nWe can see that the collection containing the most occurrences has 15, while the vast majority only contain a single occurrence.\n\n\nWhat about the countries in which these fossils were found? We can investigate this using the \"cc\", or \"country code\" column.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List unique country codes, and count them\nunique(fossils$cc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"US\" \"NC\" \"CN\" \"IN\" \"CA\" \"KE\" \"AU\" NA   \"TD\" \"TZ\" \"CD\" \"ET\" \"UG\" \"MW\" \"DJ\"\n[16] \"ZA\" \"PA\" \"FJ\" \"PE\" \"FR\" \"MA\" \"IT\" \"TN\" \"PK\" \"PG\" \"BE\" \"PT\" \"RU\" \"AR\" \"ES\"\n[31] \"UK\" \"IL\" \"DE\" \"IQ\" \"SA\" \"LY\" \"VE\" \"KZ\" \"NP\" \"BR\" \"MG\" \"PR\" \"AT\" \"JM\" \"EG\"\n[46] \"TH\" \"MX\" \"ID\" \"AQ\" \"CH\" \"CR\" \"SV\" \"TW\" \"NE\" \"TR\" \"CZ\" \"MM\" \"DK\" \"SE\" \"UA\"\n[61] \"PL\" \"CO\" \"SK\" \"GT\" \"VU\" \"SC\" \"JP\" \"KY\" \"AE\" \"CU\" \"MT\" \"BS\" \"VN\" \"NZ\" \"OM\"\n[76] \"GR\" \"ER\" \"PY\" \"EH\" \"DO\" \"RO\" \"SD\" \"ML\" \"BA\" \"SN\" \"MN\" \"BG\" \"HU\" \"LK\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(unique(fossils$cc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 89\n```\n\n\n:::\n:::\n\n\nHere we can see that Cenozoic crocodiles have been found in 89 different countries. Let's sort those values alphabetically to help us find specific countries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List and sort unique country codes, and count them\nsort(unique(fossils$cc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"AE\" \"AQ\" \"AR\" \"AT\" \"AU\" \"BA\" \"BE\" \"BG\" \"BR\" \"BS\" \"CA\" \"CD\" \"CH\" \"CN\" \"CO\"\n[16] \"CR\" \"CU\" \"CZ\" \"DE\" \"DJ\" \"DK\" \"DO\" \"EG\" \"EH\" \"ER\" \"ES\" \"ET\" \"FJ\" \"FR\" \"GR\"\n[31] \"GT\" \"HU\" \"ID\" \"IL\" \"IN\" \"IQ\" \"IT\" \"JM\" \"JP\" \"KE\" \"KY\" \"KZ\" \"LK\" \"LY\" \"MA\"\n[46] \"MG\" \"ML\" \"MM\" \"MN\" \"MT\" \"MW\" \"MX\" \"NC\" \"NE\" \"NP\" \"NZ\" \"OM\" \"PA\" \"PE\" \"PG\"\n[61] \"PK\" \"PL\" \"PR\" \"PT\" \"PY\" \"RO\" \"RU\" \"SA\" \"SC\" \"SD\" \"SE\" \"SK\" \"SN\" \"SV\" \"TD\"\n[76] \"TH\" \"TN\" \"TR\" \"TW\" \"TZ\" \"UA\" \"UG\" \"UK\" \"US\" \"VE\" \"VN\" \"VU\" \"ZA\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(sort(unique(fossils$cc)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 88\n```\n\n\n:::\n:::\n\n\nSomething weird has happened here: we can see that once the countries have been sorted, one of them has disappeared. Why? We will come back to this during our [data cleaning](#data-cleaning).\n\n## Practical\n\nNow it's your turn! Explore the data yourself:\n\nWhat is the geographic scale of our data? (hint: geogscale column)\n\n\n::: {.cell}\n\n:::\n\n\nWhat is the stratigraphic scale of our data? (hint: stratscale column)\n\n\n::: {.cell}\n\n:::\n\n\nWhat proportion of our occurrences are marine crocodiles? (hint: taxon_environment column)\n\n\n::: {.cell}\n\n:::\n\n\n# Data cleaning\n\n## Incomplete data records\n\nDatasets are rarely perfect. A common issue you may encounter when exploring your data is ambiguous, incomplete, or missing data entries. These incomplete or missing data records can occur due to various reasons. In some cases, the data truly do not exist or cannot be estimated due to issues relating to taphonomy, collection approaches, or biases in the fossil record. In other cases, discrepancies may arise because data were collected when definitions or contexts differed, such as shifts in geopolitical boundaries and country names over time. Additionally, data may be incomplete for some records, but can be inferred through other available data. \n\n### Why is it important?\n\nMissing information can bias the results of palaeobiological studies. Occurrence data are inherently based on the existence of a particular fossil, but missing data associated with that fossil occurrence can also affect analyses that rely on that associated data. For instance, missing temporal or spatial data may prevent you from including occurrences in your temporal or geographic range analyses.\n\n### What should we do with incomplete data records?\n\nDepending on your research goals, incomplete entries may either be removed through filtering or addressed through imputation techniques. Data imputation approaches can be used to replace missing data with values modelled on the observed data using various methods. These can range from simple approaches, like replacing missing values with the mean for continuous variables, to more advanced statistical or machine learning techniques. If you do decide to impute missing data, it is essential that this process and its effects on the dataset are clearly justified and documented so that future users of the dataset or analytical results are aware of these decisions. Although missing data can reduce the statistical power of analyses and bias the results, imputing missing values can introduce new biases, potentially also skewing results and interpretations of the examined data.\n\nTo decide how to handle missing data, start by identifying the gaps in your dataset, which are often represented by empty entries or ‘NA’. For imputing missing values, numerous methods and tools are available in your coding language of choice, such as missForest, mice, and kNN. Removing missing data can be straightforward when working with small datasets. For manual removal, tools such as spreadsheet software can be sufficient. In R, built-in functions such as `complete.cases()` and `na.omit()` quickly identify and remove missing values (caution: this will remove whole rows of data). The tidyr package also provides the `drop_na()` function for this purpose.\n\n### Identify and handle incomplete data records\n\nBy default, when we read data tables into R, it recognises empty cells and takes some course of action to manage them. When we use base R functions, such as `read.csv()`, empty cells are given an NA value (‘not available’) only when the column is considered to contain numerical data. When we use Tidyverse functions, such as `readr::read_csv()`, all empty cells are given NA values. This is important to bear in mind when we want to find those missing values: here, we have done the latter, so all empty cells are NA.\n\nThe extent of incompleteness of the different columns in our dataset is highly variable. For example, the number of NA values for the collection_no is 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of collection number values for which `is.na()` is TRUE\nsum(is.na(fossils$collection_no))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nThis is because it is impossible to add an occurrence to the PBDB without putting it in a collection, which must in turn have an identification number.\n\nHowever, what about genus?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count the number of genus IDs for which `is.na()` is TRUE\nsum(is.na(fossils$genus))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 766\n```\n\n\n:::\n:::\n\n\nWhat other columns might we want to check?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Latitude\nsum(is.na(fossils$lat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Palaeolatitude\nsum(is.na(fossils$paleolat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 234\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Geological formations\nsum(is.na(fossils$formation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 571\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Country code\nsum(is.na(fossils$cc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5\n```\n\n\n:::\n:::\n\n\nOK, so we've identified some incomplete data records, what do we do now? We have three options:\n\n- Filter (i.e. remove records)\n- Impute (i.e. complete records with substituted values)\n- Complete (i.e. complete records with 'true' values)\n\n#### Filter\n\nWhile all occurrences have present-day coordinates, some are missing palaeocoordinates. We could easily remove these occurrences from the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove occurrences which are missing palaeocoordinates\nfossils <- filter(fossils, !is.na(fossils$paleolat))\n\n# Check whether this has worked\nsum(is.na(fossils$paleolat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\nA further option applicable in some cases would be to fill in our missing data. We may be able to interpolate values from the rest of our data, or use additional data sources. For our palaeogeography example above, we could generate our own palaeocoordinates, for example using `palaeoverse::palaeorotate()`.\n\n#### Impute\n\nData imputation is the process of replacing missing values in a dataset with substituted values. How might we do this for our formation names?\n\n- We could estimate potential formations by using geographic coordinates to extract formations from a geological map.\n- We could evaluate whether any nearby collections of the same age have associated formation names.\n\nHowever, while a useful technique, data imputation does carry a level of uncertainty and can also bias our analyses. In this example, it might be preferable to trace back to the original literature and try to resolve this issue more robustly if the source material allows.\n\n#### Complete\n\nFor example, the formation data for collection 18539 are missing, so we could go back to the original desciptive literature to complete the data for this collection. In doing so, we've discovered that occurrences from collection 18539 are from the Bone Valley Formation. We can now programmatically update our data. We could also do this manually in spreadsheet software, but through coding, we can track and document all the changes we've made to the dataset with ease!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add formation name\nfossils[which(fossils$collection_no == \"18539\"), \"formation\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA NA\n```\n\n\n:::\n\n```{.r .cell-code}\nfossils[which(fossils$collection_no == \"18539\"), \"formation\"] <- \"Bone Valley Formation\"\n\nfossils[which(fossils$collection_no == \"18539\"), \"formation\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Bone Valley Formation\" \"Bone Valley Formation\"\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n\n#### A word of warning\n\nWe identified several data records without country codes. We could quickly filter this data, it's not that much data after all. But you've just remembered something! The country where the collection is located is a compulsory data entry field in the PBDB! **What on Earth has gone wrong?**\n\n:::\n\n::: {.callout-tip collapse=\"true\"}\n\n#### Answer\n\nAny guesses on what the country code for **NA**mibia is?\n\nR has interpreted Namibia's country code as a 'NA' value. \n\nThis is an important illustration of why we should conduct further investigation when any apparent errors arise in the dataset, rather than immediately removing these data points.\n\n:::\n\n## Outlier data records\n\n### Why is it important?\n\nOutliers are data points that significantly deviate from other values in a dataset. Similar to missing information, outliers can bias the results of palaeobiological studies and can occur due to various reasons, including errors in data collection, measurement, processing, or even just natural variations within the data. For instance, when considering the temporal range of a taxonomic group based on occurrence data, an outlier could represent an issue with data entry (e.g. wrong taxonomic name or age entered) or a hiatus in favourable preservation conditions.\n\n### What should we do with outliers?\n\nIdentifying and handling outliers is an important part of data preparation and cleaning, and they typically become apparent when conducting exploratory data analysis. For numerical data, a simple box plot can often be useful for identifying outliers where typically the 'whiskers' are quantified based on some range of values describing the data, and any points lying outside of this range are plotted as individual outliers. In general, when in doubt, visualise and summarise your data.\n\nBut what should we do with outliers once they have been identified? **Depends.**\n\n- How extreme is the outlier? \n- Do we suspect it is an error? Can it be corrected (e.g. going to the source material) or removed? \n- Do we have a good reason for retaining the data record for our analyses? \n- How does it impact our results?\n\n### Identify and handle outliers\n\nTo provide an example on identifying and handling outliers, we we will focus in on the specific variables which relate to our scientific question, i.e. the geography of our fossil occurrences. First we’ll plot where the crocodile fossils have been found across the globe: how does this match what we already know from the country codes?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"medium\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(fossils) +\n  geom_sf(data = world) +\n  geom_point(aes(x = lng, y = lat), \n             shape = 21, size = 0.75, colour = \"black\", fill = \"purple3\") +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nWe have a large density of crocodile occurrences in Europe and the western interior of the United States, along with a smattering of occurrences across the other continents. This distribution seems to fit our previous knowledge, that the occurrences are spread across 89 countries. However, the crocodile occurrences in Antarctica seem particularly suspicious: crocodiles need a warm climate, and modern-day Antarctica certainly doesn’t fit this description. Let’s investigate further. We’ll do this by plotting the latitude of the occurrences through time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add a column to the data frame with the midpoint of the fossil ages\nfossils <- mutate(fossils, mid_ma = (min_ma + max_ma) / 2)\n\n# Create dataset containing only Antarctic fossils\nantarctic <- filter(fossils, cc == \"AQ\")\n\n# Plot the age of each occurrence against its latitude\nggplot(fossils, aes(x = mid_ma, y = lat)) +\n  geom_point(colour = \"black\") +\n  geom_point(data = antarctic, colour = \"red\") +\n  labs(x = \"Age (Ma)\",\n       y = \"Latitude (º)\") +\n  scale_x_reverse() +\n  geom_hline(yintercept = 0) +\n  coord_geo(dat = \"stages\", expand = TRUE, size = \"auto\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nHere we can see the latitude of each occurrence, plotted against the temporal midpoint of the collection. We have highlighted our Antarctic occurrences in red - these points are still looking pretty anomalous.\n\nBut, wait, we should actually be looking at palaeolatitude instead. Let’s plot that against time.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the age of each occurrence against its palaeolatitude\nggplot(fossils, aes(x = mid_ma, y = paleolat)) +\n  geom_point(colour = \"black\") +\n  geom_point(data = antarctic, colour = \"red\") +\n  labs(x = \"Age (Ma)\",\n       y = \"Palaeolatitude (º)\") +\n  scale_x_reverse() +\n  geom_hline(yintercept = 0) +\n  coord_geo(dat = \"stages\", expand = TRUE, size = \"auto\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nHmm… when we look at palaeolatitude the Antarctic occurrences are even further south. Time to really check out these occurrences. Which collections are they within?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find Antarctic collection numbers\nunique(antarctic$collection_no)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  43030 120887  31173\n```\n\n\n:::\n:::\n\n\nWell, upon further visual inspection using the PBDB website, all appear to be fairly legitimate. However, all three occurrences still appear to be outliers, especially as in the late Eocene [temperatures were dropping](https://doi.org/10.1038/s41586-018-0272-2). What about the taxonomic certainty of these occurrences?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# List taxonomic names associated with Antarctic occurrences\nantarctic$identified_name\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Crocodilia indet.\" \"Crocodylia indet.\" \"Crocodylia indet.\"\n```\n\n\n:::\n:::\n\n\nSince all three occurrences are listed as “Crocodylia indet.”, it may make sense to remove them from further analyses anyway.\n\nLet’s investigate if there are any other anomalies or outliers in our data. We’ll bin the occurrences by stage to look for stage-level outliers, using boxplots to show us any anomalous data points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Put occurrences into stage bins\nbins <- time_bins(scale = \"international ages\")\nfossils <- bin_time(occdf = fossils, bins = bins,\n                    min_ma = \"min_ma\", max_ma = \"max_ma\", method = \"majority\")\n\n# Add interval name labels to occurrences\nbins <- select(bins, bin, interval_name)\nfossils <- left_join(fossils, bins, by = c(\"bin_assignment\" = \"bin\"))\n\n# Plot occurrences\nggplot(fossils, aes(x = bin_midpoint, y = paleolat, fill = interval_name)) +\n  geom_boxplot(show.legend = FALSE) +\n  labs(x = \"Age (Ma)\",\n       y = \"Palaeolatitude (º)\") +\n  scale_x_reverse() +\n  scale_fill_geo(\"stages\") +\n  coord_geo(dat = \"stages\", expand = TRUE, size = \"auto\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nBox plots are a great way to look for outliers, because their calculation automatically includes outlier determination, and any such points can clearly be seen in the graph. At time of writing, the guidance for geom_boxplot() states that “The upper whisker extends from the hinge to the largest value no further than 1.5 * IQR from the hinge (where IQR is the inter-quartile range, or distance between the first and third quartiles). The lower whisker extends from the hinge to the smallest value at most 1.5 * IQR of the hinge. Data beyond the end of the whiskers are called ‘outlying’ points and are plotted individually.” 1.5 times the interquartile range seems a reasonable cut-off for determining outliers, so we will use these plots at face value to identify data points to check.\n\nHere, the Ypresian (“Y”) is looking pretty suspicious - it seems to have a lot of outliers. Let’s plot the Ypresian occurrences on a palaeogeographic map to investigate further.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load map of the Ypresian, and identify Ypresian fossils\nfossils_y <- fossils %>%\n  filter(interval_name == \"Ypresian\")\nworld_y <- reconstruct(\"coastlines\", model = \"PALEOMAP\", age = 51.9)\n\n# Plot localities on the Ypresian map\nggplot(fossils_y) +\n  geom_sf(data = world_y) +\n  geom_point(aes(x = paleolng, y = paleolat)) +\n  labs(x = \"Palaeolongitude (º)\",\n       y = \"Palaeolatitude (º)\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nAha! There is a concentrated cluster of occurrences in the western interior of North America. This high number of occurrences is increasing the weight of data at this palaeolatitude, and narrowing the boundaries at which other points are considered outliers. We can check the effect this is having on our outlier identification by removing the US occurrences from the dataset and checking the distribution again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove US fossils from the Ypresian dataset\nfossils_y <- fossils_y %>%\n  filter(cc != \"US\")\n\n# Plot boxplot of non-US Ypresian fossil palaeolatitudes\nggplot(fossils_y) +\n  geom_boxplot(aes(y = paleolat)) +\n  labs(y = \"Palaeolatitude (º)\") +\n  scale_x_continuous(breaks = NULL)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nWe can now see that none of our occurrences are being flagged as outliers. Without this strong geographic bias towards the US, all of the occurrences in the Ypresian appear to be reasonable. This fits our prior knowledge, as [elevated global temperatures during this time](https://doi.org/10.1038/s41586-018-0272-2) likely helped crocodiles to live at higher latitudes than was possible earlier in the Paleogene.\n\nSo to sum up, it seems that our outliers are not concerning, so we will leave them in our dataset and continue with our analytical pipeline.\n\n## Identify and handle inconsistencies\n\nWe’re now going to look for inconsistencies in our dataset. Let’s start by revisiting its structure, focusing on whether the class types of the variables make sense.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check the data class of each field in our dataset\nstr(fossils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t2009 obs. of  142 variables:\n $ occurrence_no        : int  40163 40167 40168 40169 150323 168759 203975 205062 206351 211735 ...\n $ record_type          : chr  \"occ\" \"occ\" \"occ\" \"occ\" ...\n $ reid_no              : int  18506 NA NA NA NA NA 20034 NA 13474 NA ...\n $ flags                : chr  NA NA NA NA ...\n $ collection_no        : int  3113 3113 3113 3113 13346 15458 14764 22924 14830 15895 ...\n $ identified_name      : chr  \"Crocodylia indet.\" \"Thoracosaurus basifissus\" \"Thoracosaurus basitruncatus\" \"Thoracosaurus neocesariensis\" ...\n $ identified_rank      : chr  \"unranked clade\" \"species\" \"species\" \"species\" ...\n $ identified_no        : int  38309 216615 216614 184628 38435 110899 38309 110902 38424 274001 ...\n $ difference           : chr  NA \"species not entered\" \"species not entered\" NA ...\n $ accepted_name        : chr  \"Crocodylia\" \"Gavialoidea\" \"Gavialoidea\" \"Thoracosaurus neocesariensis\" ...\n $ accepted_attr        : logi  NA NA NA NA NA NA ...\n $ accepted_rank        : chr  \"unranked clade\" \"superfamily\" \"superfamily\" \"species\" ...\n $ accepted_no          : int  36582 96627 96627 184627 38435 110899 36582 110902 38424 274001 ...\n $ early_interval       : chr  \"Thanetian\" \"Thanetian\" \"Thanetian\" \"Thanetian\" ...\n $ late_interval        : chr  NA NA NA NA ...\n $ max_ma               : num  59.2 59.2 59.2 59.2 48.1 ...\n $ min_ma               : num  56 56 56 56 41 ...\n $ ref_author           : chr  \"Alroy 2006\" \"Cook and Ramsdell 1991\" \"Cook and Ramsdell 1991\" \"Cook and Ramsdell 1991\" ...\n $ ref_pubyr            : int  2006 1991 1991 1991 1988 2001 2007 1932 1986 1988 ...\n $ reference_no         : int  18120 140 140 140 688 7530 19636 34368 2930 766 ...\n $ phylum               : chr  \"Chordata\" \"Chordata\" \"Chordata\" \"Chordata\" ...\n $ class                : chr  \"Reptilia\" \"Reptilia\" \"Reptilia\" \"Reptilia\" ...\n $ order                : chr  \"Crocodylia\" \"Crocodylia\" \"Crocodylia\" \"Crocodylia\" ...\n $ family               : chr  NA NA NA \"Gavialidae\" ...\n $ genus                : chr  NA NA NA \"Thoracosaurus\" ...\n $ plant_organ          : logi  NA NA NA NA NA NA ...\n $ abund_value          : int  NA NA NA NA 62 NA NA NA NA NA ...\n $ abund_unit           : chr  NA NA NA NA ...\n $ lng                  : num  -74.7 -74.7 -74.7 -74.7 -86.5 ...\n $ lat                  : num  40 40 40 40 31.4 ...\n $ occurrence_comments  : chr  \"originally entered as \\\"Crocodylus? sp.\\\"\" NA NA NA ...\n $ collection_name      : chr  \"Vincentown Formation, NJ\" \"Vincentown Formation, NJ\" \"Vincentown Formation, NJ\" \"Vincentown Formation, NJ\" ...\n $ collection_subset    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ collection_aka       : chr  NA NA NA NA ...\n $ cc                   : chr  \"US\" \"US\" \"US\" \"US\" ...\n $ state                : chr  \"New Jersey\" \"New Jersey\" \"New Jersey\" \"New Jersey\" ...\n $ county               : chr  NA NA NA NA ...\n $ latlng_basis         : chr  \"estimated from map\" \"estimated from map\" \"estimated from map\" \"estimated from map\" ...\n $ latlng_precision     : chr  \"seconds\" \"seconds\" \"seconds\" \"seconds\" ...\n $ altitude_value       : int  NA NA NA NA NA NA NA NA NA NA ...\n $ altitude_unit        : chr  NA NA NA NA ...\n $ geogscale            : chr  \"local area\" \"local area\" \"local area\" \"local area\" ...\n $ geogcomments         : chr  \"\\\"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portion\"| __truncated__ \"\\\"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portion\"| __truncated__ \"\\\"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portion\"| __truncated__ \"\\\"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portion\"| __truncated__ ...\n $ paleomodel           : chr  \"gplates\" \"gplates\" \"gplates\" \"gplates\" ...\n $ geoplate             : chr  \"109\" \"109\" \"109\" \"109\" ...\n $ paleoage             : chr  \"mid\" \"mid\" \"mid\" \"mid\" ...\n $ paleolng             : num  -44.5 -44.5 -44.5 -44.5 -66.8 ...\n $ paleolat             : num  40.1 40.1 40.1 40.1 34.7 ...\n $ protected            : chr  NA NA NA NA ...\n $ direct_ma_value      : num  NA NA NA NA NA NA NA NA NA NA ...\n $ direct_ma_error      : num  NA NA NA NA NA NA NA NA NA NA ...\n $ direct_ma_unit       : chr  NA NA NA NA ...\n $ direct_ma_method     : chr  NA NA NA NA ...\n $ max_ma_value         : num  NA NA NA NA NA NA NA NA NA NA ...\n $ max_ma_error         : num  NA NA NA NA NA NA NA NA NA NA ...\n $ max_ma_unit          : chr  NA NA NA NA ...\n $ max_ma_method        : chr  NA NA NA NA ...\n $ min_ma_value         : num  NA NA NA NA NA NA NA NA NA NA ...\n $ min_ma_error         : num  NA NA NA NA NA NA NA NA NA NA ...\n $ min_ma_unit          : chr  NA NA NA NA ...\n $ min_ma_method        : chr  NA NA NA NA ...\n $ formation            : chr  \"Vincentown\" \"Vincentown\" \"Vincentown\" \"Vincentown\" ...\n $ geological_group     : chr  NA NA NA NA ...\n $ member               : chr  NA NA NA NA ...\n $ stratscale           : chr  \"formation\" \"formation\" \"formation\" \"formation\" ...\n $ zone                 : chr  NA NA NA NA ...\n $ zone_type            : chr  NA NA NA NA ...\n $ localsection         : chr  \"New Jersey\" \"New Jersey\" \"New Jersey\" \"New Jersey\" ...\n $ localbed             : chr  NA NA NA NA ...\n $ localbedunit         : chr  NA NA NA NA ...\n $ localorder           : chr  NA NA NA NA ...\n $ regionalsection      : chr  NA NA NA NA ...\n $ regionalbed          : chr  NA NA NA NA ...\n $ regionalbedunit      : chr  NA NA NA NA ...\n $ regionalorder        : chr  NA NA NA NA ...\n $ stratcomments        : chr  NA NA NA NA ...\n $ lithdescript         : chr  NA NA NA NA ...\n $ lithology1           : chr  \"sandstone\" \"sandstone\" \"sandstone\" \"sandstone\" ...\n $ lithadj1             : chr  \"glauconitic\" \"glauconitic\" \"glauconitic\" \"glauconitic\" ...\n $ lithification1       : chr  NA NA NA NA ...\n $ minor_lithology1     : chr  \"sandy,calcareous\" \"sandy,calcareous\" \"sandy,calcareous\" \"sandy,calcareous\" ...\n $ fossilsfrom1         : chr  NA NA NA NA ...\n $ lithology2           : chr  NA NA NA NA ...\n $ lithadj2             : chr  NA NA NA NA ...\n $ lithification2       : chr  NA NA NA NA ...\n $ minor_lithology2     : chr  NA NA NA NA ...\n $ fossilsfrom2         : chr  NA NA NA NA ...\n $ environment          : chr  NA NA NA NA ...\n $ tectonic_setting     : chr  NA NA NA NA ...\n $ geology_comments     : chr  \"lithology described as a calcareous \\\"lime sand\\\" interbedded with a quartz or \\\"yellow sand\\\"\" \"lithology described as a calcareous \\\"lime sand\\\" interbedded with a quartz or \\\"yellow sand\\\"\" \"lithology described as a calcareous \\\"lime sand\\\" interbedded with a quartz or \\\"yellow sand\\\"\" \"lithology described as a calcareous \\\"lime sand\\\" interbedded with a quartz or \\\"yellow sand\\\"\" ...\n $ size_classes         : chr  NA NA NA NA ...\n $ articulated_parts    : chr  NA NA NA NA ...\n $ associated_parts     : chr  NA NA NA NA ...\n $ common_body_parts    : chr  NA NA NA NA ...\n $ rare_body_parts      : chr  NA NA NA NA ...\n $ feed_pred_traces     : chr  NA NA NA NA ...\n $ artifacts            : chr  NA NA NA NA ...\n $ component_comments   : chr  NA NA NA NA ...\n $ pres_mode            : chr  NA NA NA NA ...\n  [list output truncated]\n```\n\n\n:::\n:::\n\nThis looks reasonable. For example, we can see that our collection IDs are `numerical`, and our `identified_name` column contains `character` strings.\n\nNow let’s dive in further to look for inconsistencies in spelling, which could cause taxonomic names or geological units to be grouped separately when they are really the same thing. We’ll start by checking for potential taxonomic misspellings.\n\nWe can use the table() function to look at the frequencies of various taxonomic names in the dataset. Here, inconsistencies like misspellings or antiquated taxonomic names might be recognised. We will check the columns `family`, `genus`, and `accepted_name`, the latter of which gives the name of the identification regardless of taxonomic level, and is the only column to give species binomials.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Tabulate the frequency of values in the \"family\" and \"genus\" columns\ntable(fossils$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Alligatoridae        Crocodylidae          Gavialidae NO_FAMILY_SPECIFIED \n                466                 422                 210                 357 \n     Planocraniidae \n                 24 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(fossils$genus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                Acresuchus               Ahdeskatanka \n                         7                          1 \n             Akanthosuchus              Aktiogavialis \n                         3                          3 \n                 Alligator           Allognathosuchus \n                        74                        128 \n            Antecrocodylus                Argochampsa \n                         2                          4 \n              Asiatosuchus                  Asifcroco \n                        32                          1 \n             Astorgosuchus             Australosuchus \n                         2                          4 \n                      Baru              Borealosuchus \n                        14                         48 \n               Bottosaurus               Boverisuchus \n                         5                         21 \n             Brachychampsa         Brachygnathosuchus \n                         1                          1 \n        Brachyuranochampsa              Brasilosuchus \n                         1                          1 \n                Brochuchus                     Caiman \n                         8                         31 \n              Ceratosuchus             Charactosuchus \n                         5                          7 \n           Chinatichampsus              Chrysochampsa \n                         1                          1 \n                Crocodylus Crocodylus (Leptorhynchus) \n                       270                          1 \n                Dinosuchus               Diplocynodon \n                         1                        127 \n            Dollosuchoides             Dongnanosuchus \n                         1                          1 \n               Duerosuchus             Dzungarisuchus \n                         1                          1 \n               Eoalligator                   Eocaiman \n                         3                          7 \n                Eogavialis                   Eosuchus \n                         4                          6 \n                Euthecodon                   Gavialis \n                        57                         40 \n             Gavialosuchus           Globidentosuchus \n                         9                          9 \n               Gnatusuchus                Gryposuchus \n                         6                         31 \n             Gunggamarandu             Harpacochampsa \n                         1                          1 \n            Hassiacosuchus            Hesperogavialis \n                         2                          6 \n             Ikanogavialis                Kalthifrons \n                         5                          1 \n                   Kambara                Kentisuchus \n                         4                          3 \n                   Kinyang                Krabisuchus \n                         5                          3 \n             Kuttanacaiman               Leidyosuchus \n                         3                          1 \n             Leptorramphus              Lianghusuchus \n                         1                          2 \n        Listrognathosuchus             Maomingosuchus \n                         1                          4 \n             Maroccosuchus                  Mecistops \n                         3                         11 \n           Megadontosuchus                 Mekosuchus \n                         1                          5 \n              Melanosuchus             Menatalligator \n                         4                          1 \n               Mourasuchus               Navajosuchus \n                        38                          2 \n               Necrosuchus                Nihilichnus \n                         1                          1 \n           Orientalosuchus            Orthogenysuchus \n                         1                          1 \n               Osteolaemus                Paleosuchus \n                         4                          3 \n                 Paludirex               Paranacaiman \n                         7                          1 \n              Paranasuchus              Paratomistoma \n                         2                          1 \n              Penghusuchus              Piscogavialis \n                         1                          8 \n               Planocrania             Procaimanoidea \n                         2                          5 \n            Protoalligator                Protocaiman \n                         1                          1 \n               Purussaurus            Qianshanosuchus \n                        60                          1 \n                  Quinkana           Rhamphostomopsis \n                         8                          4 \n             Rhamphosuchus                 Rimasuchus \n                         3                          8 \n              Sacacosuchus               Sakhibaghoon \n                         8                          1 \n          Siquisiquesuchus               Sutekhsuchus \n                         6                          5 \n              Thecachampsa              Thoracosaurus \n                        38                         11 \n               Tienosuchus                  Tomistoma \n                         1                         26 \n           Toyotamaphimeia             Trilophosuchus \n                         3                          2 \n                 Tsoabichi              Tzaganosuchus \n                         2                          1 \n               Ultrastenos            Wannaganosuchus \n                         1                          1 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter occurrences to those identified at species level, then tabulate species\n# names\nfossils_sp <- filter(fossils, accepted_rank == \"species\")\ntable(fossils_sp$accepted_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Acresuchus pachytemporalis    Ahdeskatanka russlanddeutsche \n                               7                                1 \n         Akanthosuchus langstoni           Aktiogavialis caribesi \n                               3                                1 \n    Aktiogavialis puertoricensis                Alligator darwini \n                               2                                7 \n               Alligator gaudryi              Alligator hailensis \n                               1                                2 \n          Alligator hantoniensis                 Alligator luicus \n                               2                                1 \n               Alligator mcgrewi               Alligator mefferdi \n                               1                                2 \n      Alligator mississippiensis               Alligator munensis \n                              12                                1 \n                Alligator olseni             Alligator prenasalis \n                               4                                8 \n              Alligator sinensis               Alligator thomsoni \n                               2                                1 \n      Allognathosuchus heterodon      Allognathosuchus mlynarskii \n                               2                                1 \n       Allognathosuchus polyodon        Allognathosuchus wartheni \n                               2                                4 \n       Allognathosuchus woutersi   Antecrocodylus chiangmuanensis \n                               1                                2 \n              Argochampsa krebsi       Asiatosuchus depressifrons \n                               4                               11 \n         Asiatosuchus germanicus            Asiatosuchus grangeri \n                               3                                1 \n       Asiatosuchus nanlingensis        Asiatosuchus oenotriensis \n                               4                                1 \n                Asifcroco retrai         Astorgosuchus bugtiensis \n                               1                                2 \n          Australosuchus clarkae                     Baru darrowi \n                               4                                4 \n                     Baru huberi                  Baru iylwenpeny \n                               1                                2 \n                    Baru wickeni      Borealosuchus acutidentatus \n                               7                                1 \n      Borealosuchus formidabilis          Borealosuchus griffithi \n                              17                                2 \n       Borealosuchus sternbergii            Borealosuchus wilsoni \n                              12                                2 \n           Bottosaurus fustidens          Boverisuchus magnifrons \n                               2                                2 \n              Boverisuchus vorax     Brachyuranochampsa eversolei \n                              17                                1 \n           Brasilosuchus mendesi             Brochuchus parvidens \n                               1                                1 \n              Brochuchus pigotti                 Caiman australis \n                               4                                2 \n             Caiman brevirostris                Caiman crocodilus \n                               3                                2 \n              Caiman latirostris                Caiman paranensis \n                               5                                1 \n               Caiman praecursor             Caiman wannlangstoni \n                               1                                4 \n                   Caiman yacare            Ceratosuchus burdoshi \n                               3                                4 \n          Charactosuchus fieldsi           Charactosuchus sansoai \n                               3                                1 \n      Chinatichampsus wilsonorum              Crocodilus antiquus \n                               1                                1 \n              Crocodilus ebertsi              Crocodilus ziphodon \n                               1                                2 \n                 Crocodylus acer                Crocodylus acutus \n                               1                                1 \n              Crocodylus affinis        Crocodylus anthropophagus \n                              23                                6 \n                Crocodylus aptus             Crocodylus checchiai \n                               2                                5 \n             Crocodylus elliotti           Crocodylus falconensis \n                               1                                1 \n          Crocodylus gariepensis            Crocodylus megarhinus \n                               1                                3 \n            Crocodylus niloticus          Crocodylus palaeindicus \n                              38                                5 \n            Crocodylus palustris               Crocodylus porosus \n                               5                                5 \n            Crocodylus rhombifer             Crocodylus siamensis \n                               5                               10 \n      Crocodylus thorbjarnarsoni       Diplocynodon buetikonensis \n                               7                                1 \n            Diplocynodon darwini            Diplocynodon deponiae \n                               1                                3 \n         Diplocynodon elavericus        Diplocynodon hantoniensis \n                               1                                1 \n              Diplocynodon kochi        Diplocynodon levantinicum \n                               4                                2 \n           Diplocynodon muelleri           Diplocynodon plenidens \n                               6                                2 \n            Diplocynodon ratelii            Diplocynodon remensis \n                               8                                2 \n             Diplocynodon tormis              Diplocynodon ungeri \n                               4                               16 \n        Dollosuchoides densmorei              Dongnanosuchus hsui \n                               1                                1 \n            Duerosuchus piscator        Dzungarisuchus manacensis \n                               1                                1 \n             Eoalligator chunyii             Eocaiman cavernensis \n                               3                                1 \n          Eocaiman itaboraiensis           Eocaiman palaeocenicus \n                               1                                3 \n            Eogavialis africanum              Eogavialis andrewsi \n                               1                                2 \n          Eogavialis gavialoides                Eosuchus lerichei \n                               1                                1 \n                  Eosuchus minor           Euthecodon arambourgii \n                               5                                1 \n              Euthecodon brumpti               Euthecodon nitriae \n                              33                                3 \n           Gavialis bengawanicus                  Gavialis browni \n                               7                                5 \n             Gavialis gangeticus                  Gavialis lewisi \n                              10                                3 \n          Gavialosuchus antiquus     Gavialosuchus eggenburgensis \n                               1                                1 \n  Globidentosuchus brachyrostris           Gnatusuchus pebasensis \n                               9                                6 \n         Gryposuchus colombianus             Gryposuchus croizati \n                               8                                5 \n              Gryposuchus jessei             Gryposuchus neogaeus \n                               4                                1 \n          Gryposuchus pachakamue            Gunggamarandu maunala \n                               7                                1 \n    Harpacochampsa camfieldensis            Hassiacosuchus haupti \n                               1                                1 \n        Hesperogavialis cruxenti            Ikanogavialis gameroi \n                               3                                3 \n       Kalthifrons aurivellensis              Kambara implexidens \n                               1                                1 \n                 Kambara molnari              Kambara murgonensis \n                               1                                1 \n                 Kambara taraina               Kentisuchus astrei \n                               1                                1 \n            Kentisuchus spenceri              Kinyang mabokoensis \n                               2                                1 \n               Kinyang tchernovi        Krabisuchus siamogallicus \n                               2                                3 \n      Kuttanacaiman iquitosensis       Leptorramphus entrerrianus \n                               3                                1 \n     Lianghusuchus hengyangensis Listrognathosuchus multidentatus \n                               1                                1 \n     Maomingosuchus acutirostris         Maomingosuchus petrolica \n                               1                                2 \n          Maroccosuchus zennaroi           Mecistops cataphractus \n                               3                                2 \n           Mecistops nkondoensis          Megadontosuchus arduini \n                               6                                1 \n              Mekosuchus sanderi      Mekosuchus whitehunterensis \n                               1                                4 \n            Melanosuchus fisheri         Melanosuchus latrubessei \n                               1                                1 \n              Melanosuchus niger      Menatalligator bergouniouxi \n                               1                                1 \n         Mourasuchus amazonensis              Mourasuchus arendsi \n                               4                                9 \n              Mourasuchus atopus           Mourasuchus pattersoni \n                               8                                1 \n              Navajosuchus mooki             Necrosuchus ionensis \n                               2                                1 \n           Nihilichnus nihilicus     Orientalosuchus naduongensis \n                               1                                1 \n          Orthogenysuchus olseni              Osteolaemus osborni \n                               1                                1 \n           Osteolaemus tetraspes               Paludirex gracilis \n                               3                                3 \n              Paludirex vincenti            Paranacaiman bravardi \n                               3                                1 \n         Paranasuchus gasparinae            Paratomistoma courtii \n                               2                                1 \n               Penghusuchus pani   Piscogavialis jugaliperforatus \n                               1                                3 \n         Planocrania datangensis        Planocrania hengdongensis \n                               1                                1 \n             Procaimanoidea kayi         Procaimanoidea utahensis \n                               2                                1 \n     Protoalligator huiningensis          Protocaiman peligrensis \n                               1                                1 \n        Purussaurus brasiliensis             Purussaurus mirandai \n                               4                                9 \n           Purussaurus neivensis           Qianshanosuchus youngi \n                               9                                1 \n                Quinkana babarra            Quinkana fortirostrum \n                               1                                1 \n                Quinkana meboldi                  Quinkana timara \n                               1                                2 \n       Rhamphostomopsis neogaeus         Rhamphosuchus crassidens \n                               2                                3 \n               Rimasuchus lloydi            Sacacosuchus cordovai \n                               8                                3 \n            Sakhibaghoon khizari   Siquisiquesuchus venezuelensis \n                               1                                2 \n            Sutekhsuchus dowsoni            Thecachampsa antiquus \n                               5                                8 \n       Thecachampsa carolinensis         Thecachampsa marylandica \n                               7                                2 \n          Thecachampsa sericodon        Thoracosaurus isorhynchus \n                              16                                1 \n    Thoracosaurus neocesariensis              Tienosuchus hsiangi \n                               5                                1 \n               Tomistoma brumpti               Tomistoma cairense \n                               1                                1 \n           Tomistoma calaritanum               Tomistoma coppensi \n                               1                                8 \n             Tomistoma kerunense             Tomistoma lusitanica \n                               1                                2 \n            Tomistoma schlegelii                Tomistoma tandoni \n                               1                                1 \n           Tomistoma tenuirostre       Toyotamaphimeia taiwanicus \n                               1                                2 \n         Trilophosuchus rackhami        Tsoabichi greenriverensis \n                               1                                2 \n          Tzaganosuchus infansis              Ultrastenos willisi \n                               1                                1 \n     Wannaganosuchus brachymanus \n                               1 \n```\n\n\n:::\n:::\n\n\nAlternatively, we can use the `tax_check()` function in the `palaeoverse` package, which systematically searches for and flags potential spelling variation using a defined dissimilarity threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for close spellings in the \"genus\" column\ntax_check(taxdf = fossils, name = \"genus\", dis = 0.1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in tax_check(taxdf = fossils, name = \"genus\", dis = 0.1): Non-letter\ncharacters present in the taxon names\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$synonyms\nNULL\n\n$non_letter_name\n[1] \"Crocodylus (Leptorhynchus)\"\n\n$non_letter_group\nNULL\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check for close spellings in the \"accepted_name\" column\ntax_check(taxdf = fossils_sp, name = \"accepted_name\" , dis = 0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$synonyms\n  group             greater                lesser count_greater count_lesser\n1     C    Crocodylus aptus     Crocodylus acutus             2            1\n2     D Diplocynodon ungeri Diplocynodon muelleri            16            6\n\n$non_letter_name\nNULL\n\n$non_letter_group\nNULL\n```\n\n\n:::\n:::\n\n\nTwo names are flagged here for our dissimilarity theshold. However, on further inspection from the literature, these are two distinct species and therefore not a spelling mistake.\n\nWe can also check formatting and spelling using the `fossilbrush` package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a list of taxonomic ranks to check\nfossil_ranks <- c(\"phylum\", \"class\", \"order\", \"family\", \"genus\")\n\n# Run checks\ncheck_taxonomy(as.data.frame(fossils), ranks = fossil_ranks)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking formatting [1/4]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n - formatting errors detected (see $formatting in output)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking spelling   [2/4]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n - no potential synonyms detected\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking ranks      [3/4]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n - no cross-rank names detected\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nChecking taxonomy   [4/4]\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n - conflicting classifications detected (see $duplicates in output)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$formatting\n$formatting$`non-letter`\n$formatting$`non-letter`$phylum\ninteger(0)\n\n$formatting$`non-letter`$class\ninteger(0)\n\n$formatting$`non-letter`$order\ninteger(0)\n\n$formatting$`non-letter`$family\n  [1]    6    8  179  183  184  187  188  191  208  214  218  232  270  281  282\n [16]  288  298  299  314  315  328  329  331  332  335  336  367  368  369  370\n [31]  504  534  538  542  562  563  565  567  568  569  570  571  572  573  578\n [46]  579  580  581  582  583  584  588  589  590  601  607  608  614  615  616\n [61]  619  620  629  631  663  665  666  679  703  704  705  706  707  708  709\n [76]  710  711  713  714  715  720  721  722  723  727  735  749  750  752  753\n [91]  757  760  784  794  795  813  822  825  826  827  828  838  839  840  844\n[106]  860  862  863  864  865  866  867  868  874  876  877  878  879  880  890\n[121]  891  892  893  894  896  897  899  900  902  903  904  905  907  921  922\n[136]  923  924  925  926  927  928  929  935  936  937  938  939  940  941  942\n[151]  943  944  945  946  956  957  958  959  960  962  963  964  976  977  978\n[166]  982  987  999 1011 1027 1028 1029 1034 1035 1036 1037 1038 1039 1074 1075\n[181] 1076 1077 1082 1086 1098 1099 1100 1101 1102 1103 1104 1105 1107 1110 1129\n[196] 1130 1136 1137 1138 1152 1155 1156 1157 1158 1159 1161 1166 1210 1222 1226\n[211] 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246 1247\n[226] 1248 1249 1250 1251 1252 1253 1268 1270 1271 1274 1281 1283 1284 1293 1294\n[241] 1295 1331 1334 1335 1337 1342 1388 1392 1399 1400 1401 1403 1404 1412 1418\n[256] 1451 1452 1453 1454 1455 1456 1457 1458 1462 1463 1465 1467 1492 1494 1496\n[271] 1497 1498 1500 1501 1502 1506 1508 1509 1510 1517 1518 1519 1520 1523 1531\n[286] 1579 1587 1594 1611 1612 1613 1618 1621 1628 1629 1641 1646 1657 1658 1660\n[301] 1678 1679 1701 1702 1724 1732 1735 1741 1776 1778 1779 1810 1811 1814 1824\n[316] 1826 1830 1831 1832 1833 1835 1836 1838 1879 1880 1881 1882 1883 1884 1885\n[331] 1886 1887 1888 1889 1890 1891 1931 1937 1938 1939 1940 1945 1946 1951 1952\n[346] 1956 1958 1959 1964 1980 1982 1983 1984 1985 1986 1987 1988\n\n$formatting$`non-letter`$genus\n[1] 1773\n\n\n$formatting$`word-count`\n$formatting$`word-count`$phylum\ninteger(0)\n\n$formatting$`word-count`$class\ninteger(0)\n\n$formatting$`word-count`$order\ninteger(0)\n\n$formatting$`word-count`$family\ninteger(0)\n\n$formatting$`word-count`$genus\n[1] 1773\n\n\n\n$ranks\n$ranks$crossed_adj\n$ranks$crossed_adj$`genus--family`\ncharacter(0)\n\n$ranks$crossed_adj$`family--order`\ncharacter(0)\n\n$ranks$crossed_adj$`order--class`\ncharacter(0)\n\n$ranks$crossed_adj$`class--phylum`\ncharacter(0)\n\n\n$ranks$crossed_all\n$ranks$crossed_all$genus\ncharacter(0)\n\n$ranks$crossed_all$family\ncharacter(0)\n\n$ranks$crossed_all$order\ncharacter(0)\n\n$ranks$crossed_all$class\ncharacter(0)\n\n\n\n$duplicates\n[1] taxon rank \n<0 rows> (or 0-length row.names)\n```\n\n\n:::\n:::\n\n\nAs before, no major inconsistencies or potential spelling errors were flagged.\n\nThe PBDB has an integrated taxonomy system which limits the extent to which taxon name inconsistencies can arise. However, this is not the case for some other data fields. Therefore, we should certainly check for inconsistencies in other of these fields. \n\nFor now, let's proceed to the next step of the analytical pipeline, but be sure to further explore the data looking for inconsistencies during the practical (below). \n\n## Identify and handle duplicates\n\nOur next step is to remove duplicates. This is an important step for count data, as duplicated values will artificially inflate our counts. Here, the function `dplyr::distinct()` is incredibly useful, as we can provide it with the columns we want it to check, and it removes rows for which data within those columns is identical.\n\nFirst, we will remove *absolute* duplicates: by this, we mean occurrences within a single collection which have identical taxonomic names. This can occur when, for example, two species are named within a collection, one of which is later synonymised with the other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show number of rows in dataset before duplicates are removed\nnrow(fossils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2009\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove occurrences with the same collection number and `accepted_name`\nfossils <- distinct(fossils, collection_no, accepted_name, .keep_all = TRUE)\n\n# Show number of rows in dataset after duplicates are removed\nnrow(fossils)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1956\n```\n\n\n:::\n:::\n\n\nThe number of rows dropped, which means that some of our occurrences were absolute duplicates and have now been removed.\n\nNext, we can look at geographic duplicates. We mentioned earlier that sometimes PBDB collections are entered separately for different beds from the same locality, and this means that the number of collections can be higher than the number of geographic sampling localities. Let’s check whether this is the case in our dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove duplicates based on geographic coordinates\nfossils_localities <- distinct(fossils, lng, lat, .keep_all = TRUE)\n\n# Compare length of vector of unique collection numbers with and without this\n# filter\nlength(unique(fossils$collection_no))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1484\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(unique(fossils_localities$collection_no))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1085\n```\n\n\n:::\n:::\n\n\nHere we can see that the number collections of our original dataset dropped after we removed latitude-longitude repeats. This means that, in some cases, more than one fossil sampling events have taken place at the same locality. In other words, we have more collections than geographically distinct localities in the dataset.\n\nIf we are interested in taxonomic diversity, we can also look at repeated names in our dataset. For example, we might want to identify taxa which are represented multiple times in order to then return to the literature and check that they definitely represent the same taxon. We can do this by flagging species names which are represented more than once in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Update dataset of occurrences identified to species level\nfossils_sp <- filter(fossils, accepted_rank == \"species\")\n  \n# Identify and flag taxonomic duplicates\nfossils_sp <- fossils_sp %>% \n  group_by(accepted_name) %>% \n  mutate(duplicate_flag = n() > 1)\n\n# Show counts of flagged occurrences\ntable(fossils_sp$duplicate_flag)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nFALSE  TRUE \n  100   604 \n```\n\n\n:::\n:::\n\n\nSome `FALSE` values are shown, indicating that some species are represented by a single occurrence. We also have `TRUE` values, for which the species are represented two or more times. We can then filter our dataset to those flagged, and sort them by their name, enabling easier checking.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter table to flagged occurrences\nfossils_sp <- filter(fossils_sp, duplicate_flag == TRUE)\n\n# Sort table by genus name\nfossils_sp <- arrange(fossils_sp, accepted_name)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfossils_sp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 604 × 143\n# Groups:   accepted_name [115]\n   occurrence_no record_type reid_no flags collection_no identified_name        \n           <int> <chr>         <int> <chr>         <int> <chr>                  \n 1        624984 occ           35409 <NA>          55602 Acresuchus pachytempor…\n 2       1094079 occ           35408 <NA>         136717 Acresuchus pachytempor…\n 3       1430835 occ              NA <NA>         144739 Acresuchus pachytempor…\n 4       1430836 occ              NA <NA>         191932 Acresuchus pachytempor…\n 5       1430837 occ              NA <NA>         136720 Acresuchus pachytempor…\n 6       1430838 occ              NA <NA>          67386 Acresuchus pachytempor…\n 7       1557989 occ              NA <NA>         219762 Acresuchus pachytempor…\n 8        691946 occ              NA <NA>          74555 Akanthosuchus langstoni\n 9        710089 occ              NA <NA>          76063 Akanthosuchus langston…\n10        710090 occ              NA <NA>          76064 Akanthosuchus langstoni\n# ℹ 594 more rows\n# ℹ 137 more variables: identified_rank <chr>, identified_no <int>,\n#   difference <chr>, accepted_name <chr>, accepted_attr <lgl>,\n#   accepted_rank <chr>, accepted_no <int>, early_interval <chr>,\n#   late_interval <chr>, max_ma <dbl>, min_ma <dbl>, ref_author <chr>,\n#   ref_pubyr <int>, reference_no <int>, phylum <chr>, class <chr>,\n#   order <chr>, family <chr>, genus <chr>, plant_organ <lgl>, …\n```\n\n\n:::\n:::\n\n\n\n::: {.callout-important}\n\n#### Caution\n\nIf data are altered or filtered at any point, this can change the overall summary statistics, and affect how we perceive the data. We recommend double-checking the data before proceeding to analytical processes relating to your research question.\n\n:::\n\n## Practical (if you so desire)\n\nNow it's time for you to explore that data yourself. First, using the code chunks below, add your own additional lines of code addressing each of the posed questions. You could modify some of the code above to help you, or write your own!\n\nCan you find any additional ***missing data***? What will you do with them?\n\n\n::: {.cell}\n\n:::\n\n\nCan you find any additional ***data outliers***? What will you do with them?\n\n\n::: {.cell}\n\n:::\n\n\nCan you find any additional ***data inconsistencies***? What will you do with them?\n\n\n::: {.cell}\n\n:::\n\n\nCan you find any additional ***data duplicates***? What will you do with them?\n\n\n::: {.cell}\n\n:::\n\n\nLet's save our data for the next unit!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Save data\nwrite.csv(x = fossils, file = \"./cenozoic_crocs_clean.csv\", row.names = FALSE)\n```\n:::\n\n\n# Resources\n\n1. AGGARWAL, C. C. 2017. Outlier Analysis. Springer.\n2. CHAPMAN, A. D. 2005. Principles and methods of data cleaning. Global Biodiversity Information Facility.\n3. HAMMER, Ø. and HARPER, D. A. 2024. Paleontological data analysis. John Wiley & Sons.\n4. NEWMAN, D. A. 2014. Missing data: Five practical guidelines. Organizational research methods, 17, 372–411.\n5. RIBEIRO, B. R., VELAZCO, S. J. E., GUIDONI-MARTINS, K., TESSAROLO, G., JARDIM, L., BACHMAN, S. P. and LOYOLA, R. 2022. bdc: A toolkit for standardizing, integrating and cleaning biodiversity data. Methods in Ecology and Evolution, 13, 1421–1428.\n6. TUKEY, J. W. 1977. Exploratory data analysis. Vol. 1. Springer.\n7. VAN BUUREN, S. 2018. Flexible imputation of missing data. Chapman & Hall/CRC, Boca Raton,.\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}