{
  "hash": "8ebe7ad984108de246ac5ada27e043b5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"CPEG Workshop Afternoon Session\"\nformat: html\neditor: visual\nauthor: 'Erin M. Dillon & Christopher D. Dean'\ndate: 2025-07-27\ntitle-block-banner: true\ndescription: 'Data Processing II: Harmonization and Synthesis'\n---\n\n## Learning Objectives\n\nIn this session, we'll walk through how to combine and use different deep-time and modern datasets to answer questions that cross the palaeo-ecological divide. We'll cover:\n\n-  The power of harmonizing data from different sources.\n-  The considerations and complications that arise when combining datasets.\n-  How to source spatially explicit climatic data for the past and present, and how to look at relationships with fossil and modern occurrences.\n-  How to plan, write code for, and carry out projects covering multiple time frames.\n\nTo do this, we'll continue using the Crocodylia dataset we've been working with earlier today. If you've not quite finished cleaning your dataset, you can find a cleaned version that's ready for this next step **HERE**.\n\n## Plan for the Session\n\nThe session will be split into the following sections:\n\nI.   Introduction to harmonization and synthesis\nII.  Planning, setup, and finding your data\nIII. Building a workflow to merge datasets\nIV.  Data visualisation and synthesis\n\n## I. Introduction to Harmonization and Synthesis\n\nPresentation goes here??\n\n## II. Planning, Setup, and Finding Your Data\n\n### Our Research Question\n\nBefore starting, we first need to define our research question, which will be framed around the dataset of Cenozoic Crocodylia that we've been working on this morning. As mentioned previously, Crocs are an excellent group to use for studies comparing modern and deep-time records: they have a very tight association with temperature, are well represented in the fossil record spatially and temporally, and many extant species are threatened by anthropogenic impacts including habitat loss and climate change.\n\nIn this section, we'll aim to answer the following research question: **How does the temperature range inhabited by Crocodylia in deep-time compare to that seen in the present?**\n\nWe'll focus our deep-time analysis on the Miocene, a climatically dynamic epoch in Earth's history that can serve as an analog for future climate scenarios (e.g., Steinthorsdottir et al. 2020, https://doi.org/10.1029/2020PA004037).\n\n### Making a Plan\n\nBefore we start, it's helpful to write out a step-by-step plan of what we want to accomplish to ensure that the approach we're taking and the code that we write will appropriately answer the question(s) that we are interested in. Think of this as a kind of \"logical flow.\" In other words, what are all the steps needed to get from our research idea to our finalised analysis? This can be as extensive as you wish and can be done in any fashion---even writing out your code or general approach on pen and paper! We'll be doing this a few times today, so let's start by considering our research question and what materials we will need to address it.\n\nAs we aim to compare the distributions of Crocodylia in deep-time compared to the present, there are a couple of key datasets that we will require:\n\n1.  A spatially explicit dataset of modern Crocodylia\n2.  A spatially explicit dataset of Crocodylia in the deep-time intervals we will assess\n3.  A spatially explicit dataset of modern climatic variables\n4.  A spatially explicit dataset of climatic variables for the deep-time intervals we choose, likely generated from palaeoclimatic modelling\n\n::: {.callout-note title=\"Heads Up!\"}\nEven at this first step, the decisions we make will have consequences for our research and findings. For example, our choice of datasets and how they are handled can impact our results. This will be a recurring theme throughout the session.\n:::\n\n## **BREAKOUT SESSION 1**\n\n**Organize yourselves into groups of 4-6 and discuss the following questions:**\n\n***- What issues might we encounter when sourcing, gathering, and working with these various climatic and occurrence datasets?***\n\n***-What caveats should we be aware of, and how can they be addressed?***\n\n## III. Building a Workflow to Merge Datasets\n\nWe'll now walk through an example for how we might acquire and harmonize our climatic data. First, let's make a plan of the steps we'll take and some of the decisions we'll need to consider along the way.\n\n1.  **Decide which climate data to use.** What will be most appropriate for the taxonomic group we are studying? Some potential choices might be:\n\n-   The mean annual temperature\n-   The mean annual range of temperature\n-   The annual standard deviation of temperature\n-   The temperature of the hottest or coldest quarter\n\n2.  **Find a suitable source of data.** We will need to find spatially climatic data for each time interval we are interested in and acquire it in an appropriate format (.nc). What factors might we consider?\n\n-   Spatial resolution\n-   Temporal resolution\n\n3.  **Sort file structure.** Ensure that your R project is set up appropriately and that the downloaded files are in an appropriate place.\n\n4.  **Load data.** Read our data into R in an appropriate format to work with (e.g., raster). How might we do this? What packages might we need?\n\n5.  **Check formatting.** Ensure that the data are formatted appropriately. How might this impact our results or interpretations? What issues should we be aware of?\n\n-   Do the data have the right extent for our research question and R pipeline, and can this be changed?\n-   Are they at an appropriate spatial/temporal resolution, and can this be changed?\n-   Are they in the right Coordinate Reference System?\n-   Are they capturing the same climatic information?\n\n6.  **Prepare for analysis.** Ensure that the data are ready to be used in our next stages of analysis.To do this, we might want to break down our steps further:\n\n-   Check the format of the data using the 'class()' function\n-   Make a reference raster with appropriate resolution and extent\n-   Ensure climate raster doesn't have wrapping/extent issues, and rotate if necessary\n-   Re-sample raster to our reference raster\n-   Ensure that all rasters are capturing the same climatic information\n\nNow that we have a basic plan, we can start to put it into action. Let's write some code!\n\n### 0. Set-up\n\nFirst, we'll need to install and load some packages that will allow us to work with our data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install necessary packages\n#install.packages(\"rgbif\")\n#install.packages(\"tidyverse\")\n#install.packages(\"ggplot2\")\n#install.packages(\"palaeoverse\")\n#install.packages(\"raster\")\n#install.packages(\"sf\")\n#install.packages(\"geodata\")\n#install.packages(\"rnaturalearth\")\n#install.packages(\"ncdf4\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load packages\nlibrary(rgbif)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.2     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(palaeoverse)\nlibrary(raster)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: sp\n\nAttaching package: 'raster'\n\nThe following object is masked from 'package:dplyr':\n\n    select\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.4.0; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(geodata)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: terra\nterra 1.8.54\n\nAttaching package: 'terra'\n\nThe following object is masked from 'package:tidyr':\n\n    extract\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rnaturalearth)\nlibrary(ncdf4)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set resolution\nres <- 1\n\n# Set extent\ne <- extent(-180, 180, -90, 90)\n\n# Make generic raster\nr <- raster(res = res, ext = e)\n```\n:::\n\n\n\n### 1. Organising Palaeo-climatic Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make function to carry out action faster\nprep.raster <- function(file_path, ref.raster){\n  # Load .nc file\n  raster2prep <- raster(file_path)\n  # Rotate data to solve world wrapping issue (if necessary)\n  raster.rotated <- raster::rotate(raster2prep)\n  # Resample data (the extent and resolution must be updated to avoid rgdal issue)\n  raster.resampled <- resample(x = raster.rotated, y = ref.raster)\n  # Return data\n  return(raster.resampled)\n}\n```\n:::\n\n\nAfter exploring several potential palaeo-climatic datasets, we've decided to use a dataset of global mean surface temperatures for the Phanerozoic (Scotese 2022), based on HadleyCM3L simulations and aligned with geochemical proxies like ∂18O. The data are available for 5-million-year intervals that cover our time period of interest (Miocene) and have a 1x1 degree (lat/long) resolution. The dataset is also publically accessible via Zenodo: https://zenodo.org/records/5718392.\n\nCitations:\nScotese, C. R., Song, H., Mills, B. J. W., & van der Meer, D. G. (2021). Phanerozoic paleotemperatures: The earth’s changing climate during the last 540 million years. Earth-Science Reviews, 215, 103503. https://doi.org/10.1016/j.earscirev.2021.103503\n\nValdes, P.J., Scotese, C.R., and Lunt, D.J. (2021). Deep Ocean Temperatures through Time, Climates of the Past, Discussions, https://doi.org/10.5194/cp-2020-83. \n\nThis climatic dataset offers decently high temporal resolution (for deep time), but one thing we'll need to keep in mind is that the 5-million-year intervals don't align perfectly with geological stages. This will come into play later when we start working with the occurrence data.\n\nFor our study, we'll work with two files from this dataset: one covering 25-20 Ma and another covering 20-15 Ma. These data span warming intervals like the Mid Miocene Climatic Optimum and cooling intervals like the Oligocene-Miocene Climate Transition.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in our data\n# 20-15 Ma interval\nscotese15 <- prep.raster(file_path = \"015_tas_scotese02a_v21321.nc\", \n                         ref.raster = r)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in .local(x, ...): xmin is much smaller than zero. No rotation done\n```\n\n\n:::\n\n```{.r .cell-code}\n# 25-20 Ma interval\nscotese20 <- prep.raster(file_path = \"020_tas_scotese02a_v21321.nc\", \n                         ref.raster = r)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in .local(x, ...): xmin is much smaller than zero. No rotation done\n```\n\n\n:::\n\n```{.r .cell-code}\n# Stack rasters\nscotese.temp <- stack(scotese15, scotese20)\n\n# Name and plot rasters\nnames(scotese.temp) <- c(\"Burdigalian\",\"Aquitanian\")\nplot(scotese.temp)\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n### 2. Organising Modern Climatic Data\n\nWe'll obtain our modern climatic data from WorldClim: https://www.worldclim.org/\nTo keep our climatic variables consistent, we'll also work with the mean annual temperature data.\n\nNOTE: in here include option for pre-downloaded data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data from WorldClim and make into raster\nmodern <- worldclim_global(var = \"tavg\", res = 2.5, path = tempdir())\nmodern <- as(modern, \"Raster\")\n\n# Calculate mean annual temperature\nmodern.mean <- calc(x = modern, fun = mean)\n\n# Plot raster\nplot(modern.mean)\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis modern climatic data are considerably higher resolution than what we have available for our deep-time data. What issues might this cause? What actions could we take to resolve this? What could we test?\n\n\n## **BREAKOUT SESSION 2**\n\n**Now it's your turn to give it a go!**\n\n***-First, take a couple minutes to jot down a workflow for the fossil and modern occurrence data. Think about where you might find these data, if you'll need to do any filtering, and how you might get them in the right format such that we can make fair comparisons across time with the climatic data that we just read into R.***\n\n***-Then, get into the same groups and discuss your approach and where you might encounter potential pitfalls.*** \n\n\n### Solution\n\n::: {.callout-tip title=\"Solution\" collapse=\"true\"}\n\nLet's start by thinking about what we need from our occurrence datasets. To answer our question, we aim to compare Crocodylia occurrences in the past and present in relation to temperature data from the same points.\n\nHow do we get there? Let's outline some potential steps:\n\n1.  **Decide which occurrence data to use and where to source it.** The PBDB Crocodylia dataset we've been working with contains occurrences that span our interval of interest. Where might we find a comparable dataset of modern occurrences? Earlier today, we learned about the Global Biodiversity Information Facility (GBIF). This could be a good source!\n\n2.  **Filtering.** We'll need to do some filtering, for example to our time period of interest and to remove occurrences that have high uncertainty or aren't comparable between the datasets. What other filtering criteria might we consider?\n\n3.  **Cleaning.** As we learned in the previous session, we'll also want to spend some time cleaning and exploring our data.\n\n4.  **Merging data.** We'll next want to combine our occurrence and climatic datasets to extract the mean temperature values at the same points in space and time as the occurrences. When doing this, what are some factors we need to consider? This might involving binning our data given differences in temporal and spatial resolutions and making some decisions about which taxonomic level to run our analysis. Along the way, we'll likely need to think carefully about the dataframe structures and identify common data fields that are relevant for our study (time designations, taxonomy, coordinates, collection numbers, etc). We'll also want to consider potential sampling biases that might influence our comparisons.\n\n5. **Data extraction and visualisation.** At this point, we'll have binned fossil and modern occurrences with geographic coordinates and associated temperature data. Returning to our question, this will allow us to determine whether the fossil occurrences cover a broader range of temperatures than the modern occurrences.\n:::\n\nLet's begin!\n\n### 1. Sourcing occurrence data\n\n#### 1A. Organise fossil occurrence data\n\nFirst, we'll load in our palaeontological data. Luckily for us, we've already been working with a Crocodylia fossil occurrence dataset. We'll use these data in our analysis. If needed, you can read in the cleaned dataset below.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load cleaned fossil data for order Crocodylia\nfossil_occ <- read.csv(\"crocs_fossil_test.csv\")\n\n# Let's take a quick look\nhead(fossil_occ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  occurrence_no record_type reid_no flags collection_no\n1         40163         occ   18506                3113\n2         40167         occ      NA                3113\n3         40168         occ      NA                3113\n4         40169         occ      NA                3113\n5        149621         occ      NA               13221\n6        150083         occ      NA               13293\n                         identified_name identified_rank identified_no\n1                      Crocodylia indet.  unranked clade         38309\n2               Thoracosaurus basifissus         species        216615\n3            Thoracosaurus basitruncatus         species        216614\n4           Thoracosaurus neocesariensis         species        184628\n5 Mekosuchus inexpectatus n. gen. n. sp.         species        346455\n6                 Alligator cf. sinensis         species        173237\n    difference                accepted_name accepted_attr  accepted_rank\n1                                Crocodylia            NA unranked clade\n2 nomen dubium                  Gavialoidea            NA    superfamily\n3 nomen dubium                  Gavialoidea            NA    superfamily\n4              Thoracosaurus neocesariensis            NA        species\n5                   Mekosuchus inexpectatus            NA        species\n6                        Alligator sinensis            NA        species\n  accepted_no     early_interval    late_interval  max_ma  min_ma\n1       36582          Thanetian                  59.2400 56.0000\n2       96627          Thanetian                  59.2400 56.0000\n3       96627          Thanetian                  59.2400 56.0000\n4      184627          Thanetian                  59.2400 56.0000\n5      346455           Holocene                   0.0117  0.0000\n6      173237 Middle Pleistocene Late Pleistocene  0.7740  0.0117\n             ref_author ref_pubyr reference_no   phylum    class      order\n1                 Alroy      2006        18120 Chordata Reptilia Crocodylia\n2     Cook and Ramsdell      1991          140 Chordata Reptilia Crocodylia\n3     Cook and Ramsdell      1991          140 Chordata Reptilia Crocodylia\n4     Cook and Ramsdell      1991          140 Chordata Reptilia Crocodylia\n5 Balouet and Buffetaut      1987         4393 Chordata Reptilia Crocodylia\n6          Huang et al.      1988         4412 Chordata Reptilia Crocodylia\n               family         genus plant_organ abund_value abund_unit\n1                                            NA          NA           \n2                                            NA          NA           \n3                                            NA          NA           \n4          Gavialidae Thoracosaurus          NA          NA           \n5 NO_FAMILY_SPECIFIED    Mekosuchus          NA           2  specimens\n6       Alligatoridae     Alligator          NA          NA           \n        lng       lat                     occurrence_comments\n1 -74.68333  39.97194 originally entered as \"Crocodylus? sp.\"\n2 -74.68333  39.97194                                        \n3 -74.68333  39.97194                                        \n4 -74.68333  39.97194                                        \n5 164.95666 -21.33667                  MNHN NCP 06 (holotype)\n6 111.56667  22.76667                                        \n                                collection_name collection_subset\n1                      Vincentown Formation, NJ                NA\n2                      Vincentown Formation, NJ                NA\n3                      Vincentown Formation, NJ                NA\n4                      Vincentown Formation, NJ                NA\n5                 Pindai Cave, Nepoui Peninsula                NA\n6 Xiashan Cave, lower part (Guangdong Province)                NA\n              collection_aka cc      state  county             latlng_basis\n1                            US New Jersey               estimated from map\n2                            US New Jersey               estimated from map\n3                            US New Jersey               estimated from map\n4                            US New Jersey               estimated from map\n5 Pindaï Caves, Grande Terre NC                              stated in text\n6                            CN  Guangdong Luoding based on nearby landmark\n  latlng_precision altitude_value altitude_unit        geogscale\n1          seconds             NA                     local area\n2          seconds             NA                     local area\n3          seconds             NA                     local area\n4          seconds             NA                     local area\n5          seconds             NA                        outcrop\n6          minutes             NA               small collection\n                                                                                                                                                                                                                              geogcomments\n1 \"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portions of Monmouth, Ocean, burlington, Camden, Gloucester, and Salem Counties, near the inner margin of the Outer Coastal Plain\n2 \"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portions of Monmouth, Ocean, burlington, Camden, Gloucester, and Salem Counties, near the inner margin of the Outer Coastal Plain\n3 \"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portions of Monmouth, Ocean, burlington, Camden, Gloucester, and Salem Counties, near the inner margin of the Outer Coastal Plain\n4 \"The Vincentown Fm. occurs in an irregular, narrow belt extending diagonally [NE-SW] across NJ through portions of Monmouth, Ocean, burlington, Camden, Gloucester, and Salem Counties, near the inner margin of the Outer Coastal Plain\n5                                                                                                                                                              West coast of the Island of Grande Terre. Caves located 400 m from the sea.\n6                                                              Xiashan Cave, Xiashan River Valley, at the western side of Dayunwu Mountain, 4 km from the Capital of Pingtang District (Southwest of Luoding). Lat long is for Luoding.\\\\n\n  paleomodel                        geoplate paleoage paleolng paleolat\n1    gplates                             109      mid   -44.51    40.13\n2    gplates                             109      mid   -44.51    40.13\n3    gplates                             109      mid   -44.51    40.13\n4    gplates                             109      mid   -44.51    40.13\n5    gplates not computable using this model      mid       NA       NA\n6    gplates not computable using this model      mid       NA       NA\n  paleomodel2                       geoplate2 paleoage2 paleolng2 paleolat2\n1     scotese                             109       mid    -55.15     40.14\n2     scotese                             109       mid    -55.15     40.14\n3     scotese                             109       mid    -55.15     40.14\n4     scotese                             109       mid    -55.15     40.14\n5     scotese not computable using this model       mid        NA        NA\n6     scotese not computable using this model       mid        NA        NA\n  paleomodel3                       geoplate3 paleoage3 paleolng3 paleolat3\n1       seton                             101       mid    -54.04     39.29\n2       seton                             101       mid    -54.04     39.29\n3       seton                             101       mid    -54.04     39.29\n4       seton                             101       mid    -54.04     39.29\n5       seton not computable using this model       mid        NA        NA\n6       seton not computable using this model       mid        NA        NA\n  cc.1 protected direct_ma_value direct_ma_error direct_ma_unit\n1   US                        NA              NA               \n2   US                        NA              NA               \n3   US                        NA              NA               \n4   US                        NA              NA               \n5   NC                        NA              NA               \n6   CN                        NA              NA               \n  direct_ma_method max_ma_value max_ma_error max_ma_unit max_ma_method\n1                            NA           NA                          \n2                            NA           NA                          \n3                            NA           NA                          \n4                            NA           NA                          \n5                            NA           NA                          \n6                            NA           NA                          \n  min_ma_value min_ma_error min_ma_unit min_ma_method  formation stratgroup\n1           NA           NA                           Vincentown           \n2           NA           NA                           Vincentown           \n3           NA           NA                           Vincentown           \n4           NA           NA                           Vincentown           \n5           NA           NA                                                \n6           NA           NA                                                \n  member stratscale zone zone_type localsection    localbed localbedunit\n1         formation                  New Jersey                         \n2         formation                  New Jersey                         \n3         formation                  New Jersey                         \n4         formation                  New Jersey                         \n5                                                                       \n6                                               lower layer             \n  localorder regionalsection regionalbed regionalbedunit regionalorder\n1                                                                     \n2                                                                     \n3                                                                     \n4                                                                     \n5                                                                     \n6                                                                     \n                                                                                                                                                                                                                                                                                                                                                                                                                               stratcomments\n1                                                                                                                                                                                                                                                                                                                                                                                                                                           \n2                                                                                                                                                                                                                                                                                                                                                                                                                                           \n3                                                                                                                                                                                                                                                                                                                                                                                                                                           \n4                                                                                                                                                                                                                                                                                                                                                                                                                                           \n5 Bone accumulations were found at two sites near lateral exits now filled by unstratified sediment. Bones occurred from the surface to depths of about 1.5 m, where excavation was discontinued. Charcoal obtained at a depth of about 50 cm, in direct association with bones of Sylviornis and other extinct birds, gave a radiocarbon age of 1750 ± 70 years BP (Gif. 6341 [CNRS laboratory at Gif sur Yvette, France], Balouet, 1984a).\n6                                                                                                                                                                                                                                                                                                                                                      \"The sediments of the site belong to cave accumulations...\"\\\\nlate middle Pleistocene\n                                                                                                                                                                                                        lithdescript\n1                                                                                                                                                                                                                   \n2                                                                                                                                                                                                                   \n3                                                                                                                                                                                                                   \n4                                                                                                                                                                                                                   \n5 The sediments in the main part of the cave consist of phosphates and magnesic clay with several intercalated layers of gypsum (2-10 cm deep) that were deposited during dry periods when the cave was not flooded.\n6                                                                                                                                                                                   See stratigraphic column, Fig. 2\n  lithology1     lithadj1 lithification1 minor_lithology1 fossilsfrom1\n1  sandstone  glauconitic                sandy,calcareous             \n2  sandstone  glauconitic                sandy,calcareous             \n3  sandstone  glauconitic                sandy,calcareous             \n4  sandstone  glauconitic                sandy,calcareous             \n5  claystone   phosphatic    unlithified                              \n6  claystone brown,yellow    unlithified            sandy            Y\n  lithology2 lithadj2 lithification2 minor_lithology2 fossilsfrom2\n1                                                                 \n2                                                                 \n3                                                                 \n4                                                                 \n5                                                                 \n6                                                                 \n         environment tectonic_setting\n1                                    \n2                                    \n3                                    \n4                                    \n5               cave                 \n6 terrestrial indet.                 \n                                                                                                              geology_comments\n1                                   lithology described as a calcareous \"lime sand\" interbedded with a quartz or \"yellow sand\"\n2                                   lithology described as a calcareous \"lime sand\" interbedded with a quartz or \"yellow sand\"\n3                                   lithology described as a calcareous \"lime sand\" interbedded with a quartz or \"yellow sand\"\n4                                   lithology described as a calcareous \"lime sand\" interbedded with a quartz or \"yellow sand\"\n5 The deposits in the main Pindai Cave probably accumulated at the bottom of an underground lake that formerly filled the cave\n6                                                                                                                cave deposits\n              size_classes articulated_parts associated_parts common_body_parts\n1                                                                              \n2                                                                              \n3                                                                              \n4                                                                              \n5             macrofossils                                                     \n6 macrofossils,mesofossils                                                     \n  rare_body_parts feed_pred_traces artifacts component_comments\n1                                                              \n2                                                              \n3                                                              \n4                                                              \n5                                                              \n6                                                              \n             pres_mode preservation_quality spatial_resolution\n1                                                             \n2                                                             \n3                                                             \n4                                                             \n5 body,original carbon                 good                   \n6                 body                                        \n  temporal_resolution lagerstatten concentration orientation abund_in_sediment\n1                                                                             \n2                                                                             \n3                                                                             \n4                                                                             \n5                                                                             \n6                                                                             \n  sorting fragmentation bioerosion encrustation preservation_comments\n1                               NA                                   \n2                               NA                                   \n3                               NA                                   \n4                               NA                                   \n5                               NA                                   \n6                               NA                                   \n   collection_type    collection_methods museum collection_coverage\n1 biostratigraphic                                                 \n2 biostratigraphic                                                 \n3 biostratigraphic                                                 \n4 biostratigraphic                                                 \n5        taxonomic      field collection   MNHN                    \n6                  bulk,field collection                           \n  collection_size rock_censused collectors collection_dates\n1                                                          \n2                                                          \n3                                                          \n4                                                          \n5                                                          \n6                                                          \n                                                                                                                                                                  collection_comments\n1                                                                                                                                                                                    \n2                                                                                                                                                                                    \n3                                                                                                                                                                                    \n4                                                                                                                                                                                    \n5                                                                                                                                                                                    \n6 \"...this fauna represents a new vertebrate assemblage of late middle Pleistocene in Xijiang River Valley.\"\\\\r\\\\nMuseum: Guangdong Luoding bowuguan (Museum of Luoding in Guangdong)\n                                           taxonomy_comments\n1 this is the most updated faunal list for the Vincentown Fm\n2 this is the most updated faunal list for the Vincentown Fm\n3 this is the most updated faunal list for the Vincentown Fm\n4 this is the most updated faunal list for the Vincentown Fm\n5                                                           \n6                                                           \n       research_group taxon_environment environment_basis        motility\n1 marine invertebrate            marine                NA actively mobile\n2 marine invertebrate            marine                NA actively mobile\n3 marine invertebrate            marine                NA actively mobile\n4 marine invertebrate            marine                NA actively mobile\n5          vertebrate            marine                NA actively mobile\n6          vertebrate            marine                NA actively mobile\n  life_habit vision      diet reproduction ontogeny ecospace_comments\n1                NA carnivore           NA       NA                  \n2                NA carnivore           NA       NA                  \n3                NA carnivore           NA       NA                  \n4                NA carnivore           NA       NA                  \n5                NA carnivore           NA       NA                  \n6                NA carnivore           NA       NA                  \n     composition architecture thickness reinforcement\n1 hydroxyapatite           NA        NA            NA\n2 hydroxyapatite           NA        NA            NA\n3 hydroxyapatite           NA        NA            NA\n4 hydroxyapatite           NA        NA            NA\n5 hydroxyapatite           NA        NA            NA\n6 hydroxyapatite           NA        NA            NA\n```\n\n\n:::\n:::\n\n\n#### 1B. Organise modern occurrence data\n\nAfter looking at the number and coverage of available records, we've decided to use the GBIF data.\n\nWe'll start by doing a quick data download using the `rgbif` package for the purposes of this exploratory exercise. Note that this method for retrieving occurrences has some limitations, and we'd want to do a formal download query before running our full analysis for publication. For that, you'd need to make a GBIF account.\n\nHere's how we can do this. Scroll down to load the dataset we've previously downloaded.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set taxa key to order Crocodylia\n#crocodile_key <- name_backbone(name = \"Crocodylia\")$usageKey\n\n# Download data\n#modern_download <- occ_search(\n  #taxonKey = crocodile_key,\n  #hasCoordinate = TRUE, #needs to have coordinates\n  #basisOfRecord = \"PRESERVED_SPECIMEN\", #keeping just preserved specimens for better comparability with the PBDB data\n  #limit = 10000)  #adjust limit (if you set limit to 0, you can check the metadata to see how many records are available)\n\n# Extract data\n#modern_occ <- modern_download$data\n\n# Extract metadata\n#modern_meta <- modern_download$meta\n```\n:::\n\n\nFor ease, here's a csv of the raw data:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load modern data\nmodern_occ <- read.csv(\"crocs_modern.csv\") \n\n# Let's take a quick look\nhead(modern_occ)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  X        key                           scientificName decimalLatitude\n1 1 5069348825 Paleosuchus trigonatus (Schneider, 1801)       -1.168306\n2 2 5069348783 Paleosuchus trigonatus (Schneider, 1801)       -0.968056\n3 3 5069348719 Paleosuchus trigonatus (Schneider, 1801)        0.492778\n4 4 5069345375 Paleosuchus trigonatus (Schneider, 1801)        3.620250\n5 5 5069349450       Caiman crocodilus (Linnaeus, 1758)        4.226556\n6 6 5069348947   Paleosuchus palpebrosus (Cuvier, 1807)       -3.782250\n  decimalLongitude         issues                           datasetKey\n1        -72.92169 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n2        -73.04728 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n3        -76.46489 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n4        -67.54108 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n5        -68.01636 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n6        -70.19956 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n                      publishingOrgKey                      installationKey\n1 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n2 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n3 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n4 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n5 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n6 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n                hostingOrganizationKey publishingCountry protocol\n1 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n2 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n3 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n4 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n5 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n6 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n                    lastCrawled                    lastParsed crawlId\n1 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.141+00:00      15\n2 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.134+00:00      15\n3 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.106+00:00      15\n4 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:30.596+00:00      15\n5 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.392+00:00      15\n6 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.169+00:00      15\n       basisOfRecord individualCount occurrenceStatus taxonKey kingdomKey\n1 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n2 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n3 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n4 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n5 PRESERVED_SPECIMEN               1          PRESENT  8953936          1\n6 PRESERVED_SPECIMEN               1          PRESENT  2441396          1\n  phylumKey classKey familyKey genusKey speciesKey acceptedTaxonKey\n1        44 11493978   3238603  2441393    2441394          2441394\n2        44 11493978   3238603  2441393    2441394          2441394\n3        44 11493978   3238603  2441393    2441394          2441394\n4        44 11493978   3238603  2441393    2441394          2441394\n5        44 11493978   3238603  5220195    8953936          8953936\n6        44 11493978   3238603  2441393    2441396          2441396\n                    acceptedScientificName  kingdom   phylum        family\n1 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n2 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n3 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n4 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n5       Caiman crocodilus (Linnaeus, 1758) Animalia Chordata Alligatoridae\n6   Paleosuchus palpebrosus (Cuvier, 1807) Animalia Chordata Alligatoridae\n        genus                 species genericName specificEpithet taxonRank\n1 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n2 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n3 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n4 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n5      Caiman       Caiman crocodilus      Caiman      crocodilus   SPECIES\n6 Paleosuchus Paleosuchus palpebrosus Paleosuchus     palpebrosus   SPECIES\n  taxonomicStatus iucnRedListCategory      dateIdentified elevation\n1        ACCEPTED                  LC 2023-02-02T00:00:00       114\n2        ACCEPTED                  LC 2023-02-09T00:00:00       184\n3        ACCEPTED                  LC 2023-06-24T00:00:00       258\n4        ACCEPTED                  LC 2023-08-11T00:00:00       111\n5        ACCEPTED                  LC 2023-08-18T00:00:00       111\n6        ACCEPTED                  LC 2023-09-22T00:00:00       114\n  elevationAccuracy     continent stateProvince year month day  eventDate\n1                 0 SOUTH_AMERICA      Amazonas 2023     2   1 2023-02-01\n2                 0 SOUTH_AMERICA      Amazonas 2023     2   9 2023-02-09\n3                 0 SOUTH_AMERICA      Putumayo 2023     6  24 2023-06-24\n4                 0 SOUTH_AMERICA       Guainía 2023     8  11 2023-08-11\n5                 0 SOUTH_AMERICA       Vichada 2023     8  16 2023-08-16\n6                 0 SOUTH_AMERICA      Amazonas 2023     9  22 2023-09-22\n  startDayOfYear endDayOfYear               lastInterpreted\n1             32           32 2025-05-30T20:23:32.141+00:00\n2             40           40 2025-05-30T20:23:32.134+00:00\n3            175          175 2025-05-30T20:23:32.106+00:00\n4            223          223 2025-05-30T20:23:30.596+00:00\n5            228          228 2025-05-30T20:23:32.392+00:00\n6            265          265 2025-05-30T20:23:32.169+00:00\n                                                  license isSequenced\n1 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n2 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n3 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n4 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n5 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n6 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n            identifier facts relations isInCluster                   recordedBy\n1 SINCHI:SINCHI-R:3915  none      none        TRUE Grupo de herpetología Sinchi\n2 SINCHI:SINCHI-R:3943  none      none        TRUE Grupo de herpetología Sinchi\n3 SINCHI:SINCHI-R:3979  none      none        TRUE Grupo de herpetología Sinchi\n4 SINCHI:SINCHI-R:4119  none      none       FALSE Grupo de herpetología Sinchi\n5 SINCHI:SINCHI-R:4285  none      none       FALSE Grupo de herpetología Sinchi\n6 SINCHI:SINCHI-R:4262  none      none       FALSE Grupo de herpetología Sinchi\n          identifiedBy                               preparations\n1 Colector responsable Colecta definitiva: Animal completo (ETOH)\n2 Colector responsable Colecta definitiva: Animal completo (ETOH)\n3 Colector responsable Colecta definitiva: Animal completo (ETOH)\n4 Colector responsable Colecta definitiva: Animal completo (ETOH)\n5 Colector responsable Colecta definitiva: Animal completo (ETOH)\n6 Colector responsable Colecta definitiva: Animal completo (ETOH)\n  samplingProtocol dnaSequenceID geodeticDatum      class countryCode\n1   Búsqueda libre          none         WGS84 Crocodylia          CO\n2   Búsqueda libre          none         WGS84 Crocodylia          CO\n3   Búsqueda libre          none         WGS84 Crocodylia          CO\n4   Búsqueda libre          none         WGS84 Crocodylia          CO\n5   Búsqueda libre          none         WGS84 Crocodylia          CO\n6   Búsqueda libre          none         WGS84 Crocodylia          CO\n  recordedByIDs identifiedByIDs    gbifRegion  country publishedByGbifRegion\n1          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n2          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n3          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n4          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n5          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n6          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n  recordNumber         identifier.1                habitat institutionID\n1   SNC-H 2985 SINCHI:SINCHI-R:3915 Bosque de tierra firme 860.061.110-3\n2   SNC-H 3254 SINCHI:SINCHI-R:3943 Bosque de tierra firme 860.061.110-3\n3   SNC-H 3371 SINCHI:SINCHI-R:3979               Rastrojo 860.061.110-3\n4   SNC-H 3743 SINCHI:SINCHI-R:4119 Bosque de tierra firme 860.061.110-3\n5   SNC-H 3863 SINCHI:SINCHI-R:4285                   <NA> 860.061.110-3\n6   SNC-H 4394 SINCHI:SINCHI-R:4262 Bosque de tierra firme 860.061.110-3\n       county             municipality  verbatimCoordinateSystem collectionCode\n1 La Chorrera Comunidad de San Antonio Grados, minutos, segundos       SINCHI-R\n2 La Chorrera          Puerto Príncipe Grados, minutos, segundos       SINCHI-R\n3 Puerto Asís                   Cocayá Grados, minutos, segundos       SINCHI-R\n4    Cacahual    Comunidad de Chaquita Grados, minutos, segundos       SINCHI-R\n5    Cumaribo                     <NA> Grados, minutos, segundos       SINCHI-R\n6     Leticia          Sector Pucacuro Grados, minutos, segundos       SINCHI-R\n      gbifID language         occurrenceID           type\n1 5069348825       es SINCHI:SINCHI-R:3915 PhysicalObject\n2 5069348783       es SINCHI:SINCHI-R:3943 PhysicalObject\n3 5069348719       es SINCHI:SINCHI-R:3979 PhysicalObject\n4 5069345375       es SINCHI:SINCHI-R:4119 PhysicalObject\n5 5069349450       es SINCHI:SINCHI-R:4285 PhysicalObject\n6 5069348947       es SINCHI:SINCHI-R:4262 PhysicalObject\n                 taxonRemarks catalogNumber  disposition\n1 CITES:II | Endemismo: Falso          3915 En colección\n2 CITES:II | Endemismo: Falso          3943 En colección\n3 CITES:II | Endemismo: Falso          3979 En colección\n4 CITES:II | Endemismo: Falso          4119 En colección\n5 CITES:II | Endemismo: Falso          4285 En colección\n6 CITES:II | Endemismo: Falso          4262 En colección\n                                              institutionCode verbatimElevation\n1 Instituto Amazónico de Investigaciones Científicas (SINCHI)               114\n2 Instituto Amazónico de Investigaciones Científicas (SINCHI)               184\n3 Instituto Amazónico de Investigaciones Científicas (SINCHI)               258\n4 Instituto Amazónico de Investigaciones Científicas (SINCHI)               111\n5 Instituto Amazónico de Investigaciones Científicas (SINCHI)               111\n6 Instituto Amazónico de Investigaciones Científicas (SINCHI)               114\n                                                                                       collectionID\n1 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n2 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n3 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n4 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n5 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n6 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n                                      name    sex gadm institutionKey\n1 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n2 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n3 Paleosuchus trigonatus (Schneider, 1801) Female <NA>           <NA>\n4 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n5       Caiman crocodilus (Linnaeus, 1758)   <NA> <NA>           <NA>\n6   Paleosuchus palpebrosus (Cuvier, 1807)   Male <NA>           <NA>\n  datasetName rightsHolder references associatedSequences taxonConceptID\n1        <NA>         <NA>       <NA>                <NA>           <NA>\n2        <NA>         <NA>       <NA>                <NA>           <NA>\n3        <NA>         <NA>       <NA>                <NA>           <NA>\n4        <NA>         <NA>       <NA>                <NA>           <NA>\n5        <NA>         <NA>       <NA>                <NA>           <NA>\n6        <NA>         <NA>       <NA>                <NA>           <NA>\n  locality occurrenceRemarks taxonID organismQuantity eventRemarks\n1     <NA>              <NA>    <NA>               NA         <NA>\n2     <NA>              <NA>    <NA>               NA         <NA>\n3     <NA>              <NA>    <NA>               NA         <NA>\n4     <NA>              <NA>    <NA>               NA         <NA>\n5     <NA>              <NA>    <NA>               NA         <NA>\n6     <NA>              <NA>    <NA>               NA         <NA>\n  identificationRemarks lifeStage higherGeography modified collectionKey\n1                  <NA>      <NA>            <NA>     <NA>          <NA>\n2                  <NA>      <NA>            <NA>     <NA>          <NA>\n3                  <NA>      <NA>            <NA>     <NA>          <NA>\n4                  <NA>      <NA>            <NA>     <NA>          <NA>\n5                  <NA>      <NA>            <NA>     <NA>          <NA>\n6                  <NA>      <NA>            <NA>     <NA>          <NA>\n  otherCatalogNumbers recordedByIDs.type recordedByIDs.value\n1                <NA>               <NA>                <NA>\n2                <NA>               <NA>                <NA>\n3                <NA>               <NA>                <NA>\n4                <NA>               <NA>                <NA>\n5                <NA>               <NA>                <NA>\n6                <NA>               <NA>                <NA>\n  identifiedByIDs.type identifiedByIDs.value vernacularName nomenclaturalCode\n1                 <NA>                  <NA>           <NA>              <NA>\n2                 <NA>                  <NA>           <NA>              <NA>\n3                 <NA>                  <NA>           <NA>              <NA>\n4                 <NA>                  <NA>           <NA>              <NA>\n5                 <NA>                  <NA>           <NA>              <NA>\n6                 <NA>                  <NA>           <NA>              <NA>\n  locationID organismRemarks identificationQualifier higherClassification\n1       <NA>            <NA>                    <NA>                 <NA>\n2       <NA>            <NA>                    <NA>                 <NA>\n3       <NA>            <NA>                    <NA>                 <NA>\n4       <NA>            <NA>                    <NA>                 <NA>\n5       <NA>            <NA>                    <NA>                 <NA>\n6       <NA>            <NA>                    <NA>                 <NA>\n  parentNameUsage rights dataGeneralizations fieldNumber locationRemarks\n1            <NA>   <NA>                <NA>        <NA>            <NA>\n2            <NA>   <NA>                <NA>        <NA>            <NA>\n3            <NA>   <NA>                <NA>        <NA>            <NA>\n4            <NA>   <NA>                <NA>        <NA>            <NA>\n5            <NA>   <NA>                <NA>        <NA>            <NA>\n6            <NA>   <NA>                <NA>        <NA>            <NA>\n  previousIdentifications networkKeys coordinateUncertaintyInMeters\n1                    <NA>        <NA>                            NA\n2                    <NA>        <NA>                            NA\n3                    <NA>        <NA>                            NA\n4                    <NA>        <NA>                            NA\n5                    <NA>        <NA>                            NA\n6                    <NA>        <NA>                            NA\n  dynamicProperties identificationReferences http...unknown.org.taxonRankID\n1              <NA>                     <NA>                             NA\n2              <NA>                     <NA>                             NA\n3              <NA>                     <NA>                             NA\n4              <NA>                     <NA>                             NA\n5              <NA>                     <NA>                             NA\n6              <NA>                     <NA>                             NA\n  georeferenceProtocol verbatimSRS georeferenceVerificationStatus\n1                 <NA>        <NA>                           <NA>\n2                 <NA>        <NA>                           <NA>\n3                 <NA>        <NA>                           <NA>\n4                 <NA>        <NA>                           <NA>\n5                 <NA>        <NA>                           <NA>\n6                 <NA>        <NA>                           <NA>\n  http...unknown.org.species georeferenceSources earliestPeriodOrLowestSystem\n1                       <NA>                <NA>                         <NA>\n2                       <NA>                <NA>                         <NA>\n3                       <NA>                <NA>                         <NA>\n4                       <NA>                <NA>                         <NA>\n5                       <NA>                <NA>                         <NA>\n6                       <NA>                <NA>                         <NA>\n  latestPeriodOrHighestSystem earliestEpochOrLowestSeries\n1                        <NA>                        <NA>\n2                        <NA>                        <NA>\n3                        <NA>                        <NA>\n4                        <NA>                        <NA>\n5                        <NA>                        <NA>\n6                        <NA>                        <NA>\n  latestEpochOrHighestSeries earliestAgeOrLowestStage latestAgeOrHighestStage\n1                       <NA>                     <NA>                    <NA>\n2                       <NA>                     <NA>                    <NA>\n3                       <NA>                     <NA>                    <NA>\n4                       <NA>                     <NA>                    <NA>\n5                       <NA>                     <NA>                    <NA>\n6                       <NA>                     <NA>                    <NA>\n  acceptedNameUsage lithostratigraphicTerms infraspecificEpithet\n1              <NA>                    <NA>                 <NA>\n2              <NA>                    <NA>                 <NA>\n3              <NA>                    <NA>                 <NA>\n4              <NA>                    <NA>                 <NA>\n5              <NA>                    <NA>                 <NA>\n6              <NA>                    <NA>                 <NA>\n  georeferencedBy georeferencedDate verbatimEventDate verbatimLocality\n1            <NA>              <NA>              <NA>             <NA>\n2            <NA>              <NA>              <NA>             <NA>\n3            <NA>              <NA>              <NA>             <NA>\n4            <NA>              <NA>              <NA>             <NA>\n5            <NA>              <NA>              <NA>             <NA>\n6            <NA>              <NA>              <NA>             <NA>\n  locationAccordingTo eventTime accessRights ownerInstitutionCode projectId\n1                <NA>      <NA>         <NA>                 <NA>      <NA>\n2                <NA>      <NA>         <NA>                 <NA>      <NA>\n3                <NA>      <NA>         <NA>                 <NA>      <NA>\n4                <NA>      <NA>         <NA>                 <NA>      <NA>\n5                <NA>      <NA>         <NA>                 <NA>      <NA>\n6                <NA>      <NA>         <NA>                 <NA>      <NA>\n  organismQuantityType georeferenceRemarks degreeOfEstablishment\n1                 <NA>                <NA>                  <NA>\n2                 <NA>                <NA>                  <NA>\n3                 <NA>                <NA>                  <NA>\n4                 <NA>                <NA>                  <NA>\n5                 <NA>                <NA>                  <NA>\n6                 <NA>                <NA>                  <NA>\n  coordinatePrecision eventType organismScope higherGeographyID waterBody\n1                  NA      <NA>          <NA>              <NA>      <NA>\n2                  NA      <NA>          <NA>              <NA>      <NA>\n3                  NA      <NA>          <NA>              <NA>      <NA>\n4                  NA      <NA>          <NA>              <NA>      <NA>\n5                  NA      <NA>          <NA>              <NA>      <NA>\n6                  NA      <NA>          <NA>              <NA>      <NA>\n  samplingEffort materialSampleID datasetID bibliographicCitation depth\n1           <NA>             <NA>      <NA>                  <NA>    NA\n2           <NA>             <NA>      <NA>                  <NA>    NA\n3           <NA>             <NA>      <NA>                  <NA>    NA\n4           <NA>             <NA>      <NA>                  <NA>    NA\n5           <NA>             <NA>      <NA>                  <NA>    NA\n6           <NA>             <NA>      <NA>                  <NA>    NA\n  depthAccuracy typeStatus namePublishedInYear nameAccordingTo identificationID\n1            NA       <NA>                  NA            <NA>               NA\n2            NA       <NA>                  NA            <NA>               NA\n3            NA       <NA>                  NA            <NA>               NA\n4            NA       <NA>                  NA            <NA>               NA\n5            NA       <NA>                  NA            <NA>               NA\n6            NA       <NA>                  NA            <NA>               NA\n  programmeAcronym http...unknown.org.recordID eventID\n1             <NA>                        <NA>    <NA>\n2             <NA>                        <NA>    <NA>\n3             <NA>                        <NA>    <NA>\n4             <NA>                        <NA>    <NA>\n5             <NA>                        <NA>    <NA>\n6             <NA>                        <NA>    <NA>\n  identificationVerificationStatus organismID establishmentMeans\n1                             <NA>       <NA>               <NA>\n2                             <NA>       <NA>               <NA>\n3                             <NA>       <NA>               <NA>\n4                             <NA>       <NA>               <NA>\n5                             <NA>       <NA>               <NA>\n6                             <NA>       <NA>               <NA>\n  namePublishedIn footprintWKT associatedReferences\n1            <NA>         <NA>                 <NA>\n2            <NA>         <NA>                 <NA>\n3            <NA>         <NA>                 <NA>\n4            <NA>         <NA>                 <NA>\n5            <NA>         <NA>                 <NA>\n6            <NA>         <NA>                 <NA>\n  http...unknown.org.recordEnteredBy pointRadiusSpatialFit footprintSRS\n1                               <NA>                    NA         <NA>\n2                               <NA>                    NA         <NA>\n3                               <NA>                    NA         <NA>\n4                               <NA>                    NA         <NA>\n5                               <NA>                    NA         <NA>\n6                               <NA>                    NA         <NA>\n  footprintSpatialFit fieldNotes distanceFromCentroidInMeters\n1                  NA       <NA>                           NA\n2                  NA       <NA>                           NA\n3                  NA       <NA>                           NA\n4                  NA       <NA>                           NA\n5                  NA       <NA>                           NA\n6                  NA       <NA>                           NA\n  associatedOccurrences informationWithheld verbatimTaxonRank\n1                  <NA>                <NA>              <NA>\n2                  <NA>                <NA>              <NA>\n3                  <NA>                <NA>              <NA>\n4                  <NA>                <NA>              <NA>\n5                  <NA>                <NA>              <NA>\n6                  <NA>                <NA>              <NA>\n  verbatimIdentification verbatimLabel materialEntityID islandGroup island\n1                   <NA>          <NA>             <NA>        <NA>   <NA>\n2                   <NA>          <NA>             <NA>        <NA>   <NA>\n3                   <NA>          <NA>             <NA>        <NA>   <NA>\n4                   <NA>          <NA>             <NA>        <NA>   <NA>\n5                   <NA>          <NA>             <NA>        <NA>   <NA>\n6                   <NA>          <NA>             <NA>        <NA>   <NA>\n  http...unknown.org.typifiedName http...unknown.org.photographer organismName\n1                            <NA>                            <NA>         <NA>\n2                            <NA>                            <NA>         <NA>\n3                            <NA>                            <NA>         <NA>\n4                            <NA>                            <NA>         <NA>\n5                            <NA>                            <NA>         <NA>\n6                            <NA>                            <NA>         <NA>\n  typifiedName relationshipRemarks reproductiveCondition\n1         <NA>                <NA>                  <NA>\n2         <NA>                <NA>                  <NA>\n3         <NA>                <NA>                  <NA>\n4         <NA>                <NA>                  <NA>\n5         <NA>                <NA>                  <NA>\n6         <NA>                <NA>                  <NA>\n```\n\n\n:::\n:::\n\n\n\n### 2. Filtering\n\nThese datasets contain occurrences that are relevant to our research question, but they also contain occurrences that fall outside of the scope of our planned analysis. Let's filter the datasets to just keep the relevant occurrences. What were some of the filtering criteria you brainstormed during the breakout session?\n\n*-Data type:* Note that we've already queried GBIF for just the preserved specimens to optimize comparability with the PBDB dataset. For instance, GBIF also contains fossil specimens, living specimens, and human observations that either aren't entirely comparable with a fossil occurrence or don't represent our modern time interval.\n\n*-Taxonomic:* We'll run our analysis at the order level (Crocodylia) given taxonomic differences between the fossil and modern datasets at finer taxonomic levels (e.g., extinct taxa). That said, let's just retain occurrences that have been identified at least to genus (i.e., removing indet. taxa from the fossil dataset) given uncertainty in their taxonomy.\n\n*-Spatial:* Our research question is posed at a global scale, so we can keep everything. However, we will still want to check for potential geographic outliers or inconsistencies while cleaning the data.\n\n*-Temporal:* We'll constrain our palaeontological dataset to the same time intervals as our climatic dataset (25-15 Ma). Earlier, we downloaded Crocodylia occurrences for the whole of the Cenozoic, so we'll need to do some filtering. Our modern dataset includes occurrences from the 1800s to today, whereas the WorldClim dataset starts at 1970, so we can also filter the occurrence dataset to that time range for consistency.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## PBDB filtering\nfossil_occ_filter <- fossil_occ %>%\n  dplyr::filter(accepted_rank == \"genus\" | accepted_rank ==\"species\") %>% #taxonomic filtering\n  dplyr::filter(max_ma<=25 & min_ma>=15) #temporal filtering\n\n## GBIF filtering\nmodern_occ_filter <- modern_occ %>%\n  filter(!is.na(genus)) %>% #taxonomic filtering\n  filter(year >= 1970) %>% #temporal filtering\n  filter(coordinateUncertaintyInMeters < 10000 | is.na(coordinateUncertaintyInMeters)) #we could also remove data with uncertain geographic coordinates\n```\n:::\n\n\nThis filtering step could have removed a fair amount of data. How many occurrences remain in each filtered dataset?\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(fossil_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 114\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(modern_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2504\n```\n\n\n:::\n:::\n\n\nAfter filtering, we have 114 fossil occurrences and 2504 modern occurrences to potentially work with. How might we deal with this unequal sampling?\n\n\n### 3. Cleaning\n\nWe'll then want to explore and clean our data to check for outliers, inconsistencies, duplicates, and other potential issues.\n\nOur fossil occurrence dataset has already gone through this process.\n\n**Let's spend a couple of minutes cleaning and familiarising ourselves with the GBIF data, applying what we learned in the previous session.** For example, you might look at the range of latitudes represented by occurrences or check the taxa for spelling errors. You could plot them on a map to see if you notice any geographic oddities. Or you could check for duplicates.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Practice cleaning the modern occurrence dataset here!\n```\n:::\n\n\n\n### 4. Merging\n\nNow we come to the fun part. How do we align these data, which were sampled in different ways with different temporal and spatial resolutions and coverage?\n\nLet's begin by returning to the structure of each dataset. Note that the header names differ, and that the datasets contain variables reported in different ways (units, formats) and with different resolutions.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(fossil_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  occurrence_no record_type reid_no flags collection_no    identified_name\n1        287884         occ      NA               18663   Alligator olseni\n2        287885         occ      NA               18663  Gavialosuchus sp.\n3        395640         occ   37458               38060     Brochuchus sp.\n4        431435         occ      NA               42130     Euthecodon sp.\n5        442243         occ      NA               41812      Alligator sp.\n6        474026         occ   28885               47021 Crocodylus pigotti\n  identified_rank identified_no    difference      accepted_name accepted_attr\n1         species        110673                 Alligator olseni            NA\n2           genus         38416                    Gavialosuchus            NA\n3           genus        267490                       Brochuchus            NA\n4           genus         38445                       Euthecodon            NA\n5           genus         38423                        Alligator            NA\n6         species        158091 recombined as Brochuchus pigotti            NA\n  accepted_rank accepted_no early_interval late_interval max_ma min_ma\n1       species      110673     Aquitanian                23.04  20.45\n2         genus       38416     Aquitanian                23.04  20.45\n3         genus      267490    Burdigalian                20.45  15.98\n4         genus       38445     Aquitanian   Burdigalian  23.04  15.98\n5         genus       38423    Burdigalian                20.45  15.98\n6       species      158091    Burdigalian                20.45  15.98\n       ref_author ref_pubyr reference_no   phylum    class      order\n1        Albright      1994          742 Chordata Reptilia Crocodylia\n2        Albright      1994          742 Chordata Reptilia Crocodylia\n3 Cossette et al.      2020        73795 Chordata Reptilia Crocodylia\n4        Tawadros      2001        11199 Chordata Reptilia Crocodylia\n5   Chow and Wang      1964        11441 Chordata Reptilia Crocodylia\n6       Buffetaut      1984        47638 Chordata Reptilia Crocodylia\n               family         genus plant_organ abund_value abund_unit\n1       Alligatoridae     Alligator          NA          NA           \n2 NO_FAMILY_SPECIFIED Gavialosuchus          NA          NA           \n3        Crocodylidae    Brochuchus          NA          NA           \n4        Crocodylidae    Euthecodon          NA          NA           \n5       Alligatoridae     Alligator          NA          NA           \n6        Crocodylidae    Brochuchus          NA          NA           \n        lng       lat\n1 -93.40000 31.000000\n2 -93.40000 31.000000\n3  35.75000  3.333333\n4  19.20000 29.233334\n5 118.69556 32.139442\n6  49.39361 25.983610\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                occurrence_comments\n1 LSUMG V-2255, tooth; V-2698, approximately 180 teeth; V-2732, figured tooth; V-2733, two premaxillary fragments; V-2734, six maxillae fragments; V-2735, five nasal fragments; V-2736, three frontal fragments; V-2737, two frontoparietal fragments; V-2738, two parietal fragments; V-2739, post orbital fragment; V-2740, three squamosal fragments; V-2741, left posterior quadrate; V-2742, quadrate fragment; V-2743, quadrate-quadratojugal fragment; V-2744, quadratojugal fragment; V-2745, jugal fragment; V-2746, seven anterior dentary fragments; V-2747, figured right anterior dentary fragment; V-2748, articular fragment; V-2749, 22 lower jaw fragments; V-2750, vertebrae and vertebrae fragments; V-2751, femur; V-2752, five femur fragments; V-2753, proximal right humerus; V-2754, distal humerus; V-2755, proximal right tibia; V-2756, limb bone fragments; V-2757, three metapodials; V-2758, proximal phalanx; V-2759, claw fragment; V-2760, 63 dermal scutes; V-2761, two neck scutes; V-2762, six juvenile scutes\n2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   SUMG V-2247, anterior tooth; V-2517, five teeth\n3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \"Crocodilia nov.\"\n4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \n5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  \n6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1 left dentary with 13 alveoli, plus other specimens.\n                         collection_name collection_subset       collection_aka\n1                            Toledo Bend                NA                     \n2                            Toledo Bend                NA                     \n3         Kalodirr, west of Lake Turkana                NA West Turkana, KNM-WK\n4          Bir Zaltan - Marada Formation                NA                     \n5 Puchen Beds, Nanking, Northern Kiangsu                NA                     \n6   Al-Sarrar, Locality 6, Dam Formation                NA                     \n  cc   state  county             latlng_basis latlng_precision altitude_value\n1 US   Texas  Newton  based on political unit                1             NA\n2 US   Texas  Newton  based on political unit                1             NA\n3 KE                           stated in text          minutes             NA\n4 LY                 based on nearby landmark          seconds             NA\n5 CN Jiangsu Nanking based on nearby landmark          seconds             NA\n6 SA                       estimated from map          seconds             NA\n  altitude_unit  geogscale\n1                         \n2                         \n3                         \n4               local area\n5                         \n6                         \n                                                                                                                                                                                                                                                    geogcomments\n1                                                                                                                                                                27 km NE of Burkeville in a canal that connects the Toledo Bend Reservoir with the Sabine River\n2                                                                                                                                                                27 km NE of Burkeville in a canal that connects the Toledo Bend Reservoir with the Sabine River\n3 Kalodirr is located near the head-waters of the Kalodirr River (3°20’N, 35°45’E), extending from just south of the Lodwar-Kalakol road north to the Lokipenata Ridge; approximately 10km south of the Miocene localities: Losodok, Moruaret Hill and Moruarot.\n4                                                                                                                                                                                Bir Zaltan, Sirte Basin. Lat/long estimated based on Dur Marada (neaby), Libya.\n5                                                                                                                                  Co-ordinates based on Puchen, in Northern Kiangsu Province. The site is a quarry near Puchen, 8km north of the Yangtze River.\n6                                                            Al-Sarrar area, less than 90km from the coast of the Arabian Gulf. Rocks of the Dam formation are well exposed west of the road from Ain Dar Junction to Nu'ayriyah. Co-ordinates based on Ayn Dar.\n  paleomodel geoplate paleoage paleolng paleolat paleomodel2 geoplate2\n1    gplates      101      mid   -84.46    34.75     scotese       135\n2    gplates      101      mid   -84.46    34.75     scotese       135\n3    gplates      712      mid    35.22    -1.97     scotese       712\n4    gplates      715      mid    20.66    23.97     scotese       715\n5    gplates      604      mid   116.40    31.03     scotese       611\n6    gplates      503      mid    48.24    18.79     scotese       503\n  paleoage2 paleolng2 paleolat2 paleomodel3 geoplate3 paleoage3 paleolng3\n1       mid    -88.94     31.59       seton       101       mid    -88.46\n2       mid    -88.94     31.59       seton       101       mid    -88.46\n3       mid     33.58      2.17       seton       712       mid     33.17\n4       mid     17.93     28.21       seton       715       mid     16.21\n5       mid    116.61     32.93       seton       602       mid    116.24\n6       mid     46.73     22.92       seton       503       mid     45.35\n  paleolat3 cc.1 protected direct_ma_value direct_ma_error direct_ma_unit\n1     30.59   US                        NA              NA               \n2     30.59   US                        NA              NA               \n3      1.04   KE                        NA              NA               \n4     26.44   LY                        NA              NA               \n5     34.15   CN                        NA              NA               \n6     21.49   SA                        NA              NA               \n  direct_ma_method max_ma_value max_ma_error max_ma_unit max_ma_method\n1                            NA           NA                          \n2                            NA           NA                          \n3                          17.5         10.2          Ma          K-Ar\n4                            NA           NA                          \n5                            NA           NA                          \n6                            NA           NA                          \n  min_ma_value min_ma_error min_ma_unit min_ma_method formation stratgroup\n1           NA           NA                             Fleming           \n2           NA           NA                             Fleming           \n3         16.8          0.2          Ma          K-Ar  Lothidok           \n4           NA           NA                              Marada           \n5           NA           NA                            Shanwang           \n6           NA           NA                                 Dam           \n                member    stratscale zone zone_type localsection localbed\n1 upper Carnahan Bayou                                                   \n2 upper Carnahan Bayou                                                   \n3             Kalodirr group of beds                                     \n4                      group of beds                                     \n5                             member                      Puchen   Puchen\n6                          formation                                     \n  localbedunit localorder regionalsection regionalbed regionalbedunit\n1                                                                    \n2                                                                    \n3                                                                    \n4                                                                    \n5                                                                    \n6                                                                    \n  regionalorder\n1              \n2              \n3              \n4              \n5              \n6              \n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           stratcomments\n1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \n2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \n3                                                                                                                                                                                                                                                                                                                                                                                                          the site of Kalodirr (\"Oryx\" in the Turkana language) is located at the headwater of the Kalodirr River (3?20'N, 35?45'E) between the Lokipenata Ridge and the Basalt Hills to the east (Boschetto et al. 1992; Leakey and Leakey 1986a, b).\\\\r\\\\n\\\\r\\\\nGrossman et al. 2009: The age of the Kalodirr fauna can be well constrained based on K/Ar dating of the underlying Kalodirr tuffs (17.5+/-10.2 Ma) and the overlying Naserte tuffs (16.8+/-0.2 Ma), which divide the Kalodirr Member from the younger Naserte Member of the Lothidok Formation.\\\\r\\\\n\n4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 The Marada Formation is divided into two members; a lower Qarat Jahannam Member and an upper Ar Rahlah Member. The type section of the Qarat Jahannam Member has a thickness of 123 m (404 ft). The member is made up mostly of green and yellow sandstones with minor green shales, calcareous sandstones, limestones, dolomites, and gypsum. Assigned an Aquitanian-Burdigalian age.\n5 He et al. 2011: Samples SW2007 and SW01 from the basalt just below the fossil-bearing diatomaceous sediments of the Shanwang Formation yield near plateau age of 17–18 Ma. Sample SW8-13 from a lava flow in the Yaoshan Formation yields an age of 17.3 ± 1.4 Ma (Fig. 6b). These age determinations suggest that, the age of the Shanwang biota is ca. 17 Ma, which is late Burdigalian Age of the Early Miocene in the widely-used Geologic Time Scale 2004 (Gradstein et al., 2004). The age of 17 Ma presented in this study of the Shanwang biota supports previous interpretations that this mammal fauna can be correlated with MN4 in the middle Orleanian of the European Land Mammal Age (Steininger et al., 1996; Steininger, 1999; Agustí et al., 2001), the late Hemingfordian of the North American Land Mammal Age (Woodburne and Swisher, 1995; Alroy, 2000), and the Santacrucian of the South American Land Mammal Ages (Flynn and Swisher, 1995). \n6                                                                                                                                                                                                                                                                                                                                                                                                                               Late Early Miocene. There are 3 Formations in the succession - the Hadruck, Dam and Hofuf (Hofuf overlies the others). Type section of the Dam Formation is Jabal al Lidam. The depth of the formation at Al-Sarrar varies, but is around 30m. Near the Arabian Gulf the Formation is entirely marine, with more continental facies inland. The Al-Sarrar area is an area of 'continental sediments interbedded with the marine series'.\\\\r\\\\nFauna has been collected from a number of localities which have been entered individually.\n                                                                                                                                                                               lithdescript\n1                                                                                                                                                Paleochannel conglomerate (Albright, 1999)\n2                                                                                                                                                Paleochannel conglomerate (Albright, 1999)\n3                                                                                                                                                                                          \n4                                                                            Green and yellow sandstones with minor green shales, calcareous sandstones, limestones, dolomites, and gypsum.\n5                                'They occur in a series of greyish and brownish sands and conglomerates overlain by a bed of basalt lava.' Lithologically similar to the site of Fangshan.\n6 Locality 6, level 3 - Fossiliferous white sands containing terrestrial vertebrate remains. The only other layer with fossils is level 10 - white limestone with scarce marine pelecypods.\n    lithology1                           lithadj1 lithification1\n1 conglomerate                                                  \n2 conglomerate                                                  \n3 not reported                                                  \n4    sandstone dolomitic,gypsiferous,green,yellow      lithified\n5 conglomerate                         brown,gray               \n6 not reported                              white               \n  minor_lithology1 fossilsfrom1 lithology2 lithadj2 lithification2\n1                                                                 \n2                                                                 \n3                                                                 \n4       calcareous            Y    \"shale\"    green               \n5                             Y                                   \n6            sandy                                                \n  minor_lithology2 fossilsfrom2               environment tectonic_setting\n1                                     coarse channel fill                 \n2                                     coarse channel fill                 \n3                                               \"channel\"                 \n4                             Y          carbonate indet.                 \n5                                      terrestrial indet.                 \n6                               fluvial-lacustrine indet.                 \n                                                                                                                                                                                                                                                                                                                                  geology_comments\n1                                                                                                                                                                                                                                                                        conglomerate likely from episode of violent flood mixing (Albright, 1999)\n2                                                                                                                                                                                                                                                                        conglomerate likely from episode of violent flood mixing (Albright, 1999)\n3                                                                                                                                                                                                                                            Sedimentological analyses indicate deposition via small meandering stream channels (Boschetto, 1992).\n4                                                                                                                                                                                                                                                                                                             No paleoenvironmental data provided.\n5                                                                                                                                                                                                                                                                                                                                                 \n6 'The lithologies, sedimentary structures (presence of palaeocurrents in loc. 6 and 8), the character of the fauna exclusively continental and the deposition laid down into low energy zone (specially in loc. 6 and 8 explaining the scarcity of small vertebrates and the association of postcranial bones) suggest a fluviatile environment.'\n               size_classes articulated_parts associated_parts\n1  macrofossils,mesofossils                                   \n2  macrofossils,mesofossils                                   \n3              macrofossils                                   \n4 macrofossils,microfossils                                   \n5  macrofossils,mesofossils                                   \n6  macrofossils,mesofossils                                   \n  common_body_parts rare_body_parts feed_pred_traces artifacts\n1                                                             \n2                                                             \n3                                                             \n4                                                             \n5                                                             \n6                                                             \n  component_comments pres_mode preservation_quality spatial_resolution\n1                         body                                        \n2                         body                                        \n3                         body                                        \n4                         body                                        \n5                         body                                        \n6                         body                                        \n  temporal_resolution lagerstatten concentration orientation abund_in_sediment\n1                                                                             \n2                                                                             \n3                                                                             \n4                                                                             \n5                                                                             \n6                                                                             \n  sorting fragmentation bioerosion encrustation\n1                               NA             \n2                               NA             \n3                               NA             \n4                               NA             \n5                               NA             \n6                               NA             \n                                                                                                                                                                                                                                                                                                                                                                                                                       preservation_comments\n1                                                                                                                                                                                                                                                                                                                                                                                                                                           \n2                                                                                                                                                                                                                                                                                                                                                                                                                                           \n3                                                                                                                                                                                                                                                                                                                                                                                                                                           \n4                                                                                                                                                                                                                                                                                                                                                                                                               No taphonomic data reported.\n5                                                                                                                                                                                                                                                                                                                                                                                                                                           \n6 Favourable bone concentration in localities 6, 7, 8, 9 and 23. Associated postcranial elements are not rare in localities 6 and 8. Skulls and mandibles do not show any signs of rolling or transportation before burial; although fragile, scapula and tusks are taken out in good condition. Associated skull and mandible of mastodonts have been recovered from localities 6, 8 and 23, indicating burial in a low energy environment.\n        collection_type                          collection_methods museum\n1             taxonomic bulk,surface (float),sieve,field collection       \n2             taxonomic bulk,surface (float),sieve,field collection       \n3 general faunal/floral                                                   \n4 general faunal/floral                                                   \n5      biostratigraphic                                                   \n6 general faunal/floral                       bulk,field collection       \n  collection_coverage collection_size rock_censused collectors collection_dates\n1         some genera   700 specimens                                          \n2         some genera   700 specimens                                          \n3                                                                              \n4                                                                              \n5                                                                              \n6                                                                              \n                                                                                                                                                                                                                                                                                                                                            collection_comments\n1                                                                                                                                                                                                                                                                                                                                                              \n2                                                                                                                                                                                                                                                                                                                                                              \n3                                                                                                                                                                                                                                                                                                                                                              \n4                                                                                                                                                                                                                                                                                                                         No detailed collection data reported.\n5                                                                                                                                                                                                                                                                                                                                                              \n6 Al-Sarrar localities 4-9 and 11-24 can all be dated within a short period of time. Localities 5,6,7,8, and 9 are considered contemporaneous. \\\\r\\\\n1 ton of unconsolidated sand and silt from localities 6,8,9 and 21, has been sifted and has produced rodent teeth.\\\\r\\\\nAll fossil material housed in the Department of Antiquities and Museums at Riyadh.\n                                                                                                                                                                 taxonomy_comments\n1 preliminary and highly inaccurate list published by Manning 1990<br>small mammals described by Albright 1996<br>\"approximately 700 elements referred to mammals\": Albright 1998b\n2 preliminary and highly inaccurate list published by Manning 1990<br>small mammals described by Albright 1996<br>\"approximately 700 elements referred to mammals\": Albright 1998b\n3                                                                                                                                                                                 \n4                                                             Collection based on taxa listed in text as typical of formation. Includes molluscs, echinoderms and forams. Page 286\n5                                                                                                                                                                                 \n6                        Viperidae may possibly from this locality. Sirenia ribs found in surface deposits, but cannot be correlated with uppermost beds of localities 6, 8 and 9.\n       research_group taxon_environment environment_basis        motility\n1          vertebrate            marine                NA actively mobile\n2          vertebrate            marine                NA actively mobile\n3                                marine                NA actively mobile\n4 marine invertebrate            marine                NA actively mobile\n5               PACED            marine                NA actively mobile\n6               PACED            marine                NA actively mobile\n  life_habit vision      diet reproduction ontogeny ecospace_comments\n1                NA carnivore           NA       NA                  \n2                NA carnivore           NA       NA                  \n3                NA carnivore           NA       NA                  \n4                NA carnivore           NA       NA                  \n5                NA carnivore           NA       NA                  \n6                NA carnivore           NA       NA                  \n     composition architecture thickness reinforcement\n1 hydroxyapatite           NA        NA            NA\n2 hydroxyapatite           NA        NA            NA\n3 hydroxyapatite           NA        NA            NA\n4 hydroxyapatite           NA        NA            NA\n5 hydroxyapatite           NA        NA            NA\n6 hydroxyapatite           NA        NA            NA\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(modern_occ_filter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  X        key                           scientificName decimalLatitude\n1 1 5069348825 Paleosuchus trigonatus (Schneider, 1801)       -1.168306\n2 2 5069348783 Paleosuchus trigonatus (Schneider, 1801)       -0.968056\n3 3 5069348719 Paleosuchus trigonatus (Schneider, 1801)        0.492778\n4 4 5069345375 Paleosuchus trigonatus (Schneider, 1801)        3.620250\n5 5 5069349450       Caiman crocodilus (Linnaeus, 1758)        4.226556\n6 6 5069348947   Paleosuchus palpebrosus (Cuvier, 1807)       -3.782250\n  decimalLongitude         issues                           datasetKey\n1        -72.92169 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n2        -73.04728 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n3        -76.46489 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n4        -67.54108 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n5        -68.01636 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n6        -70.19956 cdround,inmano 596dae30-e116-4fad-96ec-e726aae1eeb7\n                      publishingOrgKey                      installationKey\n1 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n2 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n3 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n4 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n5 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n6 9d77fdeb-100f-4b29-98ad-4effdd824457 338bd13b-2c49-466b-9f4f-4a0b79f8ed1a\n                hostingOrganizationKey publishingCountry protocol\n1 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n2 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n3 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n4 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n5 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n6 9d77fdeb-100f-4b29-98ad-4effdd824457                CO      EML\n                    lastCrawled                    lastParsed crawlId\n1 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.141+00:00      15\n2 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.134+00:00      15\n3 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.106+00:00      15\n4 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:30.596+00:00      15\n5 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.392+00:00      15\n6 2025-05-30T20:22:36.072+00:00 2025-05-30T20:23:32.169+00:00      15\n       basisOfRecord individualCount occurrenceStatus taxonKey kingdomKey\n1 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n2 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n3 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n4 PRESERVED_SPECIMEN               1          PRESENT  2441394          1\n5 PRESERVED_SPECIMEN               1          PRESENT  8953936          1\n6 PRESERVED_SPECIMEN               1          PRESENT  2441396          1\n  phylumKey classKey familyKey genusKey speciesKey acceptedTaxonKey\n1        44 11493978   3238603  2441393    2441394          2441394\n2        44 11493978   3238603  2441393    2441394          2441394\n3        44 11493978   3238603  2441393    2441394          2441394\n4        44 11493978   3238603  2441393    2441394          2441394\n5        44 11493978   3238603  5220195    8953936          8953936\n6        44 11493978   3238603  2441393    2441396          2441396\n                    acceptedScientificName  kingdom   phylum        family\n1 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n2 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n3 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n4 Paleosuchus trigonatus (Schneider, 1801) Animalia Chordata Alligatoridae\n5       Caiman crocodilus (Linnaeus, 1758) Animalia Chordata Alligatoridae\n6   Paleosuchus palpebrosus (Cuvier, 1807) Animalia Chordata Alligatoridae\n        genus                 species genericName specificEpithet taxonRank\n1 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n2 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n3 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n4 Paleosuchus  Paleosuchus trigonatus Paleosuchus      trigonatus   SPECIES\n5      Caiman       Caiman crocodilus      Caiman      crocodilus   SPECIES\n6 Paleosuchus Paleosuchus palpebrosus Paleosuchus     palpebrosus   SPECIES\n  taxonomicStatus iucnRedListCategory      dateIdentified elevation\n1        ACCEPTED                  LC 2023-02-02T00:00:00       114\n2        ACCEPTED                  LC 2023-02-09T00:00:00       184\n3        ACCEPTED                  LC 2023-06-24T00:00:00       258\n4        ACCEPTED                  LC 2023-08-11T00:00:00       111\n5        ACCEPTED                  LC 2023-08-18T00:00:00       111\n6        ACCEPTED                  LC 2023-09-22T00:00:00       114\n  elevationAccuracy     continent stateProvince year month day  eventDate\n1                 0 SOUTH_AMERICA      Amazonas 2023     2   1 2023-02-01\n2                 0 SOUTH_AMERICA      Amazonas 2023     2   9 2023-02-09\n3                 0 SOUTH_AMERICA      Putumayo 2023     6  24 2023-06-24\n4                 0 SOUTH_AMERICA       Guainía 2023     8  11 2023-08-11\n5                 0 SOUTH_AMERICA       Vichada 2023     8  16 2023-08-16\n6                 0 SOUTH_AMERICA      Amazonas 2023     9  22 2023-09-22\n  startDayOfYear endDayOfYear               lastInterpreted\n1             32           32 2025-05-30T20:23:32.141+00:00\n2             40           40 2025-05-30T20:23:32.134+00:00\n3            175          175 2025-05-30T20:23:32.106+00:00\n4            223          223 2025-05-30T20:23:30.596+00:00\n5            228          228 2025-05-30T20:23:32.392+00:00\n6            265          265 2025-05-30T20:23:32.169+00:00\n                                                  license isSequenced\n1 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n2 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n3 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n4 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n5 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n6 http://creativecommons.org/licenses/by-nc/4.0/legalcode       FALSE\n            identifier facts relations isInCluster                   recordedBy\n1 SINCHI:SINCHI-R:3915  none      none        TRUE Grupo de herpetología Sinchi\n2 SINCHI:SINCHI-R:3943  none      none        TRUE Grupo de herpetología Sinchi\n3 SINCHI:SINCHI-R:3979  none      none        TRUE Grupo de herpetología Sinchi\n4 SINCHI:SINCHI-R:4119  none      none       FALSE Grupo de herpetología Sinchi\n5 SINCHI:SINCHI-R:4285  none      none       FALSE Grupo de herpetología Sinchi\n6 SINCHI:SINCHI-R:4262  none      none       FALSE Grupo de herpetología Sinchi\n          identifiedBy                               preparations\n1 Colector responsable Colecta definitiva: Animal completo (ETOH)\n2 Colector responsable Colecta definitiva: Animal completo (ETOH)\n3 Colector responsable Colecta definitiva: Animal completo (ETOH)\n4 Colector responsable Colecta definitiva: Animal completo (ETOH)\n5 Colector responsable Colecta definitiva: Animal completo (ETOH)\n6 Colector responsable Colecta definitiva: Animal completo (ETOH)\n  samplingProtocol dnaSequenceID geodeticDatum      class countryCode\n1   Búsqueda libre          none         WGS84 Crocodylia          CO\n2   Búsqueda libre          none         WGS84 Crocodylia          CO\n3   Búsqueda libre          none         WGS84 Crocodylia          CO\n4   Búsqueda libre          none         WGS84 Crocodylia          CO\n5   Búsqueda libre          none         WGS84 Crocodylia          CO\n6   Búsqueda libre          none         WGS84 Crocodylia          CO\n  recordedByIDs identifiedByIDs    gbifRegion  country publishedByGbifRegion\n1          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n2          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n3          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n4          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n5          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n6          none            none LATIN_AMERICA Colombia         LATIN_AMERICA\n  recordNumber         identifier.1                habitat institutionID\n1   SNC-H 2985 SINCHI:SINCHI-R:3915 Bosque de tierra firme 860.061.110-3\n2   SNC-H 3254 SINCHI:SINCHI-R:3943 Bosque de tierra firme 860.061.110-3\n3   SNC-H 3371 SINCHI:SINCHI-R:3979               Rastrojo 860.061.110-3\n4   SNC-H 3743 SINCHI:SINCHI-R:4119 Bosque de tierra firme 860.061.110-3\n5   SNC-H 3863 SINCHI:SINCHI-R:4285                   <NA> 860.061.110-3\n6   SNC-H 4394 SINCHI:SINCHI-R:4262 Bosque de tierra firme 860.061.110-3\n       county             municipality  verbatimCoordinateSystem collectionCode\n1 La Chorrera Comunidad de San Antonio Grados, minutos, segundos       SINCHI-R\n2 La Chorrera          Puerto Príncipe Grados, minutos, segundos       SINCHI-R\n3 Puerto Asís                   Cocayá Grados, minutos, segundos       SINCHI-R\n4    Cacahual    Comunidad de Chaquita Grados, minutos, segundos       SINCHI-R\n5    Cumaribo                     <NA> Grados, minutos, segundos       SINCHI-R\n6     Leticia          Sector Pucacuro Grados, minutos, segundos       SINCHI-R\n      gbifID language         occurrenceID           type\n1 5069348825       es SINCHI:SINCHI-R:3915 PhysicalObject\n2 5069348783       es SINCHI:SINCHI-R:3943 PhysicalObject\n3 5069348719       es SINCHI:SINCHI-R:3979 PhysicalObject\n4 5069345375       es SINCHI:SINCHI-R:4119 PhysicalObject\n5 5069349450       es SINCHI:SINCHI-R:4285 PhysicalObject\n6 5069348947       es SINCHI:SINCHI-R:4262 PhysicalObject\n                 taxonRemarks catalogNumber  disposition\n1 CITES:II | Endemismo: Falso          3915 En colección\n2 CITES:II | Endemismo: Falso          3943 En colección\n3 CITES:II | Endemismo: Falso          3979 En colección\n4 CITES:II | Endemismo: Falso          4119 En colección\n5 CITES:II | Endemismo: Falso          4285 En colección\n6 CITES:II | Endemismo: Falso          4262 En colección\n                                              institutionCode verbatimElevation\n1 Instituto Amazónico de Investigaciones Científicas (SINCHI)               114\n2 Instituto Amazónico de Investigaciones Científicas (SINCHI)               184\n3 Instituto Amazónico de Investigaciones Científicas (SINCHI)               258\n4 Instituto Amazónico de Investigaciones Científicas (SINCHI)               111\n5 Instituto Amazónico de Investigaciones Científicas (SINCHI)               111\n6 Instituto Amazónico de Investigaciones Científicas (SINCHI)               114\n                                                                                       collectionID\n1 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n2 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n3 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n4 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n5 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n6 RNC:215 | https://scientific-collections.gbif.org/collection/dce190b1-b7cf-44b7-b007-e40d4dc8d01e\n                                      name    sex gadm institutionKey\n1 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n2 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n3 Paleosuchus trigonatus (Schneider, 1801) Female <NA>           <NA>\n4 Paleosuchus trigonatus (Schneider, 1801)   <NA> <NA>           <NA>\n5       Caiman crocodilus (Linnaeus, 1758)   <NA> <NA>           <NA>\n6   Paleosuchus palpebrosus (Cuvier, 1807)   Male <NA>           <NA>\n  datasetName rightsHolder references associatedSequences taxonConceptID\n1        <NA>         <NA>       <NA>                <NA>           <NA>\n2        <NA>         <NA>       <NA>                <NA>           <NA>\n3        <NA>         <NA>       <NA>                <NA>           <NA>\n4        <NA>         <NA>       <NA>                <NA>           <NA>\n5        <NA>         <NA>       <NA>                <NA>           <NA>\n6        <NA>         <NA>       <NA>                <NA>           <NA>\n  locality occurrenceRemarks taxonID organismQuantity eventRemarks\n1     <NA>              <NA>    <NA>               NA         <NA>\n2     <NA>              <NA>    <NA>               NA         <NA>\n3     <NA>              <NA>    <NA>               NA         <NA>\n4     <NA>              <NA>    <NA>               NA         <NA>\n5     <NA>              <NA>    <NA>               NA         <NA>\n6     <NA>              <NA>    <NA>               NA         <NA>\n  identificationRemarks lifeStage higherGeography modified collectionKey\n1                  <NA>      <NA>            <NA>     <NA>          <NA>\n2                  <NA>      <NA>            <NA>     <NA>          <NA>\n3                  <NA>      <NA>            <NA>     <NA>          <NA>\n4                  <NA>      <NA>            <NA>     <NA>          <NA>\n5                  <NA>      <NA>            <NA>     <NA>          <NA>\n6                  <NA>      <NA>            <NA>     <NA>          <NA>\n  otherCatalogNumbers recordedByIDs.type recordedByIDs.value\n1                <NA>               <NA>                <NA>\n2                <NA>               <NA>                <NA>\n3                <NA>               <NA>                <NA>\n4                <NA>               <NA>                <NA>\n5                <NA>               <NA>                <NA>\n6                <NA>               <NA>                <NA>\n  identifiedByIDs.type identifiedByIDs.value vernacularName nomenclaturalCode\n1                 <NA>                  <NA>           <NA>              <NA>\n2                 <NA>                  <NA>           <NA>              <NA>\n3                 <NA>                  <NA>           <NA>              <NA>\n4                 <NA>                  <NA>           <NA>              <NA>\n5                 <NA>                  <NA>           <NA>              <NA>\n6                 <NA>                  <NA>           <NA>              <NA>\n  locationID organismRemarks identificationQualifier higherClassification\n1       <NA>            <NA>                    <NA>                 <NA>\n2       <NA>            <NA>                    <NA>                 <NA>\n3       <NA>            <NA>                    <NA>                 <NA>\n4       <NA>            <NA>                    <NA>                 <NA>\n5       <NA>            <NA>                    <NA>                 <NA>\n6       <NA>            <NA>                    <NA>                 <NA>\n  parentNameUsage rights dataGeneralizations fieldNumber locationRemarks\n1            <NA>   <NA>                <NA>        <NA>            <NA>\n2            <NA>   <NA>                <NA>        <NA>            <NA>\n3            <NA>   <NA>                <NA>        <NA>            <NA>\n4            <NA>   <NA>                <NA>        <NA>            <NA>\n5            <NA>   <NA>                <NA>        <NA>            <NA>\n6            <NA>   <NA>                <NA>        <NA>            <NA>\n  previousIdentifications networkKeys coordinateUncertaintyInMeters\n1                    <NA>        <NA>                            NA\n2                    <NA>        <NA>                            NA\n3                    <NA>        <NA>                            NA\n4                    <NA>        <NA>                            NA\n5                    <NA>        <NA>                            NA\n6                    <NA>        <NA>                            NA\n  dynamicProperties identificationReferences http...unknown.org.taxonRankID\n1              <NA>                     <NA>                             NA\n2              <NA>                     <NA>                             NA\n3              <NA>                     <NA>                             NA\n4              <NA>                     <NA>                             NA\n5              <NA>                     <NA>                             NA\n6              <NA>                     <NA>                             NA\n  georeferenceProtocol verbatimSRS georeferenceVerificationStatus\n1                 <NA>        <NA>                           <NA>\n2                 <NA>        <NA>                           <NA>\n3                 <NA>        <NA>                           <NA>\n4                 <NA>        <NA>                           <NA>\n5                 <NA>        <NA>                           <NA>\n6                 <NA>        <NA>                           <NA>\n  http...unknown.org.species georeferenceSources earliestPeriodOrLowestSystem\n1                       <NA>                <NA>                         <NA>\n2                       <NA>                <NA>                         <NA>\n3                       <NA>                <NA>                         <NA>\n4                       <NA>                <NA>                         <NA>\n5                       <NA>                <NA>                         <NA>\n6                       <NA>                <NA>                         <NA>\n  latestPeriodOrHighestSystem earliestEpochOrLowestSeries\n1                        <NA>                        <NA>\n2                        <NA>                        <NA>\n3                        <NA>                        <NA>\n4                        <NA>                        <NA>\n5                        <NA>                        <NA>\n6                        <NA>                        <NA>\n  latestEpochOrHighestSeries earliestAgeOrLowestStage latestAgeOrHighestStage\n1                       <NA>                     <NA>                    <NA>\n2                       <NA>                     <NA>                    <NA>\n3                       <NA>                     <NA>                    <NA>\n4                       <NA>                     <NA>                    <NA>\n5                       <NA>                     <NA>                    <NA>\n6                       <NA>                     <NA>                    <NA>\n  acceptedNameUsage lithostratigraphicTerms infraspecificEpithet\n1              <NA>                    <NA>                 <NA>\n2              <NA>                    <NA>                 <NA>\n3              <NA>                    <NA>                 <NA>\n4              <NA>                    <NA>                 <NA>\n5              <NA>                    <NA>                 <NA>\n6              <NA>                    <NA>                 <NA>\n  georeferencedBy georeferencedDate verbatimEventDate verbatimLocality\n1            <NA>              <NA>              <NA>             <NA>\n2            <NA>              <NA>              <NA>             <NA>\n3            <NA>              <NA>              <NA>             <NA>\n4            <NA>              <NA>              <NA>             <NA>\n5            <NA>              <NA>              <NA>             <NA>\n6            <NA>              <NA>              <NA>             <NA>\n  locationAccordingTo eventTime accessRights ownerInstitutionCode projectId\n1                <NA>      <NA>         <NA>                 <NA>      <NA>\n2                <NA>      <NA>         <NA>                 <NA>      <NA>\n3                <NA>      <NA>         <NA>                 <NA>      <NA>\n4                <NA>      <NA>         <NA>                 <NA>      <NA>\n5                <NA>      <NA>         <NA>                 <NA>      <NA>\n6                <NA>      <NA>         <NA>                 <NA>      <NA>\n  organismQuantityType georeferenceRemarks degreeOfEstablishment\n1                 <NA>                <NA>                  <NA>\n2                 <NA>                <NA>                  <NA>\n3                 <NA>                <NA>                  <NA>\n4                 <NA>                <NA>                  <NA>\n5                 <NA>                <NA>                  <NA>\n6                 <NA>                <NA>                  <NA>\n  coordinatePrecision eventType organismScope higherGeographyID waterBody\n1                  NA      <NA>          <NA>              <NA>      <NA>\n2                  NA      <NA>          <NA>              <NA>      <NA>\n3                  NA      <NA>          <NA>              <NA>      <NA>\n4                  NA      <NA>          <NA>              <NA>      <NA>\n5                  NA      <NA>          <NA>              <NA>      <NA>\n6                  NA      <NA>          <NA>              <NA>      <NA>\n  samplingEffort materialSampleID datasetID bibliographicCitation depth\n1           <NA>             <NA>      <NA>                  <NA>    NA\n2           <NA>             <NA>      <NA>                  <NA>    NA\n3           <NA>             <NA>      <NA>                  <NA>    NA\n4           <NA>             <NA>      <NA>                  <NA>    NA\n5           <NA>             <NA>      <NA>                  <NA>    NA\n6           <NA>             <NA>      <NA>                  <NA>    NA\n  depthAccuracy typeStatus namePublishedInYear nameAccordingTo identificationID\n1            NA       <NA>                  NA            <NA>               NA\n2            NA       <NA>                  NA            <NA>               NA\n3            NA       <NA>                  NA            <NA>               NA\n4            NA       <NA>                  NA            <NA>               NA\n5            NA       <NA>                  NA            <NA>               NA\n6            NA       <NA>                  NA            <NA>               NA\n  programmeAcronym http...unknown.org.recordID eventID\n1             <NA>                        <NA>    <NA>\n2             <NA>                        <NA>    <NA>\n3             <NA>                        <NA>    <NA>\n4             <NA>                        <NA>    <NA>\n5             <NA>                        <NA>    <NA>\n6             <NA>                        <NA>    <NA>\n  identificationVerificationStatus organismID establishmentMeans\n1                             <NA>       <NA>               <NA>\n2                             <NA>       <NA>               <NA>\n3                             <NA>       <NA>               <NA>\n4                             <NA>       <NA>               <NA>\n5                             <NA>       <NA>               <NA>\n6                             <NA>       <NA>               <NA>\n  namePublishedIn footprintWKT associatedReferences\n1            <NA>         <NA>                 <NA>\n2            <NA>         <NA>                 <NA>\n3            <NA>         <NA>                 <NA>\n4            <NA>         <NA>                 <NA>\n5            <NA>         <NA>                 <NA>\n6            <NA>         <NA>                 <NA>\n  http...unknown.org.recordEnteredBy pointRadiusSpatialFit footprintSRS\n1                               <NA>                    NA         <NA>\n2                               <NA>                    NA         <NA>\n3                               <NA>                    NA         <NA>\n4                               <NA>                    NA         <NA>\n5                               <NA>                    NA         <NA>\n6                               <NA>                    NA         <NA>\n  footprintSpatialFit fieldNotes distanceFromCentroidInMeters\n1                  NA       <NA>                           NA\n2                  NA       <NA>                           NA\n3                  NA       <NA>                           NA\n4                  NA       <NA>                           NA\n5                  NA       <NA>                           NA\n6                  NA       <NA>                           NA\n  associatedOccurrences informationWithheld verbatimTaxonRank\n1                  <NA>                <NA>              <NA>\n2                  <NA>                <NA>              <NA>\n3                  <NA>                <NA>              <NA>\n4                  <NA>                <NA>              <NA>\n5                  <NA>                <NA>              <NA>\n6                  <NA>                <NA>              <NA>\n  verbatimIdentification verbatimLabel materialEntityID islandGroup island\n1                   <NA>          <NA>             <NA>        <NA>   <NA>\n2                   <NA>          <NA>             <NA>        <NA>   <NA>\n3                   <NA>          <NA>             <NA>        <NA>   <NA>\n4                   <NA>          <NA>             <NA>        <NA>   <NA>\n5                   <NA>          <NA>             <NA>        <NA>   <NA>\n6                   <NA>          <NA>             <NA>        <NA>   <NA>\n  http...unknown.org.typifiedName http...unknown.org.photographer organismName\n1                            <NA>                            <NA>         <NA>\n2                            <NA>                            <NA>         <NA>\n3                            <NA>                            <NA>         <NA>\n4                            <NA>                            <NA>         <NA>\n5                            <NA>                            <NA>         <NA>\n6                            <NA>                            <NA>         <NA>\n  typifiedName relationshipRemarks reproductiveCondition\n1         <NA>                <NA>                  <NA>\n2         <NA>                <NA>                  <NA>\n3         <NA>                <NA>                  <NA>\n4         <NA>                <NA>                  <NA>\n5         <NA>                <NA>                  <NA>\n6         <NA>                <NA>                  <NA>\n```\n\n\n:::\n:::\n\n\n## **BREAKOUT SESSION 3**\n\n**Return to your discussion groups and discuss the following questions:**\n\n***-What factors that might introduce bias when we try to make comparisons across these datasets?***\n\n***-What are some sources of uncertainty?***\n\n***-How might we address these potential confounds prior to analysis and/or what should we keep in mind as we're interpreting our results?***\n\n::: {.callout-tip collapse=\"true\"}\nThe resolution and coverage of the data is likely one aspect that came up in your group discussions. As we move forward, we'll need to make some practical and philosophical decisions about how we bin the data given their varying resolutions. We'll also want to consider the sensitivity of our results to these various decisions. \n:::\n\nHere, we'll touch on several key taxonomic, temporal, and spatial considerations when endeavoring to make these datasets comparable.\n\n#### Taxonomy\n\nWe'll be using higher-level taxonomic groups for our analysis. Let's take a quick look to see what's here.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fossil occurrences\ntable(fossil_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      Alligatoridae        Crocodylidae          Gavialidae NO_FAMILY_SPECIFIED \n                 24                  27                  23                  40 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern occurrences\ntable(modern_occ_filter$family)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nAlligatoridae  Crocodylidae    Gavialidae \n         1933           492            79 \n```\n\n\n:::\n:::\n\n\nWe see that the same families are represented in our datasets. If you look at genera, you'll notice some differences. If we wanted to run an analysis at a finer taxonomic level, what would be some key considerations or steps that we would need to take?\n\n#### Temporal Bins\n\nEarlier, we noticed that our climatic data are available for 5-million-year intervals, which don't align perfectly with geological stages. For example, our 25-20 Ma interval crosses the Chattian and Aquitanian stages and the 20-15 Ma interval crosses the Burdigalian and Langhian stages. Each fossil occurrence has an associated age and interval range. We want to create time bins that roughly correspond with our climate layer so we can look at occurrences in relation to the temperature reconstructions. How might we approach this?\n\nFirst, let's take a look at the temporal distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\ntax_range_time(occdf = fossil_occ_filter, \n               name = \"occurrence_no\",\n               min_ma = \"min_ma\", \n               max_ma = \"max_ma\", \n               plot = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      taxon taxon_id max_ma min_ma range_myr n_occ\n10   643927        1  16.90  15.98      0.92     1\n16   650903        2  16.90  15.98      0.92     1\n29   742606        3  16.90  15.98      0.92     1\n30   742607        4  16.90  15.98      0.92     1\n31   742608        5  16.90  15.98      0.92     1\n73  1193267        6  16.90  15.98      0.92     1\n84  1386573        7  17.50  15.50      2.00     1\n21   707383        8  18.50  16.30      2.20     1\n35   897780        9  18.50  16.30      2.20     1\n38  1126562       10  18.50  16.30      2.20     1\n39  1126564       11  18.50  16.30      2.20     1\n40  1126567       12  18.50  16.30      2.20     1\n41  1126569       13  18.50  16.30      2.20     1\n42  1126589       14  18.50  16.30      2.20     1\n50  1132855       15  18.50  16.30      2.20     1\n79  1317496       16  18.50  16.30      2.20     1\n80  1332026       17  18.50  16.30      2.20     1\n94  1419304       18  18.50  16.30      2.20     1\n95  1419305       19  18.50  16.30      2.20     1\n99  1492206       20  18.50  16.30      2.20     1\n100 1511338       21  18.50  16.30      2.20     1\n26   724280       22  20.00  16.90      3.10     1\n27   724301       23  20.00  16.90      3.10     1\n103 1545816       24  20.00  15.98      4.02     1\n104 1545817       25  20.00  15.98      4.02     1\n3    395640       26  20.45  15.98      4.47     1\n5    442243       27  20.45  15.98      4.47     1\n6    474026       28  20.45  15.98      4.47     1\n7    474083       29  20.45  15.98      4.47     1\n8    544677       30  20.45  15.98      4.47     1\n9    544678       31  20.45  15.98      4.47     1\n11   650525       32  20.45  15.98      4.47     1\n13   650742       33  20.45  15.98      4.47     1\n14   650847       34  20.45  15.98      4.47     1\n19   656614       35  20.45  15.98      4.47     1\n20   663790       36  20.45  15.98      4.47     1\n28   724344       37  20.45  15.98      4.47     1\n32   834084       38  20.45  15.98      4.47     1\n33   834085       39  20.45  15.98      4.47     1\n34   834086       40  20.45  15.98      4.47     1\n36   966808       41  20.45  15.98      4.47     1\n37  1118091       42  20.45  15.98      4.47     1\n43  1129951       43  20.45  15.98      4.47     1\n44  1129952       44  20.45  15.98      4.47     1\n45  1129953       45  20.45  15.98      4.47     1\n46  1129954       46  20.45  15.98      4.47     1\n48  1130242       47  20.45  15.98      4.47     1\n51  1134802       48  20.45  15.98      4.47     1\n52  1134981       49  20.45  15.98      4.47     1\n53  1134982       50  20.45  15.98      4.47     1\n54  1156718       51  20.45  15.98      4.47     1\n74  1194149       52  20.45  15.98      4.47     1\n75  1200115       53  20.45  15.98      4.47     1\n78  1317147       54  20.45  15.98      4.47     1\n83  1382273       55  20.45  15.98      4.47     1\n85  1404977       56  20.45  15.98      4.47     1\n86  1404978       57  20.45  15.98      4.47     1\n87  1404979       58  20.45  15.98      4.47     1\n88  1404981       59  20.45  15.98      4.47     1\n89  1404983       60  20.45  15.98      4.47     1\n90  1404984       61  20.45  15.98      4.47     1\n91  1404985       62  20.45  15.98      4.47     1\n92  1404986       63  20.45  15.98      4.47     1\n93  1404987       64  20.45  15.98      4.47     1\n98  1474085       65  20.45  15.98      4.47     1\n101 1526494       66  20.45  15.98      4.47     1\n102 1526495       67  20.45  15.98      4.47     1\n105 1588137       68  20.45  15.98      4.47     1\n106 1594384       69  20.45  15.98      4.47     1\n107 1594392       70  20.45  15.98      4.47     1\n108 1598548       71  20.45  15.98      4.47     1\n109 1598549       72  20.45  15.98      4.47     1\n110 1598550       73  20.45  15.98      4.47     1\n111 1598551       74  20.45  15.98      4.47     1\n76  1312413       75  21.00  17.50      3.50     1\n77  1312414       76  21.00  17.50      3.50     1\n23   724262       77  22.40  20.00      2.40     1\n24   724267       78  22.40  20.00      2.40     1\n25   724271       79  22.40  20.00      2.40     1\n1    287884       80  23.04  20.45      2.59     1\n2    287885       81  23.04  20.45      2.59     1\n4    431435       82  23.04  15.98      7.06     1\n12   650612       83  23.04  15.98      7.06     1\n15   650889       84  23.04  15.98      7.06     1\n17   655656       85  23.04  15.98      7.06     1\n18   655657       86  23.04  15.98      7.06     1\n22   711270       87  23.04  20.45      2.59     1\n47  1130065       88  23.04  20.45      2.59     1\n49  1132854       89  23.04  15.98      7.06     1\n55  1190785       90  23.04  15.98      7.06     1\n56  1190787       91  23.04  15.98      7.06     1\n57  1190788       92  23.04  15.98      7.06     1\n58  1190789       93  23.04  15.98      7.06     1\n59  1190790       94  23.04  15.98      7.06     1\n60  1190792       95  23.04  15.98      7.06     1\n61  1190793       96  23.04  15.98      7.06     1\n62  1190794       97  23.04  15.98      7.06     1\n63  1190796       98  23.04  15.98      7.06     1\n64  1190798       99  23.04  15.98      7.06     1\n65  1190799      100  23.04  15.98      7.06     1\n66  1190800      101  23.04  15.98      7.06     1\n67  1190801      102  23.04  15.98      7.06     1\n68  1190802      103  23.04  15.98      7.06     1\n69  1190804      104  23.04  15.98      7.06     1\n70  1190805      105  23.04  15.98      7.06     1\n71  1190806      106  23.04  15.98      7.06     1\n72  1190807      107  23.04  15.98      7.06     1\n81  1341472      108  23.04  15.98      7.06     1\n82  1355143      109  23.04  15.98      7.06     1\n96  1448003      110  23.04  15.98      7.06     1\n97  1455432      111  23.04  20.00      3.04     1\n112 1605551      112  23.04  15.98      7.06     1\n113 1646318      113  23.04  20.45      2.59     1\n114 1691471      114  23.04  15.98      7.06     1\n```\n\n\n:::\n\n```{.r .cell-code}\naxis_geo(intervals = \"stages\")\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nOne option would be to bin the data by stage and use those as proxies for our 5-million-year climatic intervals.\nAnother approach might be to make near-equal-length bins within the 25-15 Ma range, and then assign occurrences to those bins. Let's try that here. \n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate time bins of ~5 million years within 25 and 15 Ma\nbins <- time_bins(interval = c(15,25), \n                  rank = \"stage\",\n                  size = 5, #here's where we specify the equal-length bins to approximate the resolution of our climatic data\n                  scale = \"GTS2020\",\n                  plot = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nTarget equal length time bins was set to 4.67 Myr. \nGenerated time bins have a mean length of 4.67 Myr and a standard deviation of 2.02 Myr.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Check bins\nhead(bins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  bin max_ma mid_ma min_ma duration_myr grouping_rank             intervals\n1   1  27.82 25.425  23.03         4.79         stage              Chattian\n2   2  23.03 21.735  20.44         2.59         stage            Aquitanian\n3   3  20.44 17.130  13.82         6.62         stage Langhian, Burdigalian\n   colour  font\n1 #80cdc1 black\n2 #80cdc1 black\n3 #80cdc1 black\n```\n\n\n:::\n:::\n\n\nAdditionally, there are a couple methods that we could use to bin the occurrences. Let's test out two approaches here to see how they differ. Hopefully you're starting to get a sense of how these various decisions might propagate to affect our results.\n\n::: {.cell}\n\n```{.r .cell-code}\n# `mid` method = uses the midpoint of age range to bin the occurrence\nfossil_occ_mid <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'mid')\n\n# `majority` method = bins an occurrence into the bin which it most overlaps with\nfossil_occ_maj <- bin_time(occdf = fossil_occ_filter,\n                      bins = bins,\n                      method = 'majority') \n\n# Compare the bin assignments\nbin_comparison <- fossil_occ_mid[c('occurrence_no','bin_assignment','n_bins')] %>% \n  left_join(fossil_occ_maj[c('occurrence_no','bin_assignment','n_bins')],by='occurrence_no') %>% \n  mutate(agreement = case_when(\n    bin_assignment.x == bin_assignment.y ~ \"yes\"\n  ))\n```\n:::\n\n\nIn this case, they actually match up! Since these approaches yielded the same results, we'll use the 'maj' dataset moving forward.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Renaming\nfossil_occ_bin <- fossil_occ_maj\n\n# How many occurrences per bin?\ntable(fossil_occ_bin$bin_assignment)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  2   3 \n  9 105 \n```\n\n\n:::\n:::\n\n\nWe see that most of the data falls into bin 3 (20.44-13.82 Ma, midpoint=17.130 Ma), with some occurrences in bin 2 (23.03-20.44 Ma, midpoint=21.735 Ma).\n\n-  Bin 2 overlaps with our 25-20 Ma climate raster\n-  Bin 3 overlaps with our 20-15 Ma climate raster\n\nOur GBIF dataset already contains just modern data, which overlaps with our WorldClim climate layer, so no additional binning is needed. \n\nOK, so now we have some temporal bins to facilitate our comparisons over time with the climatic data.\n\n\n#### Spatial Bins\n\nWe also observed that the spatial resolution of the climatic data differed between the past and present. Additionally, the uncertainties in the coordinates for our modern and fossil occurrences differ, especially since we'll need to rely on plate models to palaeorotate the geographic positions of our fossil occurrences. How might we deal with this?\n\nLike before, let's take a look at the spatial distribution of our fossil occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(fossil_occ_bin) +\n  geom_sf(data = world) +\n  geom_point(aes(x = lng, y = lat)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nBut wait, remember that we need to paleorotate our coordinates before we proceed. We could run a couple different plate models to check the sensitivity.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Palaeorotation\nfossil_occ_bin_rot <- palaeorotate(fossil_occ_bin,\n                                   lng = \"lng\",\n                                   lat = \"lat\",\n                                   age = \"bin_midpoint\", \n                                   model  = \"PALEOMAP\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nPALEOMAP\n```\n\n\n:::\n\n```{.r .cell-code}\n# Remove NAs\nfossil_occ_bin_rot <- fossil_occ_bin_rot %>%\n  dplyr::filter(!is.na(p_lng) & !is.na(p_lat))\n\n# Plot palaeorotated coordinates\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\nggplot(fossil_occ_bin_rot) +\n  geom_sf(data = world) +\n  geom_point(aes(x = p_lng, y = p_lat)) +\n  labs(x = \"Paleolongitude (º)\",\n       y = \"Paleolatitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nFor comparison, let's also plot the modern occurrences.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load in a world map\nworld <- ne_countries(scale = \"small\", returnclass = \"sf\")\n\n# Plot the geographic coordinates of each locality over the world map\nggplot(modern_occ_filter) +\n  geom_sf(data = world) +\n  geom_point(aes(x = decimalLongitude, y = decimalLatitude)) +\n  labs(x = \"Longitude (º)\",\n       y = \"Latitude (º)\")+ \n  theme_void()\n```\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nLooking at these spatial representations of the data, we can really visualise the difference in sampling effort. How might we account for the spatial structure of the data in our analysis?\n\nAnother challenge stems from aligning these occurrences with the spatial explicit climate layers. A simple approach would be to just extract the mean temperature value at each of the (palaeo)coordinates. Alternatively, we might consider adding a bit of a buffer around each point to incorporate geographic uncertainty and variation in the climatic data. A third, albeit more complex approach, would be to assign the occurrences to spatial bins so we can match them up to the climate layers (e.g., check out the `bin_space` function). We'd also need to resolve the difference the spatial resolutions between the past and present climatic data, potentially by coarsening the modern dataset.\n\nWe'll keep things simple and show the first approach here.\n\n\n## IV. Data extraction and visualisation\n\nWe have our data binned temporally to match the climate layers, so let's create separate datasets for each time bin.\n\n::: {.cell}\n\n```{.r .cell-code}\n# 25-20 Ma climate interval\npoints_20 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 2)\n\n# 20-15 Ma climate interval\npoints_15 <- fossil_occ_bin_rot %>%\n  dplyr::filter(bin_assignment == 3) \n\n# Modern interval (whole dataset)\npoints_mod <- modern_occ_filter\n```\n:::\n\n\nNext, let's set up our points and ensure they're on the same coordinate system. Recall that this was one of the things we wanted to check when we outlined our workflow for the climatic data at the beginning of the session.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Turn points into spatial features\npoints_sf_20 <- st_as_sf(x = points_20, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_15 <- st_as_sf(x = points_15, coords = c(\"p_lng\", \"p_lat\"))\npoints_sf_mod <- st_as_sf(x = points_mod, coords = c(\"decimalLongitude\", \"decimalLatitude\"))\n\n# Set coordinate system (WGS84) for occurrences\nst_crs(points_sf_20) <- st_crs(4326)\nst_crs(points_sf_15) <- st_crs(4326)\nst_crs(points_sf_mod) <- st_crs(4326)\n```\n:::\n\n\nWe're now ready to extract the climatic data at each coordinate!\n\n::: {.cell}\n\n```{.r .cell-code}\n# Past temperature (Scotese 2022)\nscotese_temp_20 <- raster::extract(x = scotese.temp$Aquitanian, \n                           y = points_sf_20, \n                           sp = TRUE, \n                           cellnumbers = TRUE)\n\nscotese_temp_15 <- raster::extract(x = scotese.temp$Burdigalian, \n                                     y = points_sf_15, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n\n# Modern temperature (WorldClim)\nmodern_temp <- raster::extract(x = modern.mean, \n                                     y = points_sf_mod, \n                                     sp = TRUE, \n                                     cellnumbers = TRUE)\n```\n:::\n\n\nLet's take a look! How does the temperature range inhabited by Crocodylia in deep-time compare to that seen in the present?\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aquitanian range (25-20 Ma)\nrange(scotese_temp_20$Aquitanian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.43755 26.87847\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_20$Aquitanian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.440919\n```\n\n\n:::\n\n```{.r .cell-code}\n# Burdigalian/Langhian range (20-15 Ma)\nrange(scotese_temp_15$Burdigalian, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.28417 33.11024\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(scotese_temp_15$Burdigalian, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 18.82607\n```\n\n\n:::\n\n```{.r .cell-code}\n# Modern range\nrange(modern_temp@data$layer, na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  8.465333 30.584333\n```\n\n\n:::\n\n```{.r .cell-code}\ndiff(range(modern_temp@data$layer, na.rm=T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 22.119\n```\n\n\n:::\n:::\n\n\nFinally, let's plot the data.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Organise data for plotting\npalaeo_temp <- rbind(data.frame(Bin = rep(\"Burdigalian\", length(scotese_temp_15$Burdigalian)), #\n                           Temperature = scotese_temp_15$Burdigalian), \n                      data.frame(Bin = rep(\"Aquitanian\", length(scotese_temp_20$Aquitanian)), \n                                  Temperature = scotese_temp_20$Aquitanian),\n                      data.frame(Bin = rep(\"Modern\", length(modern_temp@data$layer)), \n                                  Temperature = modern_temp@data$layer))\n\n# Make box plot of temperature range\nggplot(palaeo_temp, aes(x = Bin, y = Temperature)) +\n  geom_jitter(color=\"gray80\",size=2,alpha=0.5)+\n  geom_boxplot(width=0.5,outlier.shape = NA)+\n  labs(x=\"Time interval\", y=\"Temperature (ºC)\")+\n  theme_bw()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 12 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 12 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](CPEG_Workshop_Data_Processing_II_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nWhen looking in particular at the better sampled intervals, we find that the mean temperature and range of Crocodylia were quite similar between the Miocene and Modern.\nHow might we interpret these results? How might this interpretation be shaped by the caveats we pointed out along the way?\n\nUltimately, our goal was to provide a workflow for merging different types of datasets and thinking critically about some of these caveats. These taxonomic, spatial, and temporal considerations are critical to address and report in palaeobiological and palaeoecological research in general---but particularly studies aiming to cross the palaeontological-ecological gap. We hope you can adapt and learn from this script as you venture forward with your own exciting reserach questions and datasets!\n",
    "supporting": [
      "CPEG_Workshop_Data_Processing_II_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}